/**
 * Demo Data for B2C Platform
 * Replace with actual API calls in production
 */

export const demoEvents = [
  {
    id: "1",
    title: "Summer Music Festival 2025",
    venue: "Curtis Hixon Waterfront Park",
    date: "June 15, 2025",
    time: "6:00 PM",
    image: "/api/placeholder/400/300",
    priceMin: 45,
    priceMax: 125,
    attendeeCount: 234,
    slug: "summer-music-festival-2025",
  },
  {
    id: "2",
    title: "Jazz Night at The Ritz",
    venue: "The Ritz Ybor",
    date: "June 20, 2025",
    time: "8:00 PM",
    image: "/api/placeholder/400/300",
    priceMin: 30,
    priceMax: 60,
    attendeeCount: 156,
    slug: "jazz-night-ritz",
  },
  {
    id: "3",
    title: "Electronic Sunset Sessions",
    venue: "Armature Works",
    date: "June 25, 2025",
    time: "5:00 PM",
    image: "/api/placeholder/400/300",
    priceMin: 25,
    priceMax: 50,
    attendeeCount: 189,
    slug: "electronic-sunset",
  },
];

export const demoArtists = [
  {
    id: "1",
    name: "The Midnight Collective",
    genre: "Electronic • House",
    image: "/api/placeholder/400/400",
    followers: 50000,
    upcomingShows: 3,
    slug: "the-midnight-collective",
    spotifyId: "abc123",
  },
  {
    id: "2",
    name: "Luna Eclipse",
    genre: "Indie • Alternative",
    image: "/api/placeholder/400/400",
    followers: 32000,
    upcomingShows: 2,
    slug: "luna-eclipse",
    spotifyId: "def456",
  },
  {
    id: "3",
    name: "Bass Frequency",
    genre: "EDM • Dubstep",
    image: "/api/placeholder/400/400",
    followers: 75000,
    upcomingShows: 5,
    slug: "bass-frequency",
    spotifyId: "ghi789",
  },
  {
    id: "4",
    name: "Acoustic Souls",
    genre: "Folk • Singer-Songwriter",
    image: "/api/placeholder/400/400",
    followers: 28000,
    upcomingShows: 1,
    slug: "acoustic-souls",
    spotifyId: "jkl012",
  },
];

export const demoShops = [
  {
    id: "1",
    name: "The Midnight Collective Store",
    type: "artist" as const,
    logo: "/api/placeholder/200/200",
    description: "Official merch, vinyl, and exclusive drops",
    featuredProducts: ["/api/placeholder/100/100", "/api/placeholder/100/100", "/api/placeholder/100/100"],
    slug: "midnight-collective",
    shopifyStoreId: "store123",
  },
  {
    id: "2",
    name: "The Ritz Ybor Merch",
    type: "venue" as const,
    logo: "/api/placeholder/200/200",
    description: "Venue apparel and collectibles",
    featuredProducts: ["/api/placeholder/100/100", "/api/placeholder/100/100"],
    slug: "ritz-ybor",
    shopifyStoreId: "store456",
  },
  {
    id: "3",
    name: "Sunset Records",
    type: "label" as const,
    logo: "/api/placeholder/200/200",
    description: "Vinyl, compilations, and label merch",
    featuredProducts: ["/api/placeholder/100/100", "/api/placeholder/100/100", "/api/placeholder/100/100"],
    slug: "sunset-records",
    shopifyStoreId: "store789",
  },
  {
    id: "4",
    name: "Urban Threads",
    type: "brand" as const,
    logo: "/api/placeholder/200/200",
    description: "Local streetwear and lifestyle brand",
    featuredProducts: ["/api/placeholder/100/100", "/api/placeholder/100/100"],
    slug: "urban-threads",
    shopifyStoreId: "store012",
  },
];

export const demoDestinations = [
  {
    id: "1",
    name: "The Epicurean Hotel",
    category: "stay" as const,
    image: "/api/placeholder/400/300",
    address: "1207 S Howard Ave, FL",
    distance: "0.5mi",
    priceLevel: 3,
    rating: 4.5,
    reviewCount: 342,
    slug: "epicurean-hotel",
    googlePlaceId: "place123",
  },
  {
    id: "2",
    name: "Ulele Restaurant",
    category: "dining" as const,
    image: "/api/placeholder/400/300",
    address: "1810 N Highland Ave, FL",
    distance: "0.8mi",
    priceLevel: 2,
    rating: 4.7,
    reviewCount: 1256,
    slug: "ulele-restaurant",
    googlePlaceId: "place456",
  },
  {
    id: "3",
    name: "Hyde Park Village",
    category: "shopping" as const,
    image: "/api/placeholder/400/300",
    address: "1602 W Snow Ave, FL",
    distance: "1.2mi",
    priceLevel: 2,
    rating: 4.4,
    reviewCount: 567,
    slug: "hyde-park-village",
    googlePlaceId: "place789",
  },
  {
    id: "4",
    name: "Sacred Sounds Yoga",
    category: "wellness" as const,
    image: "/api/placeholder/400/300",
    address: "1234 E 7th Ave, FL",
    distance: "0.3mi",
    priceLevel: 2,
    rating: 4.9,
    reviewCount: 189,
    slug: "sacred-sounds-yoga",
    googlePlaceId: "place012",
  },
];

export const demoAdventures = [
  {
    id: "1",
    name: "Riverwalk Tour",
    category: "tour" as const,
    image: "/api/placeholder/400/300",
    description: "Explore the waterfront on this guided walking tour featuring historic landmarks, public art, and stunning bay views.",
    duration: "2 hours",
    price: 25,
    slug: "riverwalk-tour",
  },
  {
    id: "2",
    name: "Ybor City Food Tour",
    category: "food" as const,
    image: "/api/placeholder/400/300",
    description: "Taste your way through the historic Latin Quarter with stops at authentic Cuban restaurants and local favorites.",
    duration: "3 hours",
    price: 65,
    slug: "ybor-city-food-tour",
  },
  {
    id: "3",
    name: "Kayak Adventure on Hillsborough River",
    category: "outdoor" as const,
    image: "/api/placeholder/400/300",
    description: "Paddle through natural Florida beauty just minutes from downtown. Perfect for all skill levels.",
    duration: "2.5 hours",
    price: 45,
    slug: "hillsborough-kayak",
  },
  {
    id: "4",
    name: "Street Art Walking Tour",
    category: "cultural" as const,
    image: "/api/placeholder/400/300",
    description: "Discover the vibrant street art scene with a local artist guide through Seminole Heights and downtown.",
    duration: "2 hours",
    price: 30,
    slug: "street-art-tour",
  },
];

export const demoMembershipTiers = [
  {
    name: "Explorer",
    price: 0,
    period: "Free Forever",
    description: "Perfect for discovering the local scene",
    features: [
      "Browse all events",
      "Community feed access",
      "Basic event recommendations",
      "Shop marketplace access",
      "Destination guides",
    ],
    cta: "Start Free",
    popular: false,
  },
  {
    name: "Member",
    price: 19,
    period: "per month",
    description: "The full GVTEWAY experience",
    features: [
      "Everything in Explorer",
      "Early ticket access (24h)",
      "Member-only pricing (10-20% off)",
      "Priority entry at venues",
      "Exclusive member events",
      "Advanced recommendations",
      "Save unlimited favorites",
      "Trip planning tools",
      "Member badge & profile",
    ],
    cta: "Join Now",
    popular: true,
  },
  {
    name: "VIP",
    price: 49,
    period: "per month",
    description: "For the ultimate insider",
    features: [
      "Everything in Member",
      "48h early ticket access",
      "VIP pricing (20-30% off)",
      "Dedicated concierge",
      "Backstage access opportunities",
      "Secret shows & experiences",
      "Artist meet & greets",
      "Free merchandise credits",
      "Priority support",
      "Exclusive VIP lounge access",
    ],
    cta: "Go VIP",
    popular: false,
  },
];
