/**
 * EXPANDED Organizational Hierarchy Seed Data
 * Comprehensive catalog including Film, TV, Broadcast, and Theatrical Production
 * Approximately 350+ positions across all industries
 */

export interface Position {
  code: string;
  title: string;
  level: 'entry' | 'mid' | 'senior' | 'lead' | 'manager' | 'director' | 'executive';
  area?: string; // Area/Field classification (e.g., 'Technical', 'Administrative', 'Creative', 'Operations')
  description?: string;
  alternateNames?: string[];
  requiredCertifications?: string[];
  typicalResponsibilities?: string[];
}

export interface Team {
  code: string;
  name: string;
  description?: string;
  positions: Position[];
}

export interface Department {
  code: string;
  name: string;
  description?: string;
  teams: Team[];
}

export const ORGANIZATIONAL_HIERARCHY_EXPANDED: Department[] = [
  {
    code: '0000',
    name: 'Executive',
    description: 'C-suite and executive leadership',
    teams: [
      {
        code: '0100',
        name: 'Executive Leadership',
        description: 'C-level executives and senior leadership',
        positions: [
          { code: '0101', title: 'Chief Executive Officer', level: 'executive', alternateNames: ['CEO'] },
          { code: '0102', title: 'Chief Operating Officer', level: 'executive', alternateNames: ['COO'] },
          { code: '0103', title: 'Chief Financial Officer', level: 'executive', alternateNames: ['CFO'] },
          { code: '0104', title: 'Chief Technology Officer', level: 'executive', alternateNames: ['CTO'] },
          { code: '0105', title: 'Chief Marketing Officer', level: 'executive', alternateNames: ['CMO'] },
          { code: '0106', title: 'Chief Creative Officer', level: 'executive', alternateNames: ['CCO'] },
          { code: '0107', title: 'Chief Experience Officer', level: 'executive', alternateNames: ['CXO'] },
          { code: '0108', title: 'Chief Content Officer', level: 'executive' },
          { code: '0109', title: 'President', level: 'executive' },
          { code: '0110', title: 'Vice President', level: 'executive', alternateNames: ['VP'] },
          { code: '0111', title: 'Executive Producer', level: 'executive', alternateNames: ['EP'] },
          { code: '0112', title: 'Showrunner', level: 'executive' },
        ],
      },
      {
        code: '0200',
        name: 'Finance & Accounting',
        description: 'Financial management and accounting',
        positions: [
          { code: '0201', title: 'Finance Director', level: 'director' },
          { code: '0202', title: 'Controller', level: 'manager' },
          { code: '0203', title: 'Senior Accountant', level: 'senior' },
          { code: '0204', title: 'Accountant', level: 'mid' },
          { code: '0205', title: 'Payroll Manager', level: 'manager' },
          { code: '0206', title: 'Production Accountant', level: 'senior' },
          { code: '0207', title: 'Assistant Accountant', level: 'mid' },
          { code: '0208', title: 'Bookkeeper', level: 'entry' },
          { code: '0209', title: 'Financial Analyst', level: 'mid' },
        ],
      },
      {
        code: '0300',
        name: 'Legal & Business Affairs',
        description: 'Legal counsel and business affairs',
        positions: [
          { code: '0301', title: 'General Counsel', level: 'executive' },
          { code: '0302', title: 'Legal Director', level: 'director' },
          { code: '0303', title: 'Entertainment Lawyer', level: 'senior' },
          { code: '0304', title: 'Contracts Manager', level: 'manager' },
          { code: '0305', title: 'Rights & Clearances Manager', level: 'manager' },
          { code: '0306', title: 'Business Affairs Executive', level: 'senior' },
          { code: '0307', title: 'Paralegal', level: 'mid' },
          { code: '0308', title: 'Legal Assistant', level: 'entry' },
        ],
      },
      {
        code: '0400',
        name: 'Human Resources',
        description: 'HR, talent management, and employee relations',
        positions: [
          { code: '0401', title: 'HR Director', level: 'director' },
          { code: '0402', title: 'HR Manager', level: 'manager' },
          { code: '0403', title: 'Talent Acquisition Manager', level: 'manager' },
          { code: '0404', title: 'Recruiter', level: 'mid' },
          { code: '0405', title: 'HR Coordinator', level: 'mid' },
          { code: '0406', title: 'Payroll Specialist', level: 'mid' },
          { code: '0407', title: 'Benefits Administrator', level: 'mid' },
          { code: '0408', title: 'HR Assistant', level: 'entry' },
          { code: '0409', title: 'Employee Relations Manager', level: 'manager' },
          { code: '0410', title: 'Compensation Analyst', level: 'mid' },
          { code: '0411', title: 'HR Business Partner', level: 'senior' },
          { code: '0412', title: 'Diversity & Inclusion Manager', level: 'manager' },
        ],
      },
      {
        code: '0500',
        name: 'Administration',
        description: 'Administrative support and office management',
        positions: [
          { code: '0501', title: 'Chief of Staff', level: 'executive' },
          { code: '0502', title: 'Office Manager', level: 'manager' },
          { code: '0503', title: 'Executive Assistant', level: 'senior' },
          { code: '0504', title: 'Administrative Assistant', level: 'mid' },
          { code: '0505', title: 'Receptionist', level: 'entry' },
          { code: '0506', title: 'Office Coordinator', level: 'mid' },
          { code: '0507', title: 'Project Administrator', level: 'mid' },
          { code: '0508', title: 'Data Entry Specialist', level: 'entry' },
        ],
      },
      {
        code: '0600',
        name: 'Procurement & Purchasing',
        description: 'Purchasing, vendor management, and procurement',
        positions: [
          { code: '0601', title: 'Procurement Director', level: 'director' },
          { code: '0602', title: 'Purchasing Manager', level: 'manager' },
          { code: '0603', title: 'Buyer', level: 'mid' },
          { code: '0604', title: 'Purchasing Agent', level: 'mid' },
          { code: '0605', title: 'Vendor Manager', level: 'manager' },
          { code: '0606', title: 'Contract Specialist', level: 'senior' },
          { code: '0607', title: 'Procurement Coordinator', level: 'mid' },
        ],
      },
    ],
  },
  {
    code: '1000',
    name: 'Creative',
    description: 'Creative design, content, film, TV, and theatrical production',
    teams: [
      {
        code: '1100',
        name: 'Creative Direction',
        positions: [
          { code: '1101', title: 'Creative Director', level: 'director' },
          { code: '1102', title: 'Associate Creative Director', level: 'senior' },
          { code: '1103', title: 'Art Director', level: 'senior' },
          { code: '1104', title: 'Senior Designer', level: 'senior' },
          { code: '1105', title: 'Graphic Designer', level: 'mid' },
          { code: '1106', title: 'Junior Designer', level: 'entry' },
          { code: '1107', title: 'UI/UX Designer', level: 'mid' },
          { code: '1108', title: 'Brand Designer', level: 'mid' },
          { code: '1109', title: 'Production Designer', level: 'senior' },
          { code: '1110', title: 'Set Designer', level: 'mid' },
        ],
      },
      {
        code: '1200',
        name: 'Content Production',
        positions: [
          { code: '1201', title: 'Content Director', level: 'director' },
          { code: '1202', title: 'Content Producer', level: 'senior' },
          { code: '1203', title: 'Video Producer', level: 'mid' },
          { code: '1204', title: 'Photographer', level: 'mid' },
          { code: '1205', title: 'Videographer', level: 'mid' },
          { code: '1206', title: 'Video Editor', level: 'mid' },
          { code: '1207', title: 'Motion Graphics Designer', level: 'mid' },
          { code: '1208', title: 'Animator', level: 'mid' },
          { code: '1209', title: 'VFX Artist', level: 'senior' },
          { code: '1210', title: 'Colorist', level: 'senior' },
          { code: '1211', title: 'Compositor', level: 'mid' },
        ],
      },
      {
        code: '1300',
        name: 'Writing & Story',
        positions: [
          { code: '1301', title: 'Head Writer', level: 'director' },
          { code: '1302', title: 'Screenwriter', level: 'senior' },
          { code: '1303', title: 'Story Editor', level: 'senior' },
          { code: '1304', title: 'Script Consultant', level: 'senior' },
          { code: '1305', title: 'Copywriter', level: 'mid' },
          { code: '1306', title: 'Senior Copywriter', level: 'senior' },
          { code: '1307', title: 'Content Writer', level: 'mid' },
          { code: '1308', title: 'Playwright', level: 'senior' },
          { code: '1309', title: 'Dramaturg', level: 'senior' },
        ],
      },
      {
        code: '1400',
        name: 'Film & TV Production',
        description: 'Film and television production roles',
        positions: [
          { code: '1401', title: 'Producer', level: 'senior' },
          { code: '1402', title: 'Line Producer', level: 'senior' },
          { code: '1403', title: 'Co-Producer', level: 'senior' },
          { code: '1404', title: 'Associate Producer', level: 'mid' },
          { code: '1405', title: 'Production Coordinator', level: 'mid' },
          { code: '1406', title: 'Production Assistant', level: 'entry', alternateNames: ['PA'] },
          { code: '1407', title: 'Unit Production Manager', level: 'manager', alternateNames: ['UPM'] },
          { code: '1408', title: 'First Assistant Director', level: 'senior', alternateNames: ['1st AD'] },
          { code: '1409', title: 'Second Assistant Director', level: 'mid', alternateNames: ['2nd AD'] },
          { code: '1410', title: 'Script Supervisor', level: 'mid' },
          { code: '1411', title: 'Location Manager', level: 'manager' },
          { code: '1412', title: 'Location Scout', level: 'mid' },
          { code: '1413', title: 'Location Assistant', level: 'entry' },
        ],
      },
      {
        code: '1500',
        name: 'Directing',
        description: 'Directors for film, TV, and theater',
        positions: [
          { code: '1501', title: 'Director', level: 'director' },
          { code: '1502', title: 'Assistant Director', level: 'senior' },
          { code: '1503', title: 'Second Unit Director', level: 'senior' },
          { code: '1504', title: 'Theatrical Director', level: 'director' },
          { code: '1505', title: 'Resident Director', level: 'senior' },
        ],
      },
      {
        code: '1600',
        name: 'Art Department',
        description: 'Art department for film, TV, and theater',
        positions: [
          { code: '1601', title: 'Production Designer', level: 'director' },
          { code: '1602', title: 'Art Director', level: 'senior' },
          { code: '1603', title: 'Assistant Art Director', level: 'mid' },
          { code: '1604', title: 'Set Decorator', level: 'senior' },
          { code: '1605', title: 'Lead Set Dresser', level: 'lead' },
          { code: '1606', title: 'Set Dresser', level: 'mid' },
          { code: '1607', title: 'Prop Master', level: 'lead' },
          { code: '1608', title: 'Assistant Prop Master', level: 'senior' },
          { code: '1609', title: 'Props Buyer', level: 'mid' },
          { code: '1610', title: 'Scenic Artist', level: 'mid' },
          { code: '1611', title: 'Construction Coordinator', level: 'manager' },
          { code: '1612', title: 'Scenic Carpenter', level: 'mid' },
        ],
      },
      {
        code: '1700',
        name: 'Costume & Wardrobe',
        description: 'Costume design and wardrobe',
        positions: [
          { code: '1701', title: 'Costume Designer', level: 'senior' },
          { code: '1702', title: 'Assistant Costume Designer', level: 'mid' },
          { code: '1703', title: 'Wardrobe Supervisor', level: 'lead' },
          { code: '1704', title: 'Wardrobe Assistant', level: 'mid' },
          { code: '1705', title: 'Costume Coordinator', level: 'mid' },
          { code: '1706', title: 'Costume Buyer', level: 'mid' },
          { code: '1707', title: 'Seamstress/Tailor', level: 'mid' },
        ],
      },
      {
        code: '1800',
        name: 'Hair & Makeup',
        description: 'Hair styling and makeup artistry',
        positions: [
          { code: '1801', title: 'Key Makeup Artist', level: 'lead' },
          { code: '1802', title: 'Makeup Artist', level: 'mid' },
          { code: '1803', title: 'Special Effects Makeup Artist', level: 'senior' },
          { code: '1804', title: 'Key Hair Stylist', level: 'lead' },
          { code: '1805', title: 'Hair Stylist', level: 'mid' },
          { code: '1806', title: 'Wig Master', level: 'senior' },
          { code: '1807', title: 'Prosthetics Designer', level: 'senior' },
          { code: '1808', title: 'Body Painter', level: 'mid' },
        ],
      },
      {
        code: '1900',
        name: 'Photography',
        description: 'Photography and imaging services',
        positions: [
          { code: '1901', title: 'Director of Photography', level: 'director', alternateNames: ['Photo Director'] },
          { code: '1902', title: 'Lead Photographer', level: 'senior' },
          { code: '1903', title: 'Photographer', level: 'mid' },
          { code: '1904', title: 'Assistant Photographer', level: 'entry' },
          { code: '1905', title: 'Photo Editor', level: 'mid' },
          { code: '1906', title: 'Retoucher', level: 'mid' },
          { code: '1907', title: 'Photo Archivist', level: 'mid' },
        ],
      },
    ],
  },
  {
    code: '2000',
    name: 'Marketing',
    description: 'Marketing, advertising, PR, and promotions',
    teams: [
      {
        code: '2100',
        name: 'Marketing Strategy',
        positions: [
          { code: '2101', title: 'Marketing Director', level: 'director' },
          { code: '2102', title: 'Marketing Manager', level: 'manager' },
          { code: '2103', title: 'Marketing Strategist', level: 'senior' },
          { code: '2104', title: 'Marketing Coordinator', level: 'mid' },
          { code: '2105', title: 'Marketing Assistant', level: 'entry' },
          { code: '2106', title: 'Campaign Manager', level: 'manager' },
          { code: '2107', title: 'Brand Manager', level: 'manager' },
        ],
      },
      {
        code: '2200',
        name: 'Digital Marketing',
        positions: [
          { code: '2201', title: 'Digital Marketing Director', level: 'director' },
          { code: '2202', title: 'Digital Marketing Manager', level: 'manager' },
          { code: '2203', title: 'Social Media Manager', level: 'manager' },
          { code: '2204', title: 'Social Media Coordinator', level: 'mid' },
          { code: '2205', title: 'SEO Specialist', level: 'mid' },
          { code: '2206', title: 'SEM Specialist', level: 'mid' },
          { code: '2207', title: 'Email Marketing Specialist', level: 'mid' },
          { code: '2208', title: 'Content Marketing Manager', level: 'manager' },
          { code: '2209', title: 'Community Manager', level: 'mid' },
        ],
      },
      {
        code: '2300',
        name: 'Public Relations',
        positions: [
          { code: '2301', title: 'PR Director', level: 'director' },
          { code: '2302', title: 'PR Manager', level: 'manager' },
          { code: '2303', title: 'PR Specialist', level: 'mid' },
          { code: '2304', title: 'Media Relations Specialist', level: 'mid' },
          { code: '2305', title: 'Communications Coordinator', level: 'mid' },
          { code: '2306', title: 'Publicist', level: 'senior' },
          { code: '2307', title: 'Press Agent', level: 'mid' },
          { code: '2308', title: 'Unit Publicist', level: 'senior' },
        ],
      },
      {
        code: '2400',
        name: 'Sponsorship & Partnerships',
        positions: [
          { code: '2401', title: 'Sponsorship Director', level: 'director' },
          { code: '2402', title: 'Sponsorship Manager', level: 'manager' },
          { code: '2403', title: 'Sponsorship Coordinator', level: 'mid' },
          { code: '2404', title: 'Partnership Manager', level: 'manager' },
          { code: '2405', title: 'Account Executive', level: 'mid' },
          { code: '2406', title: 'Brand Partnerships Manager', level: 'manager' },
          { code: '2407', title: 'Activation Manager', level: 'manager' },
          { code: '2408', title: 'Sponsorship Sales Executive', level: 'mid' },
        ],
      },
      {
        code: '2500',
        name: 'Media & Broadcasting',
        description: 'Media relations, broadcasting, and journalism',
        positions: [
          { code: '2501', title: 'Media Director', level: 'director' },
          { code: '2502', title: 'Media Manager', level: 'manager' },
          { code: '2503', title: 'Broadcast Producer', level: 'senior' },
          { code: '2504', title: 'Sports Broadcaster', level: 'senior', alternateNames: ['Play-by-Play Announcer'] },
          { code: '2505', title: 'Color Commentator', level: 'senior' },
          { code: '2506', title: 'Sideline Reporter', level: 'mid' },
          { code: '2507', title: 'Sports Journalist', level: 'mid' },
          { code: '2508', title: 'Content Creator', level: 'mid' },
          { code: '2509', title: 'Podcast Producer', level: 'mid' },
          { code: '2510', title: 'Social Media Producer', level: 'mid' },
          { code: '2511', title: 'Media Coordinator', level: 'mid' },
        ],
      },
      {
        code: '2600',
        name: 'Sports Marketing',
        description: 'Sports-specific marketing and fan engagement',
        positions: [
          { code: '2601', title: 'Sports Marketing Director', level: 'director' },
          { code: '2602', title: 'Fan Engagement Manager', level: 'manager' },
          { code: '2603', title: 'Game Day Marketing Manager', level: 'manager' },
          { code: '2604', title: 'Promotions Manager', level: 'manager' },
          { code: '2605', title: 'Promotions Coordinator', level: 'mid' },
          { code: '2606', title: 'Street Team Coordinator', level: 'mid' },
          { code: '2607', title: 'Brand Ambassador Coordinator', level: 'mid' },
          { code: '2608', title: 'Mascot Coordinator', level: 'mid' },
        ],
      },
      {
        code: '2700',
        name: 'Event Marketing',
        description: 'Event-specific marketing and promotions',
        positions: [
          { code: '2701', title: 'Event Marketing Director', level: 'director' },
          { code: '2702', title: 'Event Marketing Manager', level: 'manager' },
          { code: '2703', title: 'Event Promoter', level: 'senior' },
          { code: '2704', title: 'Grassroots Marketing Manager', level: 'manager' },
          { code: '2705', title: 'Experiential Marketing Manager', level: 'manager' },
          { code: '2706', title: 'Field Marketing Manager', level: 'manager' },
          { code: '2707', title: 'Guerrilla Marketing Specialist', level: 'mid' },
        ],
      },
      {
        code: '2800',
        name: 'Creative Services',
        description: 'In-house creative and design services',
        positions: [
          { code: '2801', title: 'Creative Services Director', level: 'director' },
          { code: '2802', title: 'Studio Manager', level: 'manager' },
          { code: '2803', title: 'Print Production Manager', level: 'manager' },
          { code: '2804', title: 'Prepress Technician', level: 'mid' },
          { code: '2805', title: 'Print Coordinator', level: 'mid' },
          { code: '2806', title: 'Traffic Manager', level: 'mid' },
        ],
      },
    ],
  },
  {
    code: '3000',
    name: 'Talent',
    description: 'Artist relations, booking, casting, and talent management',
    teams: [
      {
        code: '3100',
        name: 'Talent Buying & Booking',
        positions: [
          { code: '3101', title: 'Talent Director', level: 'director' },
          { code: '3102', title: 'Talent Buyer', level: 'senior' },
          { code: '3103', title: 'Booking Agent', level: 'mid' },
          { code: '3104', title: 'Talent Coordinator', level: 'mid' },
          { code: '3105', title: 'Booking Manager', level: 'manager' },
        ],
      },
      {
        code: '3200',
        name: 'Artist Relations',
        positions: [
          { code: '3201', title: 'Artist Relations Director', level: 'director' },
          { code: '3202', title: 'Artist Relations Manager', level: 'manager' },
          { code: '3203', title: 'Artist Liaison', level: 'mid' },
          { code: '3204', title: 'Tour Manager', level: 'senior' },
          { code: '3205', title: 'Artist Coordinator', level: 'mid' },
        ],
      },
      {
        code: '3300',
        name: 'Casting',
        description: 'Casting for film, TV, theater, and commercials',
        positions: [
          { code: '3301', title: 'Casting Director', level: 'director' },
          { code: '3302', title: 'Casting Associate', level: 'senior' },
          { code: '3303', title: 'Casting Assistant', level: 'mid' },
          { code: '3304', title: 'Extras Casting Director', level: 'manager' },
          { code: '3305', title: 'Talent Agent', level: 'senior' },
          { code: '3306', title: 'Talent Manager', level: 'manager' },
        ],
      },
      {
        code: '3400',
        name: 'Talent Management',
        description: 'Artist and talent representation and management',
        positions: [
          { code: '3401', title: 'Talent Management Director', level: 'director' },
          { code: '3402', title: 'Artist Manager', level: 'manager' },
          { code: '3403', title: 'Personal Manager', level: 'senior' },
          { code: '3404', title: 'Business Manager', level: 'senior' },
          { code: '3405', title: 'Publicist', level: 'senior' },
          { code: '3406', title: 'Brand Manager', level: 'manager' },
          { code: '3407', title: 'Career Advisor', level: 'senior' },
          { code: '3408', title: 'Talent Scout', level: 'mid' },
          { code: '3409', title: 'A&R Representative', level: 'senior', alternateNames: ['Artists & Repertoire'] },
          { code: '3410', title: 'Talent Development Manager', level: 'manager' },
        ],
      },
      {
        code: '3500',
        name: 'Entertainment Contracts',
        description: 'Contract negotiation and deal-making',
        positions: [
          { code: '3501', title: 'Entertainment Attorney', level: 'senior' },
          { code: '3502', title: 'Contracts Manager', level: 'manager' },
          { code: '3503', title: 'Deal Maker', level: 'senior' },
          { code: '3504', title: 'Licensing Manager', level: 'manager' },
          { code: '3505', title: 'Rights Manager', level: 'manager' },
          { code: '3506', title: 'Royalty Manager', level: 'senior' },
        ],
      },
    ],
  },
  {
    code: '4000',
    name: 'Production',
    description: 'Event, film, TV, broadcast, and theatrical production',
    teams: [
      {
        code: '4100',
        name: 'Production Management',
        positions: [
          { code: '4101', title: 'Production Director', level: 'director' },
          { code: '4102', title: 'Production Manager', level: 'manager' },
          { code: '4103', title: 'Assistant Production Manager', level: 'senior' },
          { code: '4104', title: 'Production Coordinator', level: 'mid' },
          { code: '4105', title: 'Production Assistant', level: 'entry' },
          { code: '4106', title: 'Production Supervisor', level: 'lead' },
        ],
      },
      {
        code: '4200',
        name: 'Stage Management',
        positions: [
          { code: '4201', title: 'Stage Manager', level: 'manager' },
          { code: '4202', title: 'Assistant Stage Manager', level: 'senior', alternateNames: ['ASM'] },
          { code: '4203', title: 'Stage Hand', level: 'entry' },
          { code: '4204', title: 'Deck Chief', level: 'lead' },
          { code: '4205', title: 'Fly Operator', level: 'mid' },
          { code: '4206', title: 'Prop Master', level: 'lead' },
          { code: '4207', title: 'Props Assistant', level: 'mid' },
        ],
      },
      {
        code: '4300',
        name: 'Audio & Sound',
        positions: [
          { code: '4301', title: 'Audio Director', level: 'director' },
          { code: '4302', title: 'Front of House Engineer', level: 'senior', alternateNames: ['FOH Engineer'] },
          { code: '4303', title: 'Monitor Engineer', level: 'senior' },
          { code: '4304', title: 'System Engineer', level: 'senior' },
          { code: '4305', title: 'Audio Technician', level: 'mid', alternateNames: ['A1', 'A2'] },
          { code: '4306', title: 'RF Technician', level: 'mid' },
          { code: '4307', title: 'Sound Designer', level: 'senior' },
          { code: '4308', title: 'Production Sound Mixer', level: 'senior' },
          { code: '4309', title: 'Boom Operator', level: 'mid' },
          { code: '4310', title: 'Sound Effects Editor', level: 'mid' },
          { code: '4311', title: 'Re-Recording Mixer', level: 'senior' },
          { code: '4312', title: 'Foley Artist', level: 'mid' },
          { code: '4313', title: 'Music Supervisor', level: 'senior' },
          { code: '4314', title: 'Dialogue Editor', level: 'mid' },
          { code: '4315', title: 'ADR Mixer', level: 'senior' },
        ],
      },
      {
        code: '4400',
        name: 'Lighting & Electrics',
        positions: [
          { code: '4401', title: 'Lighting Director', level: 'director', alternateNames: ['LD'] },
          { code: '4402', title: 'Lighting Designer', level: 'senior' },
          { code: '4403', title: 'Lighting Programmer', level: 'senior' },
          { code: '4404', title: 'Lighting Technician', level: 'mid' },
          { code: '4405', title: 'Followspot Operator', level: 'entry' },
          { code: '4406', title: 'Gaffer', level: 'lead' },
          { code: '4407', title: 'Best Boy Electric', level: 'senior' },
          { code: '4408', title: 'Electrician', level: 'mid' },
          { code: '4409', title: 'Lighting Board Operator', level: 'mid' },
          { code: '4410', title: 'Master Electrician', level: 'lead' },
          { code: '4411', title: 'Dimmer Board Operator', level: 'mid' },
        ],
      },
      {
        code: '4500',
        name: 'Video & Camera',
        positions: [
          { code: '4501', title: 'Video Director', level: 'director' },
          { code: '4502', title: 'Video Engineer', level: 'senior' },
          { code: '4503', title: 'LED Technician', level: 'mid' },
          { code: '4504', title: 'Camera Operator', level: 'mid' },
          { code: '4505', title: 'Projectionist', level: 'mid' },
          { code: '4506', title: 'Director of Photography', level: 'director', alternateNames: ['DP', 'DOP', 'Cinematographer'] },
          { code: '4507', title: 'First Assistant Camera', level: 'senior', alternateNames: ['1st AC', 'Focus Puller'] },
          { code: '4508', title: 'Second Assistant Camera', level: 'mid', alternateNames: ['2nd AC', 'Clapper Loader'] },
          { code: '4509', title: 'Digital Imaging Technician', level: 'senior', alternateNames: ['DIT'] },
          { code: '4510', title: 'Steadicam Operator', level: 'senior' },
          { code: '4511', title: 'Drone Operator', level: 'mid', requiredCertifications: ['Part 107'] },
          { code: '4512', title: 'Video Playback Operator', level: 'mid' },
          { code: '4513', title: 'Video Utility', level: 'entry' },
        ],
      },
      {
        code: '4600',
        name: 'Rigging & Grip',
        positions: [
          { code: '4601', title: 'Head Rigger', level: 'lead', requiredCertifications: ['ETCP Rigging'] },
          { code: '4602', title: 'Rigger', level: 'mid', requiredCertifications: ['ETCP Rigging'] },
          { code: '4603', title: 'Ground Rigger', level: 'entry' },
          { code: '4604', title: 'Key Grip', level: 'lead' },
          { code: '4605', title: 'Best Boy Grip', level: 'senior' },
          { code: '4606', title: 'Dolly Grip', level: 'mid' },
          { code: '4607', title: 'Grip', level: 'entry' },
          { code: '4608', title: 'Swing Gang', level: 'entry' },
        ],
      },
      {
        code: '4700',
        name: 'Broadcast Operations',
        description: 'TV broadcast and live streaming',
        positions: [
          { code: '4701', title: 'Broadcast Director', level: 'director' },
          { code: '4702', title: 'Technical Director', level: 'director', alternateNames: ['TD'] },
          { code: '4703', title: 'Broadcast Engineer', level: 'senior' },
          { code: '4704', title: 'Master Control Operator', level: 'mid' },
          { code: '4705', title: 'Transmission Engineer', level: 'senior' },
          { code: '4706', title: 'Graphics Operator', level: 'mid' },
          { code: '4707', title: 'Replay Operator', level: 'mid' },
          { code: '4708', title: 'EVS Operator', level: 'mid' },
          { code: '4709', title: 'Prompter Operator', level: 'entry' },
          { code: '4710', title: 'Broadcast Producer', level: 'senior' },
          { code: '4711', title: 'Broadcast Coordinator', level: 'mid' },
          { code: '4712', title: 'Satellite Truck Operator', level: 'senior' },
        ],
      },
      {
        code: '4800',
        name: 'Post-Production',
        description: 'Editing and post-production',
        positions: [
          { code: '4801', title: 'Post-Production Supervisor', level: 'manager' },
          { code: '4802', title: 'Editor', level: 'senior' },
          { code: '4803', title: 'Assistant Editor', level: 'mid' },
          { code: '4804', title: 'VFX Supervisor', level: 'director' },
          { code: '4805', title: 'VFX Producer', level: 'senior' },
          { code: '4806', title: 'Compositor', level: 'mid' },
          { code: '4807', title: 'Rotoscope Artist', level: 'entry' },
          { code: '4808', title: 'Color Grader', level: 'senior', alternateNames: ['Colorist'] },
          { code: '4809', title: 'Online Editor', level: 'senior' },
          { code: '4810', title: 'Offline Editor', level: 'mid' },
          { code: '4811', title: 'Conform Artist', level: 'mid' },
          { code: '4812', title: 'Finishing Editor', level: 'senior' },
          { code: '4813', title: 'Motion Graphics Artist', level: 'mid' },
          { code: '4814', title: '3D Artist', level: 'mid' },
          { code: '4815', title: 'Matte Painter', level: 'senior' },
          { code: '4816', title: 'Tracking Artist', level: 'mid' },
        ],
      },
    ],
  },
  {
    code: '5000',
    name: 'Operations',
    description: 'Site operations, logistics, security, and infrastructure',
    teams: [
      {
        code: '5100',
        name: 'Site Operations',
        positions: [
          { code: '5101', title: 'Site Director', level: 'director' },
          { code: '5102', title: 'Site Manager', level: 'manager' },
          { code: '5103', title: 'Site Coordinator', level: 'mid' },
          { code: '5104', title: 'Site Supervisor', level: 'lead' },
          { code: '5105', title: 'Operations Manager', level: 'manager' },
        ],
      },
      {
        code: '5200',
        name: 'Logistics & Supply Chain',
        positions: [
          { code: '5201', title: 'Logistics Director', level: 'director' },
          { code: '5202', title: 'Logistics Manager', level: 'manager' },
          { code: '5203', title: 'Logistics Coordinator', level: 'mid' },
          { code: '5204', title: 'Warehouse Manager', level: 'manager' },
          { code: '5205', title: 'Freight Coordinator', level: 'mid' },
          { code: '5206', title: 'Inventory Manager', level: 'manager' },
          { code: '5207', title: 'Supply Chain Coordinator', level: 'mid' },
          { code: '5208', title: 'Shipping & Receiving Clerk', level: 'entry' },
        ],
      },
      {
        code: '5300',
        name: 'Transportation',
        positions: [
          { code: '5301', title: 'Transportation Manager', level: 'manager' },
          { code: '5302', title: 'Transportation Coordinator', level: 'mid' },
          { code: '5303', title: 'Driver', level: 'entry', requiredCertifications: ['CDL'] },
          { code: '5304', title: 'Shuttle Coordinator', level: 'mid' },
          { code: '5305', title: 'Transportation Captain', level: 'lead' },
          { code: '5306', title: 'Fleet Manager', level: 'manager' },
        ],
      },
      {
        code: '5400',
        name: 'Facilities & Maintenance',
        positions: [
          { code: '5401', title: 'Facilities Manager', level: 'manager' },
          { code: '5402', title: 'Facilities Coordinator', level: 'mid' },
          { code: '5403', title: 'Maintenance Technician', level: 'mid' },
          { code: '5404', title: 'Electrician', level: 'mid', requiredCertifications: ['Licensed Electrician'] },
          { code: '5405', title: 'Plumber', level: 'mid', requiredCertifications: ['Licensed Plumber'] },
          { code: '5406', title: 'HVAC Technician', level: 'mid' },
          { code: '5407', title: 'Carpenter', level: 'mid' },
          { code: '5408', title: 'Painter', level: 'entry' },
        ],
      },
      {
        code: '5600',
        name: 'Construction & Build',
        description: 'Construction, build-out, and structural work',
        positions: [
          { code: '5601', title: 'Construction Manager', level: 'manager' },
          { code: '5602', title: 'General Contractor', level: 'senior' },
          { code: '5603', title: 'Site Superintendent', level: 'lead' },
          { code: '5604', title: 'Project Engineer', level: 'senior' },
          { code: '5605', title: 'Structural Engineer', level: 'senior', requiredCertifications: ['PE License'] },
          { code: '5606', title: 'Civil Engineer', level: 'senior', requiredCertifications: ['PE License'] },
          { code: '5607', title: 'Foreman', level: 'lead' },
          { code: '5608', title: 'Master Carpenter', level: 'lead' },
          { code: '5609', title: 'Framer', level: 'mid' },
          { code: '5610', title: 'Welder', level: 'mid', requiredCertifications: ['Welding Certification'] },
          { code: '5611', title: 'Heavy Equipment Operator', level: 'mid', requiredCertifications: ['Equipment Certification'] },
          { code: '5612', title: 'Concrete Finisher', level: 'mid' },
          { code: '5613', title: 'Mason', level: 'mid' },
          { code: '5614', title: 'Roofer', level: 'mid' },
          { code: '5615', title: 'Drywall Installer', level: 'mid' },
          { code: '5616', title: 'Laborer', level: 'entry' },
        ],
      },
      {
        code: '5500',
        name: 'Security & Safety',
        description: 'Security, safety, and emergency services',
        positions: [
          { code: '5501', title: 'Security Director', level: 'director' },
          { code: '5502', title: 'Security Manager', level: 'manager' },
          { code: '5503', title: 'Security Supervisor', level: 'lead' },
          { code: '5504', title: 'Security Officer', level: 'entry' },
          { code: '5505', title: 'Safety Manager', level: 'manager' },
          { code: '5506', title: 'Safety Coordinator', level: 'mid' },
          { code: '5507', title: 'Fire Safety Officer', level: 'mid' },
          { code: '5508', title: 'Stunt Coordinator', level: 'senior' },
          { code: '5509', title: 'Safety Officer', level: 'mid' },
          { code: '5510', title: 'EMT/Paramedic', level: 'mid', requiredCertifications: ['EMT', 'Paramedic'] },
          { code: '5511', title: 'Fire Marshal', level: 'senior', requiredCertifications: ['Fire Marshal Certification'] },
          { code: '5512', title: 'Emergency Response Coordinator', level: 'senior' },
          { code: '5513', title: 'Crowd Control Specialist', level: 'mid' },
          { code: '5514', title: 'K9 Handler', level: 'mid', requiredCertifications: ['K9 Certification'] },
        ],
      },
      {
        code: '5700',
        name: 'Environmental Services',
        description: 'Waste management, recycling, and environmental services',
        positions: [
          { code: '5701', title: 'Environmental Services Director', level: 'director' },
          { code: '5702', title: 'Sustainability Manager', level: 'manager' },
          { code: '5703', title: 'Waste Management Coordinator', level: 'mid' },
          { code: '5704', title: 'Recycling Coordinator', level: 'mid' },
          { code: '5705', title: 'Composting Specialist', level: 'mid' },
          { code: '5706', title: 'Environmental Compliance Officer', level: 'senior' },
          { code: '5707', title: 'Custodian', level: 'entry' },
          { code: '5708', title: 'Janitorial Supervisor', level: 'lead' },
        ],
      },
      {
        code: '5800',
        name: 'Event Services',
        description: 'Event setup, teardown, and general services',
        positions: [
          { code: '5801', title: 'Event Services Manager', level: 'manager' },
          { code: '5802', title: 'Event Setup Supervisor', level: 'lead' },
          { code: '5803', title: 'Event Crew Chief', level: 'lead' },
          { code: '5804', title: 'Event Technician', level: 'mid' },
          { code: '5805', title: 'Load-In/Load-Out Coordinator', level: 'mid' },
          { code: '5806', title: 'Event Porter', level: 'entry' },
          { code: '5807', title: 'Runner', level: 'entry' },
        ],
      },
    ],
  },
  {
    code: '6000',
    name: 'Experience',
    description: 'Guest services, accessibility, and customer experience',
    teams: [
      {
        code: '6100',
        name: 'Guest Experience',
        positions: [
          { code: '6101', title: 'Guest Experience Director', level: 'director' },
          { code: '6102', title: 'Guest Services Manager', level: 'manager' },
          { code: '6103', title: 'Guest Services Supervisor', level: 'lead' },
          { code: '6104', title: 'Guest Services Representative', level: 'entry' },
          { code: '6105', title: 'Concierge', level: 'mid' },
          { code: '6106', title: 'Usher', level: 'entry' },
          { code: '6107', title: 'House Manager', level: 'manager' },
        ],
      },
      {
        code: '6200',
        name: 'Accessibility Services',
        positions: [
          { code: '6201', title: 'Accessibility Director', level: 'director' },
          { code: '6202', title: 'Accessibility Manager', level: 'manager' },
          { code: '6203', title: 'Accessibility Coordinator', level: 'mid' },
          { code: '6204', title: 'ADA Compliance Specialist', level: 'senior' },
          { code: '6205', title: 'Sign Language Interpreter', level: 'mid' },
          { code: '6206', title: 'Captioning Specialist', level: 'mid' },
        ],
      },
      {
        code: '6300',
        name: 'Ticketing & Box Office',
        positions: [
          { code: '6301', title: 'Box Office Manager', level: 'manager' },
          { code: '6302', title: 'Box Office Supervisor', level: 'lead' },
          { code: '6303', title: 'Box Office Agent', level: 'entry' },
          { code: '6304', title: 'Will Call Coordinator', level: 'mid' },
          { code: '6305', title: 'Ticket Taker', level: 'entry' },
        ],
      },
      {
        code: '6400',
        name: 'Health & Wellness',
        description: 'Medical, health, and wellness services',
        positions: [
          { code: '6401', title: 'Medical Director', level: 'director', requiredCertifications: ['MD', 'DO'] },
          { code: '6402', title: 'Nurse Manager', level: 'manager', requiredCertifications: ['RN License'] },
          { code: '6403', title: 'Registered Nurse', level: 'senior', alternateNames: ['RN'], requiredCertifications: ['RN License'] },
          { code: '6404', title: 'Licensed Practical Nurse', level: 'mid', alternateNames: ['LPN'], requiredCertifications: ['LPN License'] },
          { code: '6405', title: 'Paramedic', level: 'senior', requiredCertifications: ['Paramedic Certification'] },
          { code: '6406', title: 'EMT', level: 'mid', requiredCertifications: ['EMT Certification'] },
          { code: '6407', title: 'First Aid Attendant', level: 'entry', requiredCertifications: ['First Aid/CPR'] },
          { code: '6408', title: 'Wellness Coordinator', level: 'mid' },
          { code: '6409', title: 'Mental Health Counselor', level: 'senior', requiredCertifications: ['Licensed Counselor'] },
          { code: '6410', title: 'Substance Abuse Counselor', level: 'senior', requiredCertifications: ['CASAC'] },
        ],
      },
      {
        code: '6500',
        name: 'Education & Training',
        description: 'Training, education, and development programs',
        positions: [
          { code: '6501', title: 'Training Director', level: 'director' },
          { code: '6502', title: 'Training Manager', level: 'manager' },
          { code: '6503', title: 'Training Coordinator', level: 'mid' },
          { code: '6504', title: 'Instructor', level: 'senior' },
          { code: '6505', title: 'Technical Trainer', level: 'senior' },
          { code: '6506', title: 'Safety Trainer', level: 'senior' },
          { code: '6507', title: 'Curriculum Developer', level: 'senior' },
          { code: '6508', title: 'Learning & Development Specialist', level: 'mid' },
          { code: '6509', title: 'Workshop Facilitator', level: 'mid' },
          { code: '6510', title: 'Educational Coordinator', level: 'mid' },
        ],
      },
    ],
  },
  {
    code: '7000',
    name: 'Hospitality',
    description: 'Food & beverage, catering, and VIP services',
    teams: [
      {
        code: '7100',
        name: 'Food & Beverage',
        positions: [
          { code: '7101', title: 'F&B Director', level: 'director' },
          { code: '7102', title: 'F&B Manager', level: 'manager' },
          { code: '7103', title: 'Catering Manager', level: 'manager' },
          { code: '7104', title: 'Executive Chef', level: 'senior' },
          { code: '7105', title: 'Sous Chef', level: 'mid' },
          { code: '7106', title: 'Line Cook', level: 'entry' },
          { code: '7107', title: 'Bartender', level: 'entry', requiredCertifications: ['TIPS', 'ServSafe'] },
          { code: '7108', title: 'Server', level: 'entry', requiredCertifications: ['Food Handler'] },
          { code: '7109', title: 'Barista', level: 'entry' },
          { code: '7110', title: 'Food Runner', level: 'entry' },
          { code: '7111', title: 'Craft Services', level: 'mid' },
        ],
      },
      {
        code: '7200',
        name: 'VIP Services',
        positions: [
          { code: '7201', title: 'VIP Services Director', level: 'director' },
          { code: '7202', title: 'VIP Services Manager', level: 'manager' },
          { code: '7203', title: 'VIP Host', level: 'mid' },
          { code: '7204', title: 'Hospitality Coordinator', level: 'mid' },
          { code: '7205', title: 'Green Room Coordinator', level: 'mid' },
          { code: '7206', title: 'Backstage Hospitality Manager', level: 'manager' },
          { code: '7207', title: 'Artist Hospitality Coordinator', level: 'mid' },
        ],
      },
      {
        code: '7300',
        name: 'Concessions & Retail',
        description: 'Concessions, merchandise, and retail operations',
        positions: [
          { code: '7301', title: 'Concessions Director', level: 'director' },
          { code: '7302', title: 'Concessions Manager', level: 'manager' },
          { code: '7303', title: 'Concessions Supervisor', level: 'lead' },
          { code: '7304', title: 'Concessions Worker', level: 'entry' },
          { code: '7305', title: 'Merchandise Manager', level: 'manager' },
          { code: '7306', title: 'Retail Supervisor', level: 'lead' },
          { code: '7307', title: 'Retail Associate', level: 'entry' },
          { code: '7308', title: 'Inventory Specialist', level: 'mid' },
          { code: '7309', title: 'POS Manager', level: 'manager', alternateNames: ['Point of Sale Manager'] },
        ],
      },
    ],
  },
  {
    code: '8000',
    name: 'Entertainment',
    description: 'Performers, talent, and entertainment programming',
    teams: [
      {
        code: '8100',
        name: 'Entertainment Programming',
        positions: [
          { code: '8101', title: 'Entertainment Director', level: 'director' },
          { code: '8102', title: 'Entertainment Manager', level: 'manager' },
          { code: '8103', title: 'Entertainment Coordinator', level: 'mid' },
          { code: '8104', title: 'Program Director', level: 'director' },
          { code: '8105', title: 'Creative Producer', level: 'senior' },
          { code: '8106', title: 'Experience Designer', level: 'senior' },
          { code: '8107', title: 'Activation Producer', level: 'mid' },
        ],
      },
      {
        code: '8150',
        name: 'Live Entertainment',
        description: 'Live performance and interactive entertainment',
        positions: [
          { code: '8151', title: 'Live Entertainment Director', level: 'director' },
          { code: '8152', title: 'Performance Director', level: 'director' },
          { code: '8153', title: 'Show Producer', level: 'senior' },
          { code: '8154', title: 'Show Caller', level: 'senior' },
          { code: '8155', title: 'Stage Combat Choreographer', level: 'senior' },
          { code: '8156', title: 'Aerial Choreographer', level: 'senior' },
          { code: '8157', title: 'Circus Performer', level: 'mid' },
          { code: '8158', title: 'Magician', level: 'mid' },
          { code: '8159', title: 'Comedian', level: 'mid' },
          { code: '8160', title: 'Street Performer', level: 'entry' },
          { code: '8161', title: 'Character Actor', level: 'mid' },
          { code: '8162', title: 'Improv Performer', level: 'mid' },
        ],
      },
      {
        code: '8170',
        name: 'Music & Audio Entertainment',
        description: 'Musicians, DJs, and audio entertainment',
        positions: [
          { code: '8171', title: 'Music Director', level: 'director' },
          { code: '8172', title: 'Musical Director', level: 'director' },
          { code: '8173', title: 'Conductor', level: 'director' },
          { code: '8174', title: 'Bandleader', level: 'senior' },
          { code: '8175', title: 'Musician', level: 'mid' },
          { code: '8176', title: 'Session Musician', level: 'senior' },
          { code: '8177', title: 'DJ', level: 'mid' },
          { code: '8178', title: 'Resident DJ', level: 'senior' },
          { code: '8179', title: 'Music Producer', level: 'senior' },
          { code: '8180', title: 'Composer', level: 'senior' },
          { code: '8181', title: 'Arranger', level: 'senior' },
          { code: '8182', title: 'Vocalist', level: 'mid' },
          { code: '8183', title: 'Background Vocalist', level: 'mid' },
        ],
      },
      {
        code: '8200',
        name: 'Performers & Talent',
        positions: [
          { code: '8201', title: 'Headliner', level: 'executive' },
          { code: '8202', title: 'Featured Artist', level: 'senior' },
          { code: '8203', title: 'Supporting Artist', level: 'mid' },
          { code: '8204', title: 'DJ', level: 'mid' },
          { code: '8205', title: 'MC/Host', level: 'mid' },
          { code: '8206', title: 'Dancer', level: 'mid' },
          { code: '8207', title: 'Choreographer', level: 'senior' },
          { code: '8208', title: 'Acrobat', level: 'mid' },
          { code: '8209', title: 'Actor', level: 'mid' },
          { code: '8210', title: 'Voice Actor', level: 'mid' },
          { code: '8211', title: 'Stand-In', level: 'entry' },
          { code: '8212', title: 'Photo Double', level: 'entry' },
          { code: '8213', title: 'Stunt Performer', level: 'senior' },
          { code: '8214', title: 'Extra/Background Actor', level: 'entry' },
        ],
      },
      {
        code: '8300',
        name: 'Sports Entertainment',
        description: 'Athletes, coaches, and sports entertainment talent',
        positions: [
          { code: '8301', title: 'Professional Athlete', level: 'senior' },
          { code: '8302', title: 'Head Coach', level: 'director' },
          { code: '8303', title: 'Assistant Coach', level: 'senior' },
          { code: '8304', title: 'Athletic Trainer', level: 'senior', requiredCertifications: ['Certified Athletic Trainer'] },
          { code: '8305', title: 'Strength & Conditioning Coach', level: 'senior' },
          { code: '8306', title: 'Sports Psychologist', level: 'senior' },
          { code: '8307', title: 'Team Physician', level: 'executive', requiredCertifications: ['MD', 'DO'] },
          { code: '8308', title: 'Physical Therapist', level: 'senior', requiredCertifications: ['PT License'] },
          { code: '8309', title: 'Equipment Manager', level: 'manager' },
          { code: '8310', title: 'Scout', level: 'senior' },
          { code: '8311', title: 'Referee/Official', level: 'mid', requiredCertifications: ['Sport-Specific Certification'] },
          { code: '8312', title: 'Umpire', level: 'mid', requiredCertifications: ['Sport-Specific Certification'] },
          { code: '8313', title: 'Mascot Performer', level: 'mid' },
          { code: '8314', title: 'Cheerleader', level: 'mid' },
          { code: '8315', title: 'Cheer Coach', level: 'senior' },
          { code: '8316', title: 'Dance Team Member', level: 'mid' },
          { code: '8317', title: 'Esports Player', level: 'mid' },
          { code: '8318', title: 'Esports Coach', level: 'senior' },
        ],
      },
      {
        code: '8400',
        name: 'Game Day Operations',
        description: 'Sports event and game day staff',
        positions: [
          { code: '8401', title: 'Game Day Operations Director', level: 'director' },
          { code: '8402', title: 'Game Day Manager', level: 'manager' },
          { code: '8403', title: 'Game Day Coordinator', level: 'mid' },
          { code: '8404', title: 'Stadium Announcer', level: 'mid', alternateNames: ['PA Announcer'] },
          { code: '8405', title: 'In-Game Host', level: 'mid' },
          { code: '8406', title: 'Hype Team Member', level: 'entry' },
          { code: '8407', title: 'Ball Person', level: 'entry' },
          { code: '8408', title: 'Bat Boy/Girl', level: 'entry' },
          { code: '8409', title: 'Ice Crew Member', level: 'entry' },
          { code: '8410', title: 'Field Crew Member', level: 'entry' },
        ],
      },
    ],
  },
  {
    code: '8500',
    name: 'Travel & Tourism',
    description: 'Travel coordination, tour management, and tourism services',
    teams: [
      {
        code: '8510',
        name: 'Travel Management',
        description: 'Travel planning and coordination',
        positions: [
          { code: '8511', title: 'Travel Director', level: 'director' },
          { code: '8512', title: 'Travel Manager', level: 'manager' },
          { code: '8513', title: 'Travel Coordinator', level: 'mid' },
          { code: '8514', title: 'Travel Agent', level: 'mid' },
          { code: '8515', title: 'Group Travel Specialist', level: 'senior' },
          { code: '8516', title: 'Corporate Travel Manager', level: 'manager' },
          { code: '8517', title: 'Travel Consultant', level: 'mid' },
        ],
      },
      {
        code: '8520',
        name: 'Tour Operations',
        description: 'Tour management and operations',
        positions: [
          { code: '8521', title: 'Tour Director', level: 'director' },
          { code: '8522', title: 'Tour Manager', level: 'manager' },
          { code: '8523', title: 'Tour Coordinator', level: 'mid' },
          { code: '8524', title: 'Tour Guide', level: 'mid' },
          { code: '8525', title: 'Tour Escort', level: 'entry' },
          { code: '8526', title: 'Road Manager', level: 'senior' },
          { code: '8527', title: 'Advance Person', level: 'mid' },
          { code: '8528', title: 'Tour Accountant', level: 'senior' },
        ],
      },
      {
        code: '8530',
        name: 'Accommodation Services',
        description: 'Hotel and lodging coordination',
        positions: [
          { code: '8531', title: 'Accommodation Manager', level: 'manager' },
          { code: '8532', title: 'Hotel Liaison', level: 'mid' },
          { code: '8533', title: 'Housing Coordinator', level: 'mid' },
          { code: '8534', title: 'Rooming Coordinator', level: 'mid' },
          { code: '8535', title: 'Venue Liaison', level: 'mid' },
        ],
      },
      {
        code: '8540',
        name: 'Ground Transportation',
        description: 'Ground transport and logistics',
        positions: [
          { code: '8541', title: 'Ground Transportation Manager', level: 'manager' },
          { code: '8542', title: 'Bus Captain', level: 'lead' },
          { code: '8543', title: 'Tour Bus Driver', level: 'mid', requiredCertifications: ['CDL'] },
          { code: '8544', title: 'Driver Coordinator', level: 'mid' },
          { code: '8545', title: 'Charter Coordinator', level: 'mid' },
        ],
      },
    ],
  },
  {
    code: '9000',
    name: 'Technology',
    description: 'IT, software development, and technical infrastructure',
    teams: [
      {
        code: '9100',
        name: 'Engineering',
        positions: [
          { code: '9101', title: 'VP of Engineering', level: 'executive' },
          { code: '9102', title: 'Engineering Manager', level: 'manager' },
          { code: '9103', title: 'Tech Lead', level: 'lead' },
          { code: '9104', title: 'Senior Software Engineer', level: 'senior' },
          { code: '9105', title: 'Software Engineer', level: 'mid' },
          { code: '9106', title: 'Junior Software Engineer', level: 'entry' },
          { code: '9107', title: 'DevOps Engineer', level: 'senior' },
          { code: '9108', title: 'QA Engineer', level: 'mid' },
        ],
      },
      {
        code: '9200',
        name: 'Product',
        positions: [
          { code: '9201', title: 'VP of Product', level: 'executive' },
          { code: '9202', title: 'Product Manager', level: 'manager' },
          { code: '9203', title: 'Product Owner', level: 'senior' },
          { code: '9204', title: 'Product Designer', level: 'mid' },
          { code: '9205', title: 'UX Researcher', level: 'mid' },
          { code: '9206', title: 'Product Analyst', level: 'mid' },
        ],
      },
      {
        code: '9300',
        name: 'IT Operations',
        positions: [
          { code: '9301', title: 'IT Director', level: 'director' },
          { code: '9302', title: 'IT Manager', level: 'manager' },
          { code: '9303', title: 'Systems Administrator', level: 'senior' },
          { code: '9304', title: 'Network Engineer', level: 'senior' },
          { code: '9305', title: 'IT Support Specialist', level: 'mid' },
          { code: '9306', title: 'Help Desk Technician', level: 'entry' },
          { code: '9307', title: 'Database Administrator', level: 'senior' },
        ],
      },
      {
        code: '9400',
        name: 'Data & Analytics',
        positions: [
          { code: '9401', title: 'Data Director', level: 'director' },
          { code: '9402', title: 'Data Engineer', level: 'senior' },
          { code: '9403', title: 'Data Analyst', level: 'mid' },
          { code: '9404', title: 'Business Intelligence Analyst', level: 'mid' },
          { code: '9405', title: 'Data Scientist', level: 'senior' },
          { code: '9406', title: 'Analytics Manager', level: 'manager' },
          { code: '9407', title: 'Reporting Analyst', level: 'mid' },
        ],
      },
      {
        code: '9500',
        name: 'Cybersecurity',
        description: 'Information security and cybersecurity',
        positions: [
          { code: '9501', title: 'Chief Information Security Officer', level: 'executive', alternateNames: ['CISO'] },
          { code: '9502', title: 'Security Director', level: 'director' },
          { code: '9503', title: 'Security Engineer', level: 'senior' },
          { code: '9504', title: 'Security Analyst', level: 'mid' },
          { code: '9505', title: 'Penetration Tester', level: 'senior' },
          { code: '9506', title: 'Security Operations Center Analyst', level: 'mid', alternateNames: ['SOC Analyst'] },
          { code: '9507', title: 'Compliance Manager', level: 'manager' },
        ],
      },
      {
        code: '9600',
        name: 'Infrastructure & Cloud',
        description: 'Cloud infrastructure and platform engineering',
        positions: [
          { code: '9601', title: 'Infrastructure Director', level: 'director' },
          { code: '9602', title: 'Cloud Architect', level: 'director' },
          { code: '9603', title: 'Site Reliability Engineer', level: 'senior', alternateNames: ['SRE'] },
          { code: '9604', title: 'Platform Engineer', level: 'senior' },
          { code: '9605', title: 'Cloud Engineer', level: 'mid' },
          { code: '9606', title: 'Infrastructure Engineer', level: 'senior' },
          { code: '9607', title: 'Release Engineer', level: 'senior' },
        ],
      },
    ],
  },
];
