-- =====================================================
-- ADD EVENT ROLES TO USER ROLE ENUM
-- Comprehensive event role system for all platforms
-- =====================================================

-- Add All Platforms Event Roles
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'EXECUTIVE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CORE_AAA';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AA';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PRODUCTION';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MANAGEMENT';

-- Add COMPVSS Event Roles
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CREW';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'STAFF';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'VENDOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ENTERTAINER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ARTIST';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AGENT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MEDIA';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SPONSOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PARTNER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'INDUSTRY';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'INTERN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'VOLUNTEER';

-- Add GVTEWAY Event Roles
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GUEST';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BACKSTAGE_L1';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BACKSTAGE_L2';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PLATINUM_VIP_L1';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PLATINUM_VIP_L2';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'VIP_L1';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'VIP_L2';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'VIP_L3';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GA_L1';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GA_L2';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GA_L3';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GA_L4';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GA_L5';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'INFLUENCER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BRAND_AMBASSADOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AFFILIATE';

-- =====================================================
-- COMMENTS
-- =====================================================

COMMENT ON TYPE "UserRole" IS 'User roles including platform roles, Legend roles, and event-specific roles with programmable access levels';
