#!/bin/bash
# Migration tracking script
echo "COMPVSS Advancing Pages Migration Progress"
echo "==========================================="
echo ""
echo "✅ Completed (9/22):"
echo "  - new/page.tsx"
echo "  - access/page.tsx"
echo "  - accommodation/page.tsx"
echo "  - hospitality/page.tsx"
echo "  - marketing/page.tsx"
echo "  - other/page.tsx"
echo ""
echo "🔄 In Progress (6/22):"
echo "  - permits/page.tsx"
echo "  - security/page.tsx"
echo "  - staffing/page.tsx"
echo "  - technical/page.tsx"
echo "  - transportation/page.tsx"
echo "  - travel/page.tsx"
echo ""
echo "❌ Remaining (7/22):"
echo "  - dashboard/page.tsx"
echo "  - heavy-equipment/page.tsx"
echo "  - site-assets/page.tsx"
echo "  - site-infrastructure/page.tsx"
echo "  - site-safety/page.tsx"
echo "  - site-utilities/page.tsx"
echo "  - site-vehicles/page.tsx"
echo ""
echo "Progress: 41% (9/22 complete)"
