-- ============================================================================
-- CATALOG ITEMS - TECHNICAL PRODUCTION (Comprehensive)
-- Audio, Lighting, Backline, Special FX, Production Comms
-- ============================================================================

BEGIN;

-- ============================================================================
-- TECHNICAL PRODUCTION - AUDIO
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, dimensions, weight, power_requirements,
  typical_quantity, estimated_cost,
  requires_certification, requires_insurance, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Line Array Speaker System',
  'line-array-speaker-system',
  'Professional line array PA system for large venues (per side)',
  'High-output line array system with integrated rigging, DSP processing, and amplification. Suitable for venues 500-5000 capacity.',
  'system',
  ARRAY['PA System', 'Sound System', 'Line Array PA', 'Main PA', 'FOH System'],
  ARRAY['speakers', 'pa', 'sound', 'audio', 'line array', 'main', 'foh', 'front of house'],
  ARRAY['audio', 'sound', 'large venue', 'main system', 'professional'],
  'L-Acoustics',
  'K2',
  '24" x 18" x 48" per cabinet',
  '165 lbs per cabinet',
  '208-240V 3-phase',
  2,
  '$2000-5000 per day',
  true,
  true,
  '2 weeks',
  ARRAY['Eighth Day Sound', 'Clair Global', 'Britannia Row'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Subwoofer (18" Powered)',
  'subwoofer-18-powered',
  'Powered 18-inch subwoofer for low-end reinforcement',
  'Self-powered dual 18" subwoofer with integrated DSP and rigging points. Frequency response 30Hz-120Hz.',
  'each',
  ARRAY['Sub', 'Bass Bin', 'Low End', '18-inch Sub', 'Powered Sub'],
  ARRAY['sub', 'subwoofer', 'bass', 'low end', '18', 'powered', 'lf'],
  ARRAY['audio', 'bass', 'subwoofer', 'low frequency'],
  'Meyer Sound',
  '1100-LFC',
  '28" x 42" x 36"',
  '245 lbs',
  '100-240V',
  4,
  '$150-300 per day',
  false,
  true,
  '1 week',
  ARRAY['Eighth Day Sound', 'PRG', 'Solotech'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Digital Mixing Console (32-channel)',
  'digital-mixing-console-32ch',
  '32-channel digital mixing console with effects and recording',
  'Professional digital console with 32 input channels, 16 mix buses, integrated effects, and multitrack recording capability.',
  'each',
  ARRAY['Sound Mixer', 'Mixing Board', 'Audio Console', 'Desk', 'Digital Desk'],
  ARRAY['mixer', 'console', 'soundboard', 'audio', 'digital', '32', 'channel', 'desk'],
  ARRAY['audio', 'mixing', 'console', 'digital', 'foh'],
  'DiGiCo',
  'SD12',
  '31" x 24" x 8"',
  '55 lbs',
  '100-240V',
  1,
  '$300-800 per day',
  true,
  true,
  '2 weeks',
  ARRAY['Eighth Day Sound', 'Clair Global', 'PRG'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Wireless Microphone System (Handheld)',
  'wireless-mic-handheld',
  'Professional wireless handheld microphone system',
  'UHF wireless system with handheld transmitter, receiver, and antenna distribution. Frequency-agile with 100+ channels.',
  'system',
  ARRAY['Wireless Mic', 'Radio Mic', 'Handheld Wireless', 'UHF Mic'],
  ARRAY['wireless', 'microphone', 'mic', 'handheld', 'uhf', 'radio'],
  ARRAY['audio', 'wireless', 'microphone', 'vocal'],
  'Shure',
  'ULXD2/SM58',
  'Handheld + rack receiver',
  '3 lbs',
  '100-240V',
  8,
  '$75-150 per day',
  false,
  true,
  '1 week',
  ARRAY['Local audio rental', 'PRG', 'Solotech'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Wireless In-Ear Monitor System',
  'wireless-iem-system',
  'Professional wireless in-ear monitor system',
  'Stereo wireless IEM system with bodypack receiver, earpieces, and rack transmitter.',
  'system',
  ARRAY['IEM', 'In-Ear', 'Wireless Monitor', 'Earpiece'],
  ARRAY['iem', 'in-ear', 'monitor', 'wireless', 'earpiece', 'bodypack'],
  ARRAY['audio', 'monitoring', 'wireless', 'iem'],
  'Shure',
  'PSM1000',
  'Bodypack + rack transmitter',
  '2 lbs',
  '100-240V',
  12,
  '$50-100 per day',
  false,
  true,
  '1 week',
  ARRAY['Local audio rental', 'PRG', 'Solotech'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Stage Monitor (Wedge)',
  'stage-monitor-wedge',
  'Powered stage monitor wedge speaker',
  '15" powered wedge monitor with 1000W amplification, 55° coverage angle.',
  'each',
  ARRAY['Wedge', 'Floor Monitor', 'Stage Monitor', 'Powered Wedge'],
  ARRAY['monitor', 'wedge', 'stage', 'floor', 'powered', '15'],
  ARRAY['audio', 'monitoring', 'stage', 'wedge'],
  'QSC',
  'K12.2',
  '23" x 14" x 13"',
  '37 lbs',
  '100-240V',
  10,
  '$40-80 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental', 'Guitar Center'],
  true,
  true,
  6
);

-- ============================================================================
-- TECHNICAL PRODUCTION - LIGHTING
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, dimensions, weight, power_requirements,
  typical_quantity, estimated_cost,
  requires_certification, requires_insurance, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'LED Moving Head (Spot)',
  'led-moving-head-spot',
  'LED moving head spot fixture with gobo and prism',
  '300W LED moving head spot with CMY color mixing, rotating gobos, prism, zoom 7-50°.',
  'each',
  ARRAY['Moving Light', 'Moving Head', 'Spot Light', 'LED Spot'],
  ARRAY['moving', 'head', 'spot', 'led', 'gobo', 'intelligent'],
  ARRAY['lighting', 'moving head', 'led', 'spot'],
  'Robe',
  'Robin Pointe',
  '15" x 15" x 22"',
  '42 lbs',
  '100-240V',
  24,
  '$75-150 per day',
  false,
  true,
  '2 weeks',
  ARRAY['4Wall Entertainment', 'PRG', 'Barbizon'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'LED Moving Head (Wash)',
  'led-moving-head-wash',
  'LED moving head wash fixture with color mixing',
  '400W RGBW LED moving head wash with zoom 7-60°, smooth color mixing.',
  'each',
  ARRAY['Moving Wash', 'LED Wash', 'Color Wash', 'Moving Head Wash'],
  ARRAY['moving', 'head', 'wash', 'led', 'rgbw', 'color', 'intelligent'],
  ARRAY['lighting', 'moving head', 'led', 'wash'],
  'Chauvet',
  'Rogue R2 Wash',
  '13" x 13" x 19"',
  '35 lbs',
  '100-240V',
  20,
  '$60-120 per day',
  false,
  true,
  '2 weeks',
  ARRAY['4Wall Entertainment', 'PRG', 'Barbizon'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'LED PAR Can (RGBWA)',
  'led-par-can-rgbwa',
  'LED PAR can with RGBWA color mixing',
  '150W RGBWA+UV LED PAR with DMX control, 25° beam angle.',
  'each',
  ARRAY['LED PAR', 'PAR Can', 'Color PAR', 'RGB PAR'],
  ARRAY['led', 'par', 'can', 'rgbwa', 'color', 'wash'],
  ARRAY['lighting', 'par', 'led', 'color'],
  'Chauvet',
  'COLORado 1 Solo',
  '10" x 10" x 12"',
  '12 lbs',
  '100-240V',
  50,
  '$15-30 per day',
  false,
  false,
  '3 days',
  ARRAY['Local lighting rental', '4Wall', 'Barbizon'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'Follow Spot (1200W)',
  'follow-spot-1200w',
  'Professional follow spot with iris and color',
  '1200W discharge follow spot with iris, color boomerang, and DMX control.',
  'each',
  ARRAY['Followspot', 'Spot Light', 'Follow', 'Spotlight'],
  ARRAY['follow', 'spot', 'followspot', 'spotlight', '1200', 'discharge'],
  ARRAY['lighting', 'follow spot', 'spotlight'],
  'Robert Juliat',
  'Super Korrigan',
  '36" x 18" x 24"',
  '85 lbs',
  '208V',
  2,
  '$150-300 per day',
  true,
  true,
  '2 weeks',
  ARRAY['4Wall Entertainment', 'PRG', 'Barbizon'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'LED Strip Light (1 meter)',
  'led-strip-light-1m',
  'RGB LED strip light for stage wash',
  '1-meter RGB LED batten with individual pixel control, DMX.',
  'each',
  ARRAY['LED Strip', 'LED Batten', 'Pixel Strip', 'RGB Strip'],
  ARRAY['led', 'strip', 'batten', 'rgb', 'pixel', 'wash'],
  ARRAY['lighting', 'led', 'strip', 'wash'],
  'Chauvet',
  'COLORstrip',
  '40" x 3" x 3"',
  '8 lbs',
  '100-240V',
  30,
  '$20-40 per day',
  false,
  false,
  '3 days',
  ARRAY['Local lighting rental', '4Wall'],
  true,
  true,
  5
);

-- ============================================================================
-- TECHNICAL PRODUCTION - BACKLINE
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Guitar Amplifier (100W)',
  'guitar-amp-100w',
  'Professional guitar amplifier head and cabinet',
  '100W tube guitar amp head with 4x12 speaker cabinet',
  'system',
  ARRAY['Guitar Amp', 'Amp Head', 'Guitar Stack'],
  ARRAY['guitar', 'amplifier', 'amp', '100w', 'tube', 'stack'],
  ARRAY['backline', 'guitar', 'amplifier'],
  'Marshall',
  'JCM800',
  3,
  '$75-150 per day',
  '1 week',
  ARRAY['Backline rental companies', 'Guitar Center'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Bass Amplifier (500W)',
  'bass-amp-500w',
  'Professional bass amplifier head and cabinet',
  '500W bass amp head with 4x10 or 1x15 speaker cabinet',
  'system',
  ARRAY['Bass Amp', 'Bass Head', 'Bass Stack'],
  ARRAY['bass', 'amplifier', 'amp', '500w', 'head', 'cabinet'],
  ARRAY['backline', 'bass', 'amplifier'],
  'Ampeg',
  'SVT-3 Pro',
  2,
  '$60-120 per day',
  '1 week',
  ARRAY['Backline rental companies', 'Guitar Center'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Drum Kit (5-piece)',
  'drum-kit-5-piece',
  'Professional 5-piece drum kit with hardware',
  'Complete drum kit: kick, snare, 3 toms, hi-hat, cymbals, hardware',
  'kit',
  ARRAY['Drums', 'Drum Set', 'Kit', 'Percussion'],
  ARRAY['drums', 'drum kit', 'percussion', '5-piece', 'kit'],
  ARRAY['backline', 'drums', 'percussion'],
  'DW',
  'Performance Series',
  1,
  '$100-200 per day',
  '1 week',
  ARRAY['Backline rental companies', 'Drum shops'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Keyboard (88-key)',
  'keyboard-88-key',
  'Professional 88-key weighted keyboard',
  'Full-size 88-key weighted action keyboard with stand',
  'each',
  ARRAY['Piano', 'Keyboard', 'Digital Piano', '88-key'],
  ARRAY['keyboard', 'piano', '88', 'keys', 'weighted', 'digital'],
  ARRAY['backline', 'keyboard', 'piano'],
  'Nord',
  'Stage 3',
  2,
  '$75-150 per day',
  '1 week',
  ARRAY['Backline rental companies', 'Music stores'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Keyboard Amplifier',
  'keyboard-amplifier',
  'Powered keyboard amplifier',
  '200W powered keyboard amp with multiple inputs',
  'each',
  ARRAY['Keyboard Amp', 'KB Amp', 'Powered Monitor'],
  ARRAY['keyboard', 'amplifier', 'amp', 'powered', 'monitor'],
  ARRAY['backline', 'keyboard', 'amplifier'],
  'Roland',
  'KC-550',
  3,
  '$40-80 per day',
  '3 days',
  ARRAY['Backline rental companies', 'Music stores'],
  true,
  true,
  5
);

-- ============================================================================
-- TECHNICAL PRODUCTION - SPECIAL FX
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  typical_quantity, estimated_cost, requires_certification, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'special-fx'),
  'Fog Machine (3000W)',
  'fog-machine-3000w',
  'High-output fog machine for atmospheric effects',
  '3000W fog machine with DMX control, 20,000 cu ft/min output',
  'each',
  ARRAY['Fogger', 'Smoke Machine', 'Hazer', 'Atmosphere'],
  ARRAY['fog', 'smoke', 'machine', 'fogger', 'atmosphere', 'haze'],
  ARRAY['special fx', 'fog', 'atmosphere'],
  10,
  '$50-100 per day',
  false,
  '3 days',
  ARRAY['Local lighting rental', '4Wall', 'FX rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'special-fx'),
  'Confetti Cannon (CO2)',
  'confetti-cannon-co2',
  'CO2-powered confetti cannon',
  'Single-shot CO2 confetti cannon, 30-50 ft range',
  'each',
  ARRAY['Confetti Blaster', 'CO2 Cannon', 'Streamer Cannon'],
  ARRAY['confetti', 'cannon', 'co2', 'blaster', 'streamer', 'fx'],
  ARRAY['special fx', 'confetti', 'pyro'],
  6,
  '$75-150 per day',
  true,
  '2 weeks',
  ARRAY['FX rental companies', 'Pyro companies'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'special-fx'),
  'Bubble Machine',
  'bubble-machine',
  'Professional bubble machine for effects',
  'High-output bubble machine with DMX control',
  'each',
  ARRAY['Bubbles', 'Bubble Blower', 'Bubble FX'],
  ARRAY['bubble', 'machine', 'bubbles', 'fx', 'effect'],
  ARRAY['special fx', 'bubbles', 'atmosphere'],
  4,
  '$30-60 per day',
  false,
  '3 days',
  ARRAY['Local rental', 'Party rental'],
  true,
  true,
  3
);

-- ============================================================================
-- TECHNICAL PRODUCTION - PRODUCTION COMMS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'production-comms'),
  'Clear-Com Wired Beltpack',
  'clearcom-wired-beltpack',
  'Wired intercom beltpack for production communication',
  'Single or dual-channel wired beltpack with headset',
  'each',
  ARRAY['Beltpack', 'Intercom', 'Clear-Com', 'Comms Pack'],
  ARRAY['clearcom', 'clear-com', 'beltpack', 'intercom', 'comms', 'wired'],
  ARRAY['comms', 'intercom', 'production'],
  'Clear-Com',
  'RS-702',
  12,
  '$25-50 per day',
  '1 week',
  ARRAY['PRG', 'VER', 'Production rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'production-comms'),
  'Wireless Intercom System',
  'wireless-intercom-system',
  'Wireless intercom base station and beltpacks',
  'Digital wireless intercom system with base station and beltpacks',
  'system',
  ARRAY['Wireless Comms', 'Radio Comms', 'Wireless Intercom'],
  ARRAY['wireless', 'intercom', 'comms', 'radio', 'digital'],
  ARRAY['comms', 'wireless', 'intercom'],
  'Clear-Com',
  'FreeSpeak II',
  1,
  '$200-400 per day',
  '2 weeks',
  ARRAY['PRG', 'VER', 'Production rental'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'production-comms'),
  'Two-Way Radio (UHF)',
  'two-way-radio-uhf',
  'Professional UHF two-way radio',
  'UHF handheld radio with earpiece, 16 channels',
  'each',
  ARRAY['Walkie-Talkie', 'Radio', 'Handheld Radio', 'Two-Way'],
  ARRAY['radio', 'walkie', 'talkie', 'uhf', 'two-way', 'handheld'],
  ARRAY['comms', 'radio', 'walkie-talkie'],
  'Motorola',
  'CP200d',
  20,
  '$15-30 per day',
  '3 days',
  ARRAY['Radio rental companies', 'Local rental'],
  true,
  true,
  3
);

COMMIT;
