-- ============================================================================
-- CATALOG ITEMS - HEAVY EQUIPMENT (Comprehensive)
-- Lifts, Forklifts, Generators, Rigging, Construction Equipment
-- ============================================================================

BEGIN;

-- ============================================================================
-- HEAVY EQUIPMENT - SCISSOR LIFTS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, dimensions, weight, capacity,
  typical_quantity, estimated_cost,
  requires_certification, requires_insurance, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scissor-lifts'),
  'Scissor Lift (19 ft)',
  'scissor-lift-19ft',
  '19-foot electric scissor lift',
  'Electric scissor lift, 19ft working height, 32" width, indoor/outdoor use',
  'each',
  ARRAY['Scissor Lift', 'Aerial Lift', 'Electric Lift', '19ft Lift'],
  ARRAY['scissor', 'lift', 'aerial', 'electric', '19', 'feet', 'platform'],
  ARRAY['heavy equipment', 'lift', 'aerial'],
  'Genie',
  'GS-1932',
  '32" x 70" x 79"',
  '2300 lbs',
  '500 lbs',
  4,
  '$100-200 per day',
  true,
  true,
  '1 week',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Herc Rentals'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scissor-lifts'),
  'Scissor Lift (26 ft)',
  'scissor-lift-26ft',
  '26-foot electric scissor lift',
  'Electric scissor lift, 26ft working height, 46" width, indoor/outdoor use',
  'each',
  ARRAY['Scissor Lift', 'Aerial Lift', 'Electric Lift', '26ft Lift'],
  ARRAY['scissor', 'lift', 'aerial', 'electric', '26', 'feet', 'platform'],
  ARRAY['heavy equipment', 'lift', 'aerial'],
  'Genie',
  'GS-2632',
  '46" x 96" x 95"',
  '3400 lbs',
  '500 lbs',
  3,
  '$150-250 per day',
  true,
  true,
  '1 week',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Herc Rentals'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scissor-lifts'),
  'Scissor Lift (32 ft)',
  'scissor-lift-32ft',
  '32-foot electric scissor lift',
  'Electric scissor lift, 32ft working height, 46" width, indoor/outdoor use',
  'each',
  ARRAY['Scissor Lift', 'Aerial Lift', 'Electric Lift', '32ft Lift'],
  ARRAY['scissor', 'lift', 'aerial', 'electric', '32', 'feet', 'platform'],
  ARRAY['heavy equipment', 'lift', 'aerial'],
  'Genie',
  'GS-3232',
  '46" x 96" x 102"',
  '4300 lbs',
  '500 lbs',
  2,
  '$200-350 per day',
  true,
  true,
  '1 week',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Herc Rentals'],
  true,
  true,
  3
);

-- ============================================================================
-- HEAVY EQUIPMENT - BOOM LIFTS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, dimensions, capacity,
  typical_quantity, estimated_cost,
  requires_certification, requires_insurance, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'boom-lifts'),
  'Boom Lift (45 ft Articulating)',
  'boom-lift-45ft-articulating',
  '45-foot articulating boom lift',
  'Diesel articulating boom lift, 45ft working height, 4WD, rough terrain',
  'each',
  ARRAY['Boom Lift', 'Articulating Lift', 'Knuckle Boom', '45ft Boom'],
  ARRAY['boom', 'lift', 'articulating', 'knuckle', '45', 'feet', 'aerial'],
  ARRAY['heavy equipment', 'lift', 'boom', 'aerial'],
  'JLG',
  '450AJ',
  '8ft x 20ft',
  '500 lbs',
  2,
  '$300-500 per day',
  true,
  true,
  '2 weeks',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Herc Rentals'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'boom-lifts'),
  'Boom Lift (60 ft Telescopic)',
  'boom-lift-60ft-telescopic',
  '60-foot telescopic boom lift',
  'Diesel telescopic boom lift, 60ft working height, 4WD, rough terrain',
  'each',
  ARRAY['Boom Lift', 'Telescopic Lift', 'Straight Boom', '60ft Boom'],
  ARRAY['boom', 'lift', 'telescopic', 'straight', '60', 'feet', 'aerial'],
  ARRAY['heavy equipment', 'lift', 'boom', 'aerial'],
  'Genie',
  'S-60',
  '8ft x 24ft',
  '500 lbs',
  1,
  '$400-700 per day',
  true,
  true,
  '2 weeks',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Herc Rentals'],
  true,
  true,
  2
);

-- ============================================================================
-- HEAVY EQUIPMENT - FORKLIFTS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, capacity,
  typical_quantity, estimated_cost,
  requires_certification, requires_insurance, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'forklifts'),
  'Forklift (5000 lb)',
  'forklift-5000lb',
  '5000-pound capacity forklift',
  'Propane or electric forklift, 5000 lb capacity, pneumatic tires',
  'each',
  ARRAY['Forklift', 'Lift Truck', 'Material Handler', '5K Forklift'],
  ARRAY['forklift', 'lift', 'truck', '5000', 'material', 'handler'],
  ARRAY['heavy equipment', 'forklift', 'material handling'],
  'Toyota',
  '8FGU25',
  '5000 lbs',
  2,
  '$200-350 per day',
  true,
  true,
  '1 week',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Forklift rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'forklifts'),
  'Forklift (8000 lb)',
  'forklift-8000lb',
  '8000-pound capacity forklift',
  'Propane or diesel forklift, 8000 lb capacity, pneumatic tires, rough terrain',
  'each',
  ARRAY['Forklift', 'Lift Truck', 'Material Handler', '8K Forklift'],
  ARRAY['forklift', 'lift', 'truck', '8000', 'material', 'handler', 'rough terrain'],
  ARRAY['heavy equipment', 'forklift', 'material handling'],
  'Hyster',
  'H80FT',
  '8000 lbs',
  1,
  '$300-500 per day',
  true,
  true,
  '1 week',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Forklift rental'],
  true,
  true,
  2
);

-- ============================================================================
-- HEAVY EQUIPMENT - GENERATORS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements, capacity,
  typical_quantity, estimated_cost,
  requires_certification, requires_insurance, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'generators'),
  'Generator (20kW)',
  'generator-20kw',
  '20-kilowatt diesel generator',
  'Diesel generator, 20kW continuous, 120/240V single-phase, sound-attenuated',
  'each',
  ARRAY['Generator', 'Genset', 'Power Generator', '20kW Gen'],
  ARRAY['generator', 'genset', 'power', '20', 'kw', 'diesel'],
  ARRAY['heavy equipment', 'generator', 'power'],
  'Caterpillar',
  'XQ20',
  'Diesel fuel',
  '20kW',
  3,
  '$150-300 per day',
  true,
  true,
  '1 week',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Generator rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'generators'),
  'Generator (60kW)',
  'generator-60kw',
  '60-kilowatt diesel generator',
  'Diesel generator, 60kW continuous, 120/208V 3-phase, sound-attenuated',
  'each',
  ARRAY['Generator', 'Genset', 'Power Generator', '60kW Gen'],
  ARRAY['generator', 'genset', 'power', '60', 'kw', 'diesel', '3-phase'],
  ARRAY['heavy equipment', 'generator', 'power'],
  'Caterpillar',
  'XQ60',
  'Diesel fuel',
  '60kW',
  2,
  '$300-600 per day',
  true,
  true,
  '2 weeks',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Generator rental'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'generators'),
  'Generator (100kW)',
  'generator-100kw',
  '100-kilowatt diesel generator',
  'Diesel generator, 100kW continuous, 120/208V 3-phase, sound-attenuated, trailer-mounted',
  'each',
  ARRAY['Generator', 'Genset', 'Power Generator', '100kW Gen'],
  ARRAY['generator', 'genset', 'power', '100', 'kw', 'diesel', '3-phase', 'trailer'],
  ARRAY['heavy equipment', 'generator', 'power'],
  'Caterpillar',
  'XQ100',
  'Diesel fuel',
  '100kW',
  1,
  '$400-700 per day',
  true,
  true,
  '2 weeks',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Generator rental'],
  true,
  true,
  3
);

-- ============================================================================
-- HEAVY EQUIPMENT - LIGHT TOWERS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'light-towers'),
  'Light Tower (4x1000W)',
  'light-tower-4x1000w',
  'Portable light tower with 4x1000W metal halide lamps',
  'Diesel-powered light tower, 30ft mast, 4x1000W MH lamps, 360° coverage',
  'each',
  ARRAY['Light Tower', 'Portable Lights', 'Site Lighting', 'Tower Lights'],
  ARRAY['light', 'tower', 'portable', 'site', 'lighting', '1000w', 'mast'],
  ARRAY['heavy equipment', 'lighting', 'site'],
  'Generac',
  'MLT4150',
  4,
  '$100-200 per day',
  '3 days',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Equipment rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'light-towers'),
  'Light Tower (LED)',
  'light-tower-led',
  'LED light tower with solar/battery power',
  'Solar/battery LED light tower, 20ft mast, 4x150W LED, eco-friendly',
  'each',
  ARRAY['LED Light Tower', 'Solar Light Tower', 'Battery Lights'],
  ARRAY['light', 'tower', 'led', 'solar', 'battery', 'eco', 'portable'],
  ARRAY['heavy equipment', 'lighting', 'site', 'sustainable'],
  'Allmand',
  'Night-Lite Pro',
  3,
  '$80-150 per day',
  '3 days',
  ARRAY['United Rentals', 'Sunbelt Rentals', 'Equipment rental'],
  true,
  true,
  2
);

-- ============================================================================
-- HEAVY EQUIPMENT - RIGGING EQUIPMENT
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, dimensions, weight, material, capacity,
  typical_quantity, estimated_cost,
  requires_certification, requires_insurance, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'rigging-equipment'),
  'Chain Hoist (1-ton)',
  'chain-hoist-1-ton',
  'Electric chain hoist, 1-ton capacity',
  'Single-speed electric chain hoist with hook, 20ft lift height',
  'each',
  ARRAY['Chain Motor', 'Hoist', 'Electric Hoist', 'Chain Hoist'],
  ARRAY['hoist', 'chain', 'motor', '1 ton', 'electric', 'rigging'],
  ARRAY['rigging', 'hoist', 'lifting'],
  'CM',
  'Lodestar',
  '12" x 18" x 24"',
  '85 lbs',
  'Steel',
  '1 ton (2000 lbs)',
  10,
  '$75-150 per day',
  true,
  true,
  '2 weeks',
  ARRAY['Rigging companies', 'Production equipment rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'rigging-equipment'),
  'Chain Hoist (2-ton)',
  'chain-hoist-2-ton',
  'Electric chain hoist, 2-ton capacity',
  'Single-speed electric chain hoist with hook, 20ft lift height',
  'each',
  ARRAY['Chain Motor', 'Hoist', 'Electric Hoist', '2-ton Hoist'],
  ARRAY['hoist', 'chain', 'motor', '2 ton', 'electric', 'rigging'],
  ARRAY['rigging', 'hoist', 'lifting'],
  'CM',
  'Lodestar',
  '14" x 20" x 26"',
  '120 lbs',
  'Steel',
  '2 tons (4000 lbs)',
  6,
  '$100-200 per day',
  true,
  true,
  '2 weeks',
  ARRAY['Rigging companies', 'Production equipment rental'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'rigging-equipment'),
  'Truss Section (10 ft)',
  'truss-section-10ft',
  '10-foot aluminum box truss',
  '12" x 12" aluminum box truss, bolt-together connections',
  'section',
  ARRAY['Truss', 'Box Truss', 'Aluminum Truss'],
  ARRAY['truss', 'aluminum', 'box', '10', 'feet', 'rigging'],
  ARRAY['rigging', 'truss', 'structure'],
  'Thomas',
  'Supertruss',
  '10 ft x 12" x 12"',
  '35 lbs',
  'Aluminum',
  '1000 lbs (distributed)',
  40,
  '$15-30 per day',
  false,
  false,
  '1 week',
  ARRAY['Staging companies', 'Lighting rental', 'Production rental'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'rigging-equipment'),
  'Shackle (1-ton)',
  'shackle-1-ton',
  'Screw-pin anchor shackle, 1-ton',
  'Galvanized steel screw-pin shackle, 1-ton working load limit',
  'each',
  ARRAY['Shackle', 'Rigging Shackle', 'Anchor Shackle'],
  ARRAY['shackle', 'rigging', '1 ton', 'anchor', 'hardware'],
  ARRAY['rigging', 'hardware', 'shackle'],
  'Crosby',
  'G-209',
  '3" x 2"',
  '1.5 lbs',
  'Galvanized steel',
  '1 ton WLL',
  50,
  '$3-8 per day',
  false,
  false,
  '3 days',
  ARRAY['Rigging suppliers', 'Hardware stores'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'rigging-equipment'),
  'Spanset (1-ton, 6 ft)',
  'spanset-1-ton-6ft',
  'Round sling, 1-ton capacity',
  'Polyester round sling, purple (1-ton), 6-foot length',
  'each',
  ARRAY['Round Sling', 'Spanset', 'Sling', 'Rigging Sling'],
  ARRAY['spanset', 'sling', 'round', '1 ton', 'rigging', 'purple'],
  ARRAY['rigging', 'sling', 'lifting'],
  'Lift-All',
  'EN90',
  '6 ft length',
  '2 lbs',
  'Polyester',
  '1 ton WLL',
  30,
  '$5-12 per day',
  false,
  false,
  '3 days',
  ARRAY['Rigging suppliers', 'Production rental'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'heavy-equipment'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'rigging-equipment'),
  'Ground Support Tower (12 ft)',
  'ground-support-tower-12ft',
  '12-foot ground support tower',
  'Aluminum crank-up tower with base plate, 12ft height, 500lb capacity',
  'each',
  ARRAY['Tower', 'Crank Stand', 'Ground Support', 'Truss Tower'],
  ARRAY['tower', 'ground support', 'crank', 'stand', '12', 'feet'],
  ARRAY['rigging', 'support', 'tower'],
  'Global Truss',
  'ST-180',
  '12 ft height',
  '120 lbs',
  'Aluminum',
  '500 lbs',
  8,
  '$40-80 per day',
  false,
  false,
  '1 week',
  ARRAY['Lighting rental', 'Production rental', 'Staging companies'],
  true,
  true,
  6
);

COMMIT;
