-- ============================================================================
-- CATALOG EXPANSION - AUDIO (Comprehensive)
-- Expanding audio category with full professional inventory
-- ============================================================================

BEGIN;

-- ============================================================================
-- TECHNICAL PRODUCTION - AUDIO (Additional Items)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, dimensions, weight, power_requirements,
  typical_quantity, estimated_cost,
  requires_certification, requires_insurance, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
-- Microphones
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Dynamic Microphone (SM58)',
  'dynamic-mic-sm58',
  'Industry-standard dynamic vocal microphone',
  'Cardioid dynamic microphone, frequency response 50Hz-15kHz, rugged construction.',
  'each',
  ARRAY['SM58', 'Vocal Mic', 'Dynamic Mic', 'Shure 58'],
  ARRAY['microphone', 'mic', 'sm58', 'dynamic', 'vocal', 'shure'],
  ARRAY['audio', 'microphone', 'vocal'],
  'Shure',
  'SM58',
  '6.5" length',
  '0.66 lbs',
  NULL,
  20,
  '$10-25 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental', 'Guitar Center'],
  true,
  true,
  7
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Condenser Microphone (Large Diaphragm)',
  'condenser-mic-large-diaphragm',
  'Large diaphragm condenser microphone for studio quality',
  'Cardioid condenser mic, 20Hz-20kHz, requires phantom power, shock mount included.',
  'each',
  ARRAY['Condenser Mic', 'LDC', 'Studio Mic', 'Vocal Condenser'],
  ARRAY['microphone', 'condenser', 'large diaphragm', 'studio', 'vocal'],
  ARRAY['audio', 'microphone', 'studio', 'condenser'],
  'Neumann',
  'U87',
  '8" length',
  '1.1 lbs',
  '48V phantom power',
  8,
  '$75-150 per day',
  false,
  true,
  '1 week',
  ARRAY['Professional audio rental', 'Recording studios'],
  true,
  true,
  8
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Shotgun Microphone',
  'shotgun-microphone',
  'Directional shotgun microphone for broadcast',
  'Super-cardioid shotgun mic, 40Hz-20kHz, windscreen and boom pole compatible.',
  'each',
  ARRAY['Shotgun Mic', 'Boom Mic', 'Directional Mic'],
  ARRAY['shotgun', 'microphone', 'boom', 'directional', 'broadcast'],
  ARRAY['audio', 'microphone', 'broadcast', 'video'],
  'Sennheiser',
  'MKH 416',
  '10" length',
  '0.35 lbs',
  '48V phantom power',
  4,
  '$50-100 per day',
  false,
  true,
  '1 week',
  ARRAY['Video production rental', 'Broadcast rental'],
  true,
  true,
  9
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Lavalier Microphone (Wireless)',
  'lavalier-mic-wireless',
  'Wireless lavalier microphone for presentations',
  'Omnidirectional lav mic with bodypack transmitter and receiver.',
  'system',
  ARRAY['Lav Mic', 'Lapel Mic', 'Wireless Lav', 'Clip-on Mic'],
  ARRAY['lavalier', 'lav', 'lapel', 'wireless', 'microphone', 'presentation'],
  ARRAY['audio', 'microphone', 'wireless', 'presentation'],
  'Sennheiser',
  'EW 112P G4',
  'Bodypack + receiver',
  '1.5 lbs',
  '100-240V',
  12,
  '$50-100 per day',
  false,
  false,
  '1 week',
  ARRAY['AV rental', 'Presentation equipment'],
  true,
  true,
  10
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Boundary Microphone',
  'boundary-microphone',
  'Low-profile boundary/surface microphone',
  'Omnidirectional boundary mic for conference tables, 50Hz-18kHz.',
  'each',
  ARRAY['Boundary Mic', 'Surface Mic', 'Table Mic', 'PZM'],
  ARRAY['boundary', 'surface', 'microphone', 'table', 'conference', 'pzm'],
  ARRAY['audio', 'microphone', 'conference'],
  'Shure',
  'MX395',
  '5" diameter',
  '0.5 lbs',
  '12-52V phantom power',
  8,
  '$25-50 per day',
  false,
  false,
  '3 days',
  ARRAY['AV rental', 'Conference equipment'],
  true,
  true,
  11
),

-- Speakers & Monitors
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Point Source Speaker (12" 2-way)',
  'point-source-speaker-12in',
  'Powered 12-inch 2-way point source speaker',
  '1000W powered speaker, 12" woofer + 1.4" compression driver, 90x50° coverage.',
  'each',
  ARRAY['Powered Speaker', 'PA Speaker', '12-inch Speaker', 'Point Source'],
  ARRAY['speaker', 'powered', '12', 'point source', 'pa', '2-way'],
  ARRAY['audio', 'speaker', 'pa'],
  'QSC',
  'K12.2',
  '23" x 14" x 13"',
  '37 lbs',
  '100-240V',
  12,
  '$40-80 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental', 'Guitar Center'],
  true,
  true,
  12
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Point Source Speaker (15" 2-way)',
  'point-source-speaker-15in',
  'Powered 15-inch 2-way point source speaker',
  '1500W powered speaker, 15" woofer + 1.75" compression driver, 90x50° coverage.',
  'each',
  ARRAY['Powered Speaker', 'PA Speaker', '15-inch Speaker', 'Point Source'],
  ARRAY['speaker', 'powered', '15', 'point source', 'pa', '2-way'],
  ARRAY['audio', 'speaker', 'pa'],
  'QSC',
  'K15.2',
  '27" x 16" x 15"',
  '51 lbs',
  '100-240V',
  8,
  '$50-100 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental', 'Guitar Center'],
  true,
  true,
  13
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Subwoofer (15" Powered)',
  'subwoofer-15-powered',
  'Powered 15-inch subwoofer',
  'Self-powered 15" subwoofer, 1000W, frequency response 40Hz-125Hz.',
  'each',
  ARRAY['Sub', 'Bass Bin', '15-inch Sub', 'Powered Sub'],
  ARRAY['sub', 'subwoofer', 'bass', '15', 'powered', 'lf'],
  ARRAY['audio', 'bass', 'subwoofer', 'low frequency'],
  'QSC',
  'KS118',
  '24" x 21" x 28"',
  '107 lbs',
  '100-240V',
  6,
  '$75-150 per day',
  false,
  true,
  '1 week',
  ARRAY['Local audio rental', 'PRG'],
  true,
  true,
  14
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Subwoofer (21" Dual Powered)',
  'subwoofer-21-dual-powered',
  'Dual 21-inch powered subwoofer',
  'Self-powered dual 21" subwoofer, 3600W, frequency response 28Hz-100Hz.',
  'each',
  ARRAY['Sub', 'Bass Bin', '21-inch Sub', 'Dual Sub'],
  ARRAY['sub', 'subwoofer', 'bass', '21', 'dual', 'powered', 'lf'],
  ARRAY['audio', 'bass', 'subwoofer', 'low frequency'],
  'Meyer Sound',
  '900-LFC',
  '42" x 28" x 36"',
  '295 lbs',
  '100-240V',
  2,
  '$200-400 per day',
  false,
  true,
  '2 weeks',
  ARRAY['PRG', 'Solotech', 'Eighth Day Sound'],
  true,
  true,
  15
),

-- Audio Processing & Effects
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Graphic Equalizer (31-band)',
  'graphic-eq-31-band',
  '31-band graphic equalizer',
  'Dual-channel 31-band 1/3-octave graphic EQ with XLR I/O.',
  'each',
  ARRAY['Graphic EQ', 'EQ', 'Equalizer', '31-band'],
  ARRAY['equalizer', 'eq', 'graphic', '31', 'band', 'processor'],
  ARRAY['audio', 'processing', 'eq'],
  'DBX',
  '231s',
  '19" rack, 2U',
  '12 lbs',
  '100-240V',
  4,
  '$20-40 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental'],
  true,
  true,
  16
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Compressor/Limiter (Dual Channel)',
  'compressor-limiter-dual',
  'Dual-channel compressor/limiter',
  'Professional dynamics processor with compression, limiting, and gating.',
  'each',
  ARRAY['Compressor', 'Limiter', 'Dynamics Processor', 'Comp/Limiter'],
  ARRAY['compressor', 'limiter', 'dynamics', 'processor', 'audio'],
  ARRAY['audio', 'processing', 'dynamics'],
  'DBX',
  '266xs',
  '19" rack, 1U',
  '8 lbs',
  '100-240V',
  3,
  '$25-50 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental'],
  true,
  true,
  17
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Effects Processor (Multi-FX)',
  'effects-processor-multi-fx',
  'Multi-effects processor with reverb, delay, chorus',
  'Professional effects unit with hundreds of presets, stereo I/O.',
  'each',
  ARRAY['Effects', 'FX Processor', 'Reverb', 'Multi-FX'],
  ARRAY['effects', 'fx', 'processor', 'reverb', 'delay', 'chorus'],
  ARRAY['audio', 'processing', 'effects'],
  'Lexicon',
  'MX400',
  '19" rack, 2U',
  '10 lbs',
  '100-240V',
  2,
  '$30-60 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental'],
  true,
  true,
  18
),

-- Audio Interfaces & Recorders
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Digital Audio Interface (8-channel)',
  'audio-interface-8ch',
  '8-channel USB audio interface',
  'Professional audio interface with 8 mic preamps, USB connectivity, 24-bit/192kHz.',
  'each',
  ARRAY['Audio Interface', 'USB Interface', 'Recording Interface'],
  ARRAY['interface', 'audio', 'usb', '8', 'channel', 'recording'],
  ARRAY['audio', 'recording', 'interface'],
  'Focusrite',
  'Scarlett 18i20',
  '19" rack, 1U',
  '5 lbs',
  'USB powered',
  2,
  '$40-80 per day',
  false,
  false,
  '3 days',
  ARRAY['Recording studios', 'AV rental'],
  true,
  true,
  19
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Multitrack Recorder (32-track)',
  'multitrack-recorder-32-track',
  '32-track digital multitrack recorder',
  'Standalone multitrack recorder with 32 channels, SD card recording, 24-bit/96kHz.',
  'each',
  ARRAY['Recorder', 'Multitrack', 'Digital Recorder', '32-track'],
  ARRAY['recorder', 'multitrack', 'recording', '32', 'track', 'digital'],
  ARRAY['audio', 'recording', 'multitrack'],
  'Tascam',
  'DP-32SD',
  '17" x 14" x 3"',
  '8 lbs',
  '100-240V',
  1,
  '$50-100 per day',
  false,
  false,
  '1 week',
  ARRAY['Recording studios', 'Audio rental'],
  true,
  true,
  20
),

-- Cables & Accessories
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'XLR Cable (25 ft)',
  'xlr-cable-25ft',
  '25-foot XLR microphone cable',
  'Professional mic cable, XLR male to XLR female, 25ft length.',
  'each',
  ARRAY['Mic Cable', 'XLR Cable', 'Microphone Cable'],
  ARRAY['xlr', 'cable', 'mic', 'microphone', '25', 'feet'],
  ARRAY['audio', 'cable', 'xlr'],
  'Mogami',
  'Gold Studio',
  '25 ft',
  '1 lb',
  NULL,
  50,
  '$3-8 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental', 'Music stores'],
  true,
  true,
  21
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'XLR Cable (50 ft)',
  'xlr-cable-50ft',
  '50-foot XLR microphone cable',
  'Professional mic cable, XLR male to XLR female, 50ft length.',
  'each',
  ARRAY['Mic Cable', 'XLR Cable', 'Microphone Cable'],
  ARRAY['xlr', 'cable', 'mic', 'microphone', '50', 'feet'],
  ARRAY['audio', 'cable', 'xlr'],
  'Mogami',
  'Gold Studio',
  '50 ft',
  '2 lbs',
  NULL,
  30,
  '$5-12 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental', 'Music stores'],
  true,
  true,
  22
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Speaker Cable (50 ft Speakon)',
  'speaker-cable-50ft-speakon',
  '50-foot Speakon speaker cable',
  'Professional speaker cable, Speakon NL4 connectors, 12AWG, 50ft.',
  'each',
  ARRAY['Speaker Cable', 'Speakon Cable', 'PA Cable'],
  ARRAY['speaker', 'cable', 'speakon', 'nl4', '50', 'feet'],
  ARRAY['audio', 'cable', 'speaker'],
  'ProCo',
  'Excellines',
  '50 ft',
  '3 lbs',
  NULL,
  40,
  '$5-12 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental'],
  true,
  true,
  23
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Direct Box (Passive)',
  'direct-box-passive',
  'Passive direct injection box',
  'Passive DI box for converting unbalanced to balanced signals.',
  'each',
  ARRAY['DI Box', 'Direct Box', 'DI', 'Passive DI'],
  ARRAY['di', 'direct', 'box', 'passive', 'injection'],
  ARRAY['audio', 'di box', 'signal'],
  'Radial',
  'ProDI',
  '5" x 3" x 2"',
  '1 lb',
  NULL,
  15,
  '$5-15 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental', 'Music stores'],
  true,
  true,
  24
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'audio'),
  'Direct Box (Active)',
  'direct-box-active',
  'Active direct injection box',
  'Active DI box with phantom power, pad, and ground lift.',
  'each',
  ARRAY['DI Box', 'Direct Box', 'DI', 'Active DI'],
  ARRAY['di', 'direct', 'box', 'active', 'injection', 'phantom'],
  ARRAY['audio', 'di box', 'signal'],
  'Radial',
  'J48',
  '5" x 3" x 2"',
  '1 lb',
  '48V phantom power',
  10,
  '$10-20 per day',
  false,
  false,
  '3 days',
  ARRAY['Local audio rental', 'Music stores'],
  true,
  true,
  25
);

COMMIT;
