-- ============================================================================
-- CATALOG EXPANSION - LIGHTING (Comprehensive)
-- Expanding lighting category with full professional inventory
-- ============================================================================

BEGIN;

-- ============================================================================
-- TECHNICAL PRODUCTION - LIGHTING (Additional Items)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, dimensions, weight, power_requirements,
  typical_quantity, estimated_cost,
  requires_certification, requires_insurance, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
-- Conventional Fixtures
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'ERS Ellipsoidal (Source Four 750W)',
  'ers-ellipsoidal-source-four-750w',
  'ETC Source Four ellipsoidal spotlight',
  '750W HPL lamp, 19° or 26° or 36° or 50° lens tube options.',
  'each',
  ARRAY['Source Four', 'Ellipsoidal', 'Leko', 'ERS', 'Spot Light'],
  ARRAY['source', 'four', 'ellipsoidal', 'leko', 'ers', 'spotlight', '750'],
  ARRAY['lighting', 'conventional', 'ellipsoidal'],
  'ETC',
  'Source Four 750W',
  '26" length',
  '15 lbs',
  '120V',
  30,
  '$15-30 per day',
  false,
  false,
  '1 week',
  ARRAY['4Wall Entertainment', 'Barbizon', 'Local theater rental'],
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'Fresnel (6" 750W)',
  'fresnel-6in-750w',
  '6-inch fresnel spotlight',
  '750W tungsten fresnel with barn doors, adjustable beam 10-60°.',
  'each',
  ARRAY['Fresnel', '6-inch Fresnel', 'Spot Light'],
  ARRAY['fresnel', '6', 'inch', 'spotlight', '750', 'tungsten'],
  ARRAY['lighting', 'conventional', 'fresnel'],
  'Strand',
  'Cantata',
  '18" length',
  '12 lbs',
  '120V',
  20,
  '$12-25 per day',
  false,
  false,
  '1 week',
  ARRAY['4Wall Entertainment', 'Barbizon', 'Local theater rental'],
  true,
  true,
  7
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'PAR Can (PAR64 1000W)',
  'par-can-par64-1000w',
  'PAR64 1000W par can fixture',
  '1000W PAR64 lamp, narrow/medium/wide beam options, with barn doors.',
  'each',
  ARRAY['PAR Can', 'PAR64', 'Par Light'],
  ARRAY['par', 'can', 'par64', '1000', 'tungsten', 'lamp'],
  ARRAY['lighting', 'conventional', 'par'],
  'Altman',
  'PAR64',
  '12" length',
  '8 lbs',
  '120V',
  40,
  '$8-15 per day',
  false,
  false,
  '3 days',
  ARRAY['Local lighting rental', '4Wall', 'Barbizon'],
  true,
  true,
  8
),

-- LED Fixtures
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'LED Ellipsoidal (Source Four LED)',
  'led-ellipsoidal-source-four-led',
  'ETC Source Four LED ellipsoidal',
  'LED ellipsoidal with full color mixing, 19° or 26° or 36° or 50° lens.',
  'each',
  ARRAY['Source Four LED', 'LED Leko', 'LED Ellipsoidal', 'LED ERS'],
  ARRAY['source', 'four', 'led', 'ellipsoidal', 'leko', 'color'],
  ARRAY['lighting', 'led', 'ellipsoidal'],
  'ETC',
  'Source Four LED Series 3',
  '26" length',
  '18 lbs',
  '100-240V',
  20,
  '$30-60 per day',
  false,
  true,
  '2 weeks',
  ARRAY['4Wall Entertainment', 'PRG', 'Barbizon'],
  true,
  true,
  9
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'LED Fresnel (6" LED)',
  'led-fresnel-6in',
  '6-inch LED fresnel',
  'LED fresnel with tungsten emulation or full color, adjustable beam 15-70°.',
  'each',
  ARRAY['LED Fresnel', '6-inch LED', 'Color Fresnel'],
  ARRAY['led', 'fresnel', '6', 'inch', 'color', 'tungsten'],
  ARRAY['lighting', 'led', 'fresnel'],
  'ETC',
  'Desire D60',
  '18" length',
  '14 lbs',
  '100-240V',
  15,
  '$25-50 per day',
  false,
  false,
  '1 week',
  ARRAY['4Wall Entertainment', 'PRG', 'Barbizon'],
  true,
  true,
  10
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'LED Cyc Light (4-cell)',
  'led-cyc-light-4-cell',
  'LED cyclorama wash light',
  '4-cell RGBW LED cyc light for backdrop washing, DMX control.',
  'each',
  ARRAY['Cyc Light', 'LED Cyc', 'Backdrop Light', 'Wall Wash'],
  ARRAY['cyc', 'cyclorama', 'led', 'wash', 'backdrop', 'wall'],
  ARRAY['lighting', 'led', 'cyc', 'wash'],
  'Chauvet',
  'COLORado Batten 72 Tour',
  '40" x 6" x 8"',
  '22 lbs',
  '100-240V',
  12,
  '$35-70 per day',
  false,
  false,
  '1 week',
  ARRAY['4Wall Entertainment', 'Local lighting rental'],
  true,
  true,
  11
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'LED Tube Light (4 ft RGBW)',
  'led-tube-light-4ft-rgbw',
  '4-foot LED tube light',
  'RGBW LED tube with individual pixel control, DMX, battery option.',
  'each',
  ARRAY['LED Tube', 'Pixel Tube', 'RGB Tube', 'Tube Light'],
  ARRAY['led', 'tube', 'pixel', 'rgbw', '4', 'feet', 'battery'],
  ARRAY['lighting', 'led', 'tube', 'pixel'],
  'Astera',
  'Titan Tube',
  '48" length',
  '4 lbs',
  '100-240V or battery',
  20,
  '$30-60 per day',
  false,
  false,
  '1 week',
  ARRAY['4Wall Entertainment', 'PRG', 'Lighting rental'],
  true,
  true,
  12
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'LED Uplighter (Battery RGBW)',
  'led-uplighter-battery-rgbw',
  'Battery-powered LED uplighter',
  'Wireless RGBW LED uplight with battery, DMX wireless control, 12+ hour runtime.',
  'each',
  ARRAY['LED Uplight', 'Battery Uplight', 'Wireless Uplight', 'RGB Uplight'],
  ARRAY['led', 'uplight', 'battery', 'wireless', 'rgbw', 'wash'],
  ARRAY['lighting', 'led', 'uplight', 'battery'],
  'Chauvet',
  'Freedom Par Quad-4',
  '10" x 10" x 11"',
  '6 lbs',
  'Battery or AC',
  30,
  '$15-30 per day',
  false,
  false,
  '3 days',
  ARRAY['Event lighting rental', '4Wall', 'Local rental'],
  true,
  true,
  13
),

-- Specialty Fixtures
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'LED Blinder (4-lite)',
  'led-blinder-4-lite',
  'LED blinder/audience light',
  '4-cell LED blinder with warm white or RGBW, DMX control.',
  'each',
  ARRAY['Blinder', 'Audience Light', 'LED Blinder', '4-lite'],
  ARRAY['blinder', 'led', 'audience', 'light', '4', 'cell'],
  ARRAY['lighting', 'led', 'blinder', 'audience'],
  'Chauvet',
  'COLORado Panel Q40',
  '20" x 20" x 4"',
  '18 lbs',
  '100-240V',
  8,
  '$25-50 per day',
  false,
  false,
  '1 week',
  ARRAY['4Wall Entertainment', 'Lighting rental'],
  true,
  true,
  14
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'Strobe Light (LED)',
  'strobe-light-led',
  'LED strobe fixture',
  'High-power LED strobe with variable speed, DMX control.',
  'each',
  ARRAY['Strobe', 'LED Strobe', 'Flash Light'],
  ARRAY['strobe', 'led', 'flash', 'effect', 'dmx'],
  ARRAY['lighting', 'led', 'strobe', 'effect'],
  'Chauvet',
  'Shocker 2',
  '12" x 12" x 8"',
  '12 lbs',
  '100-240V',
  6,
  '$20-40 per day',
  false,
  false,
  '3 days',
  ARRAY['4Wall Entertainment', 'Lighting rental'],
  true,
  true,
  15
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'UV/Blacklight (LED)',
  'uv-blacklight-led',
  'LED UV/blacklight fixture',
  'UV LED fixture for blacklight effects, 365nm wavelength, DMX.',
  'each',
  ARRAY['UV Light', 'Blacklight', 'LED UV', 'Ultraviolet'],
  ARRAY['uv', 'blacklight', 'led', 'ultraviolet', 'effect'],
  ARRAY['lighting', 'led', 'uv', 'effect'],
  'Chauvet',
  'SlimPAR 64 UV',
  '10" x 10" x 4"',
  '5 lbs',
  '100-240V',
  10,
  '$15-30 per day',
  false,
  false,
  '3 days',
  ARRAY['Event lighting rental', 'Local rental'],
  true,
  true,
  16
),

-- Control & Dimming
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'Dimmer Pack (12-channel)',
  'dimmer-pack-12-channel',
  '12-channel dimmer pack',
  '12x 2.4kW dimmer channels, DMX control, Edison outputs.',
  'each',
  ARRAY['Dimmer', 'Dimmer Pack', '12-channel Dimmer'],
  ARRAY['dimmer', 'pack', '12', 'channel', 'dmx', 'control'],
  ARRAY['lighting', 'dimmer', 'control'],
  'Leviton',
  'D4DMX',
  '19" rack, 3U',
  '35 lbs',
  '208V',
  4,
  '$40-80 per day',
  true,
  false,
  '1 week',
  ARRAY['4Wall Entertainment', 'Lighting rental'],
  true,
  true,
  17
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'Lighting Console (Small Format)',
  'lighting-console-small',
  'Small format lighting control console',
  'Compact lighting console, 512 DMX channels, effects engine, touchscreen.',
  'each',
  ARRAY['Light Board', 'Lighting Desk', 'DMX Console', 'Control Console'],
  ARRAY['console', 'lighting', 'dmx', 'control', 'desk', 'board'],
  ARRAY['lighting', 'control', 'dmx', 'console'],
  'Chamsys',
  'MagicQ MQ50',
  '20" x 16" x 4"',
  '15 lbs',
  '100-240V',
  2,
  '$100-200 per day',
  false,
  true,
  '2 weeks',
  ARRAY['4Wall Entertainment', 'PRG', 'Lighting rental'],
  true,
  true,
  18
),

-- Rigging & Mounting
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'Lighting Stand (12 ft)',
  'lighting-stand-12ft',
  'Crank-up lighting stand',
  'Aluminum crank stand, 12ft max height, T-bar top, 100lb capacity.',
  'each',
  ARRAY['Light Stand', 'Crank Stand', 'T-Bar Stand'],
  ARRAY['stand', 'lighting', 'crank', '12', 'feet', 't-bar'],
  ARRAY['lighting', 'stand', 'rigging'],
  'Global Truss',
  'ST-132',
  '12 ft max height',
  '45 lbs',
  NULL,
  15,
  '$15-30 per day',
  false,
  false,
  '3 days',
  ARRAY['Lighting rental', 'Event rental'],
  true,
  true,
  19
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'Lighting Truss (8 ft)',
  'lighting-truss-8ft',
  '8-foot lighting truss section',
  '12" x 12" box truss, 8ft length, for overhead lighting.',
  'section',
  ARRAY['Truss', 'Light Truss', 'Box Truss'],
  ARRAY['truss', 'lighting', '8', 'feet', 'box', 'overhead'],
  ARRAY['lighting', 'truss', 'rigging'],
  'Global Truss',
  'F34',
  '8 ft x 12" x 12"',
  '28 lbs',
  NULL,
  20,
  '$12-25 per day',
  false,
  false,
  '1 week',
  ARRAY['Lighting rental', 'Staging companies'],
  true,
  true,
  20
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'C-Clamp (Lighting)',
  'c-clamp-lighting',
  'Lighting C-clamp for pipe mounting',
  'Heavy-duty C-clamp for mounting fixtures to 1.5" or 2" pipe.',
  'each',
  ARRAY['C-Clamp', 'Pipe Clamp', 'Lighting Clamp'],
  ARRAY['clamp', 'c-clamp', 'pipe', 'mounting', 'lighting'],
  ARRAY['lighting', 'rigging', 'clamp'],
  'Chauvet',
  'CTC-50',
  '6" x 3"',
  '1 lb',
  NULL,
  50,
  '$2-5 per day',
  false,
  false,
  '3 days',
  ARRAY['Lighting rental', 'Hardware stores'],
  true,
  true,
  21
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'Safety Cable (Lighting)',
  'safety-cable-lighting',
  'Lighting safety cable',
  'Steel safety cable for securing lighting fixtures, 500lb rating.',
  'each',
  ARRAY['Safety Cable', 'Safety Wire', 'Fixture Safety'],
  ARRAY['safety', 'cable', 'wire', 'lighting', 'fixture', 'secure'],
  ARRAY['lighting', 'safety', 'rigging'],
  'ProX',
  'XC-SC500',
  '24" length',
  '0.25 lbs',
  NULL,
  100,
  '$1-3 per day',
  false,
  false,
  '3 days',
  ARRAY['Lighting rental', 'Hardware stores'],
  true,
  true,
  22
),

-- Power & Cable
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'DMX Cable (25 ft)',
  'dmx-cable-25ft',
  '25-foot DMX cable',
  '5-pin DMX cable, 25ft length, for lighting control.',
  'each',
  ARRAY['DMX Cable', 'Lighting Cable', '5-pin DMX'],
  ARRAY['dmx', 'cable', '25', 'feet', '5-pin', 'lighting'],
  ARRAY['lighting', 'cable', 'dmx'],
  'ProCo',
  'Stagemaster',
  '25 ft',
  '1 lb',
  NULL,
  40,
  '$3-8 per day',
  false,
  false,
  '3 days',
  ARRAY['Lighting rental', 'Music stores'],
  true,
  true,
  23
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'DMX Cable (50 ft)',
  'dmx-cable-50ft',
  '50-foot DMX cable',
  '5-pin DMX cable, 50ft length, for lighting control.',
  'each',
  ARRAY['DMX Cable', 'Lighting Cable', '5-pin DMX'],
  ARRAY['dmx', 'cable', '50', 'feet', '5-pin', 'lighting'],
  ARRAY['lighting', 'cable', 'dmx'],
  'ProCo',
  'Stagemaster',
  '50 ft',
  '2 lbs',
  NULL,
  25,
  '$5-12 per day',
  false,
  false,
  '3 days',
  ARRAY['Lighting rental', 'Music stores'],
  true,
  true,
  24
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'lighting'),
  'Power Cable (Edison 25 ft)',
  'power-cable-edison-25ft',
  '25-foot Edison power cable',
  'Heavy-duty Edison power cable, 12AWG, 25ft.',
  'each',
  ARRAY['Power Cable', 'Edison Cable', 'Extension Cord'],
  ARRAY['power', 'cable', 'edison', '25', 'feet', 'extension'],
  ARRAY['lighting', 'power', 'cable'],
  'ProCo',
  'Lifelines',
  '25 ft',
  '2 lbs',
  NULL,
  50,
  '$3-8 per day',
  false,
  false,
  '3 days',
  ARRAY['Lighting rental', 'Hardware stores'],
  true,
  true,
  25
);

COMMIT;
