-- ============================================================================
-- CATALOG BACKLINE - COMPREHENSIVE (Industry Standard Equipment)
-- Based on professional touring and production standards
-- ============================================================================

BEGIN;

-- ============================================================================
-- BACKLINE - GUITAR AMPLIFIERS (Top 10)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Marshall JCM800 2203 Head + 1960A Cab',
  'marshall-jcm800-head-cab',
  'Iconic 100W tube guitar amp head with 4x12 cabinet',
  '100W all-tube head, 4x12" Celestion G12T-75 speakers, classic rock tone',
  'system',
  ARRAY['Marshall Stack', 'JCM800', 'Marshall Head', 'Guitar Stack'],
  ARRAY['marshall', 'jcm800', 'guitar', 'amp', 'head', 'cabinet', 'stack', 'tube'],
  ARRAY['backline', 'guitar', 'amplifier', 'marshall'],
  'Marshall',
  'JCM800 2203 + 1960A',
  '120V',
  2,
  '$100-200 per day',
  '1 week',
  ARRAY['Backline rental', 'Guitar Center', 'Music stores'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Fender Twin Reverb (Reissue)',
  'fender-twin-reverb',
  'Classic 85W 2x12 combo amp',
  '85W tube combo, 2x12" speakers, reverb and tremolo, clean Fender tone',
  'each',
  ARRAY['Twin Reverb', 'Fender Twin', 'Twin Amp'],
  ARRAY['fender', 'twin', 'reverb', 'combo', 'guitar', 'amp', 'tube'],
  ARRAY['backline', 'guitar', 'amplifier', 'fender'],
  'Fender',
  'Twin Reverb',
  '120V',
  3,
  '$75-150 per day',
  '1 week',
  ARRAY['Backline rental', 'Guitar Center'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Mesa/Boogie Dual Rectifier Head + Cab',
  'mesa-dual-rectifier',
  '100W high-gain tube head with 4x12 cabinet',
  '100W 3-channel tube head, 4x12" Celestion V30 speakers, modern metal tone',
  'system',
  ARRAY['Mesa Boogie', 'Dual Rec', 'Rectifier', 'Mesa Stack'],
  ARRAY['mesa', 'boogie', 'dual', 'rectifier', 'guitar', 'amp', 'metal'],
  ARRAY['backline', 'guitar', 'amplifier', 'mesa'],
  'Mesa/Boogie',
  'Dual Rectifier',
  '120V',
  2,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Professional audio'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Vox AC30C2 Combo',
  'vox-ac30-combo',
  'Classic 30W British combo amp',
  '30W tube combo, 2x12" Celestion Alnico Blue speakers, vintage British tone',
  'each',
  ARRAY['Vox AC30', 'AC30', 'Vox Combo'],
  ARRAY['vox', 'ac30', 'combo', 'guitar', 'amp', 'british', 'tube'],
  ARRAY['backline', 'guitar', 'amplifier', 'vox'],
  'Vox',
  'AC30C2',
  '120V',
  2,
  '$60-120 per day',
  '1 week',
  ARRAY['Backline rental', 'Music stores'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Orange Rockerverb 100 MKIII Head + PPC412',
  'orange-rockerverb-100',
  '100W British tube head with 4x12 cabinet',
  '100W tube head, 4x12" Voice of the World speakers, British crunch tone',
  'system',
  ARRAY['Orange Amp', 'Rockerverb', 'Orange Stack'],
  ARRAY['orange', 'rockerverb', 'guitar', 'amp', 'head', 'british'],
  ARRAY['backline', 'guitar', 'amplifier', 'orange'],
  'Orange',
  'Rockerverb 100 MKIII',
  '120V',
  1,
  '$100-200 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Professional audio'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Fender Deluxe Reverb (Reissue)',
  'fender-deluxe-reverb',
  'Classic 22W 1x12 combo amp',
  '22W tube combo, 1x12" speaker, reverb and tremolo, vintage Fender tone',
  'each',
  ARRAY['Deluxe Reverb', 'Fender Deluxe', 'Deluxe Amp'],
  ARRAY['fender', 'deluxe', 'reverb', 'combo', 'guitar', 'amp'],
  ARRAY['backline', 'guitar', 'amplifier', 'fender'],
  'Fender',
  'Deluxe Reverb',
  '120V',
  3,
  '$50-100 per day',
  '1 week',
  ARRAY['Backline rental', 'Guitar Center'],
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'EVH 5150III 100W Head + 4x12 Cab',
  'evh-5150-iii',
  'High-gain 100W tube head with cabinet',
  '100W 3-channel tube head, 4x12" EVH speakers, modern high-gain tone',
  'system',
  ARRAY['EVH Amp', '5150', 'Van Halen Amp'],
  ARRAY['evh', '5150', 'guitar', 'amp', 'head', 'high-gain', 'metal'],
  ARRAY['backline', 'guitar', 'amplifier', 'evh'],
  'EVH',
  '5150III 100W',
  '120V',
  1,
  '$100-200 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Guitar stores'],
  true,
  true,
  7
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Friedman BE-100 Deluxe Head + Cab',
  'friedman-be100',
  'Boutique 100W tube head with 4x12 cabinet',
  '100W 2-channel tube head, 4x12" Celestion speakers, boutique British tone',
  'system',
  ARRAY['Friedman Amp', 'BE-100', 'Friedman Head'],
  ARRAY['friedman', 'be100', 'guitar', 'amp', 'boutique', 'head'],
  ARRAY['backline', 'guitar', 'amplifier', 'friedman'],
  'Friedman',
  'BE-100 Deluxe',
  '120V',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Boutique audio'],
  true,
  true,
  8
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Peavey 6505+ Head + 4x12 Cab',
  'peavey-6505-plus',
  'High-gain 120W tube head with cabinet',
  '120W 2-channel tube head, 4x12" Sheffield speakers, aggressive metal tone',
  'system',
  ARRAY['Peavey 6505', '6505+', 'Peavey Head'],
  ARRAY['peavey', '6505', 'guitar', 'amp', 'head', 'metal', 'high-gain'],
  ARRAY['backline', 'guitar', 'amplifier', 'peavey'],
  'Peavey',
  '6505+',
  '120V',
  2,
  '$75-150 per day',
  '1 week',
  ARRAY['Backline rental', 'Music stores'],
  true,
  true,
  9
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Kemper Profiler Head + Powered Cab',
  'kemper-profiler',
  'Digital profiling amp with powered cabinet',
  'Digital amp profiler, 600W powered cabinet, thousands of amp profiles',
  'system',
  ARRAY['Kemper', 'Profiler', 'Digital Amp', 'Modeling Amp'],
  ARRAY['kemper', 'profiler', 'digital', 'modeling', 'guitar', 'amp'],
  ARRAY['backline', 'guitar', 'amplifier', 'digital'],
  'Kemper',
  'Profiler Head',
  '120V',
  2,
  '$100-200 per day',
  '1 week',
  ARRAY['Backline rental', 'Professional audio'],
  true,
  true,
  10
);

-- ============================================================================
-- BACKLINE - BASS AMPLIFIERS (Top 10)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Ampeg SVT-CL Head + SVT-810E Cab',
  'ampeg-svt-cl',
  'Classic 300W all-tube bass head with 8x10 cabinet',
  '300W all-tube head, 8x10" speakers, legendary Ampeg tone',
  'system',
  ARRAY['Ampeg SVT', 'SVT Classic', 'Ampeg Stack'],
  ARRAY['ampeg', 'svt', 'bass', 'amp', 'head', 'tube', '8x10'],
  ARRAY['backline', 'bass', 'amplifier', 'ampeg'],
  'Ampeg',
  'SVT-CL + SVT-810E',
  '120V',
  2,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Professional audio'],
  true,
  true,
  11
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Ampeg SVT-7 PRO Head + SVT-410HLF Cab',
  'ampeg-svt7-pro',
  '1000W Class-D bass head with 4x10 cabinet',
  '1000W Class-D head, 4x10" speakers with horn, modern Ampeg tone',
  'system',
  ARRAY['Ampeg SVT-7', 'SVT Pro', 'Ampeg Bass'],
  ARRAY['ampeg', 'svt', 'bass', 'amp', 'class-d', '4x10'],
  ARRAY['backline', 'bass', 'amplifier', 'ampeg'],
  'Ampeg',
  'SVT-7 PRO',
  '120V',
  2,
  '$100-200 per day',
  '1 week',
  ARRAY['Backline rental', 'Music stores'],
  true,
  true,
  12
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Gallien-Krueger 800RB Head + 4x10 Cab',
  'gk-800rb',
  '300W solid-state bass head with 4x10 cabinet',
  '300W bi-amp head, 4x10" speakers, punchy GK tone',
  'system',
  ARRAY['GK 800RB', 'Gallien-Krueger', 'GK Bass'],
  ARRAY['gk', 'gallien', 'krueger', '800rb', 'bass', 'amp'],
  ARRAY['backline', 'bass', 'amplifier', 'gk'],
  'Gallien-Krueger',
  '800RB',
  '120V',
  2,
  '$75-150 per day',
  '1 week',
  ARRAY['Backline rental', 'Music stores'],
  true,
  true,
  13
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Markbass Little Mark III Head + 4x10 Cab',
  'markbass-little-mark-iii',
  '500W lightweight bass head with 4x10 cabinet',
  '500W Class-D head, 4x10" speakers, Italian Markbass tone',
  'system',
  ARRAY['Markbass', 'Little Mark', 'Markbass Head'],
  ARRAY['markbass', 'little', 'mark', 'bass', 'amp', 'lightweight'],
  ARRAY['backline', 'bass', 'amplifier', 'markbass'],
  'Markbass',
  'Little Mark III',
  '120V',
  2,
  '$75-150 per day',
  '1 week',
  ARRAY['Backline rental', 'Music stores'],
  true,
  true,
  14
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Darkglass Microtubes 900 v2 + Cab',
  'darkglass-microtubes-900',
  '900W bass head with distortion circuit',
  '900W Class-D head with Microtubes distortion, 4x10" or 2x12" cab options',
  'system',
  ARRAY['Darkglass', 'Microtubes', 'Darkglass Head'],
  ARRAY['darkglass', 'microtubes', 'bass', 'amp', 'distortion'],
  ARRAY['backline', 'bass', 'amplifier', 'darkglass'],
  'Darkglass',
  'Microtubes 900 v2',
  '120V',
  1,
  '$100-200 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Boutique audio'],
  true,
  true,
  15
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Fender Bassman 800 Head + 8x10 Cab',
  'fender-bassman-800',
  '800W hybrid bass head with 8x10 cabinet',
  '800W hybrid head with tube preamp, 8x10" speakers, classic Fender tone',
  'system',
  ARRAY['Fender Bassman', 'Bassman 800', 'Fender Bass'],
  ARRAY['fender', 'bassman', 'bass', 'amp', 'hybrid', '8x10'],
  ARRAY['backline', 'bass', 'amplifier', 'fender'],
  'Fender',
  'Bassman 800',
  '120V',
  1,
  '$100-200 per day',
  '1 week',
  ARRAY['Backline rental', 'Music stores'],
  true,
  true,
  16
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Aguilar Tone Hammer 700 + DB 4x10 Cab',
  'aguilar-tone-hammer-700',
  '700W bass head with 4x10 cabinet',
  '700W Class-D head, 4x10" speakers, warm Aguilar tone',
  'system',
  ARRAY['Aguilar', 'Tone Hammer', 'Aguilar Head'],
  ARRAY['aguilar', 'tone', 'hammer', 'bass', 'amp', '4x10'],
  ARRAY['backline', 'bass', 'amplifier', 'aguilar'],
  'Aguilar',
  'Tone Hammer 700',
  '120V',
  1,
  '$100-200 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Boutique audio'],
  true,
  true,
  17
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Mesa/Boogie Subway D-800+ Head + Cab',
  'mesa-subway-d800',
  '800W ultra-lightweight bass head',
  '800W Class-D head, 4x10" or 2x12" cab options, Mesa tone in 4.5 lbs',
  'system',
  ARRAY['Mesa Bass', 'Subway', 'Mesa Boogie Bass'],
  ARRAY['mesa', 'boogie', 'subway', 'bass', 'amp', 'lightweight'],
  ARRAY['backline', 'bass', 'amplifier', 'mesa'],
  'Mesa/Boogie',
  'Subway D-800+',
  '120V',
  1,
  '$100-200 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Professional audio'],
  true,
  true,
  18
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Hartke HA5500 Head + HyDrive 4x10 Cab',
  'hartke-ha5500',
  '500W hybrid bass head with 4x10 cabinet',
  '500W hybrid head with tube preamp, 4x10" HyDrive speakers',
  'system',
  ARRAY['Hartke', 'HA5500', 'Hartke Bass'],
  ARRAY['hartke', 'ha5500', 'bass', 'amp', 'hybrid', '4x10'],
  ARRAY['backline', 'bass', 'amplifier', 'hartke'],
  'Hartke',
  'HA5500',
  '120V',
  2,
  '$75-150 per day',
  '1 week',
  ARRAY['Backline rental', 'Music stores'],
  true,
  true,
  19
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Orange Terror Bass 1000 Head + OBC410 Cab',
  'orange-terror-bass-1000',
  '1000W hybrid bass head with 4x10 cabinet',
  '1000W hybrid head with tube preamp, 4x10" speakers, British Orange tone',
  'system',
  ARRAY['Orange Bass', 'Terror Bass', 'Orange Head'],
  ARRAY['orange', 'terror', 'bass', 'amp', 'hybrid', '4x10'],
  ARRAY['backline', 'bass', 'amplifier', 'orange'],
  'Orange',
  'Terror Bass 1000',
  '120V',
  1,
  '$100-200 per day',
  '1 week',
  ARRAY['Backline rental', 'Music stores'],
  true,
  true,
  20
);

COMMIT;
