-- ============================================================================
-- CATALOG BACKLINE - DRUMS & KEYBOARDS (Industry Standard Equipment)
-- Professional touring drum kits and keyboard instruments
-- ============================================================================

BEGIN;

-- ============================================================================
-- BACKLINE - DRUM KITS (Top 10)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'DW Collector''s Series 5-Piece Shell Pack',
  'dw-collectors-5-piece',
  'Professional 5-piece maple drum kit',
  '22x18 kick, 10x8 & 12x9 toms, 16x14 floor tom, 14x6.5 snare, hardware included',
  'kit',
  ARRAY['DW Drums', 'Drum Workshop', 'DW Kit', '5-Piece Kit'],
  ARRAY['dw', 'drums', 'kit', 'collectors', 'maple', '5-piece'],
  ARRAY['backline', 'drums', 'percussion', 'dw'],
  'DW (Drum Workshop)',
  'Collector''s Series',
  1,
  '$150-300 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Drum shops', 'Professional audio'],
  true,
  true,
  21
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Yamaha Recording Custom 5-Piece Kit',
  'yamaha-recording-custom',
  'Professional 5-piece birch drum kit',
  '22x16 kick, 10x8 & 12x9 toms, 16x15 floor tom, 14x5.5 snare, hardware included',
  'kit',
  ARRAY['Yamaha Drums', 'Recording Custom', 'Yamaha Kit'],
  ARRAY['yamaha', 'drums', 'kit', 'recording', 'custom', 'birch'],
  ARRAY['backline', 'drums', 'percussion', 'yamaha'],
  'Yamaha',
  'Recording Custom',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Drum shops'],
  true,
  true,
  22
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Tama Starclassic Performer B/B 5-Piece',
  'tama-starclassic-5-piece',
  'Professional 5-piece birch/bubinga kit',
  '22x18 kick, 10x7 & 12x8 toms, 16x14 floor tom, 14x5.5 snare, hardware included',
  'kit',
  ARRAY['Tama Drums', 'Starclassic', 'Tama Kit'],
  ARRAY['tama', 'drums', 'kit', 'starclassic', 'birch', 'bubinga'],
  ARRAY['backline', 'drums', 'percussion', 'tama'],
  'Tama',
  'Starclassic Performer B/B',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Drum shops'],
  true,
  true,
  23
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pearl Reference Pure 5-Piece Kit',
  'pearl-reference-pure',
  'Professional 5-piece maple drum kit',
  '22x18 kick, 10x8 & 12x9 toms, 16x16 floor tom, 14x6.5 snare, hardware included',
  'kit',
  ARRAY['Pearl Drums', 'Reference Pure', 'Pearl Kit'],
  ARRAY['pearl', 'drums', 'kit', 'reference', 'pure', 'maple'],
  ARRAY['backline', 'drums', 'percussion', 'pearl'],
  'Pearl',
  'Reference Pure',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Drum shops'],
  true,
  true,
  24
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Ludwig Classic Maple 5-Piece Kit',
  'ludwig-classic-maple',
  'Professional 5-piece maple drum kit',
  '22x18 kick, 10x9 & 12x10 toms, 16x16 floor tom, 14x6.5 snare, hardware included',
  'kit',
  ARRAY['Ludwig Drums', 'Classic Maple', 'Ludwig Kit'],
  ARRAY['ludwig', 'drums', 'kit', 'classic', 'maple', 'vintage'],
  ARRAY['backline', 'drums', 'percussion', 'ludwig'],
  'Ludwig',
  'Classic Maple',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Drum shops'],
  true,
  true,
  25
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Gretsch USA Custom 5-Piece Kit',
  'gretsch-usa-custom',
  'Professional 5-piece maple drum kit',
  '22x18 kick, 10x8 & 12x9 toms, 16x16 floor tom, 14x6.5 snare, hardware included',
  'kit',
  ARRAY['Gretsch Drums', 'USA Custom', 'Gretsch Kit'],
  ARRAY['gretsch', 'drums', 'kit', 'usa', 'custom', 'maple'],
  ARRAY['backline', 'drums', 'percussion', 'gretsch'],
  'Gretsch',
  'USA Custom',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Drum shops'],
  true,
  true,
  26
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Mapex Saturn V MH Exotic 5-Piece',
  'mapex-saturn-v',
  'Professional 5-piece maple/walnut kit',
  '22x18 kick, 10x7 & 12x8 toms, 16x14 floor tom, 14x5.5 snare, hardware included',
  'kit',
  ARRAY['Mapex Drums', 'Saturn V', 'Mapex Kit'],
  ARRAY['mapex', 'drums', 'kit', 'saturn', 'maple', 'walnut'],
  ARRAY['backline', 'drums', 'percussion', 'mapex'],
  'Mapex',
  'Saturn V MH Exotic',
  1,
  '$100-200 per day',
  '1 week',
  ARRAY['Backline rental', 'Drum shops'],
  true,
  true,
  27
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Sonor SQ1 5-Piece Kit',
  'sonor-sq1',
  'Professional 5-piece maple drum kit',
  '22x17.5 kick, 10x8 & 12x9 toms, 16x15 floor tom, 14x6 snare, hardware included',
  'kit',
  ARRAY['Sonor Drums', 'SQ1', 'Sonor Kit'],
  ARRAY['sonor', 'drums', 'kit', 'sq1', 'maple', 'german'],
  ARRAY['backline', 'drums', 'percussion', 'sonor'],
  'Sonor',
  'SQ1',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Drum shops'],
  true,
  true,
  28
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'PDP Concept Maple 7-Piece Kit',
  'pdp-concept-maple-7-piece',
  'Professional 7-piece maple drum kit',
  '22x18 kick, 8x7, 10x8, 12x9 toms, 14x12, 16x14 floor toms, 14x5.5 snare',
  'kit',
  ARRAY['PDP Drums', 'Concept Maple', 'PDP Kit', '7-Piece'],
  ARRAY['pdp', 'drums', 'kit', 'concept', 'maple', '7-piece'],
  ARRAY['backline', 'drums', 'percussion', 'pdp'],
  'PDP (Pacific Drums)',
  'Concept Maple',
  1,
  '$100-200 per day',
  '1 week',
  ARRAY['Backline rental', 'Drum shops'],
  true,
  true,
  29
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Roland TD-50KV V-Drums Electronic Kit',
  'roland-td50kv',
  'Professional electronic drum kit',
  'TD-50 module, mesh heads, digital pads, full kit with cymbals and hardware',
  'kit',
  ARRAY['Roland V-Drums', 'Electronic Drums', 'E-Drums', 'TD-50'],
  ARRAY['roland', 'electronic', 'drums', 'v-drums', 'td50', 'digital'],
  ARRAY['backline', 'drums', 'electronic', 'roland'],
  'Roland',
  'TD-50KV V-Drums',
  1,
  '$150-300 per day',
  '1 week',
  ARRAY['Backline rental', 'Electronic music stores'],
  true,
  true,
  30
);

-- ============================================================================
-- BACKLINE - KEYBOARDS & SYNTHESIZERS (Top 10)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Nord Stage 4 88-Key',
  'nord-stage-4-88',
  'Professional 88-key stage piano with synth and organ',
  '88-key weighted action, piano/organ/synth engines, dual keyboard split',
  'each',
  ARRAY['Nord Stage', 'Nord Piano', 'Stage Piano'],
  ARRAY['nord', 'stage', 'piano', 'keyboard', '88', 'weighted'],
  ARRAY['backline', 'keyboard', 'piano', 'nord'],
  'Nord',
  'Stage 4 88',
  '120V',
  2,
  '$150-300 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Keyboard stores', 'Professional audio'],
  true,
  true,
  31
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Yamaha CP88 Stage Piano',
  'yamaha-cp88',
  'Professional 88-key stage piano',
  '88-key NW-GH weighted action, vintage and modern piano sounds',
  'each',
  ARRAY['Yamaha CP', 'CP88', 'Stage Piano'],
  ARRAY['yamaha', 'cp88', 'piano', 'keyboard', '88', 'stage'],
  ARRAY['backline', 'keyboard', 'piano', 'yamaha'],
  'Yamaha',
  'CP88',
  '120V',
  2,
  '$100-200 per day',
  '1 week',
  ARRAY['Backline rental', 'Keyboard stores'],
  true,
  true,
  32
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Korg SV-2 88 Stage Piano',
  'korg-sv2-88',
  'Professional 88-key vintage stage piano',
  '88-key RH3 weighted action, vintage electric pianos and organs',
  'each',
  ARRAY['Korg SV-2', 'SV2', 'Stage Piano'],
  ARRAY['korg', 'sv2', 'piano', 'keyboard', '88', 'vintage'],
  ARRAY['backline', 'keyboard', 'piano', 'korg'],
  'Korg',
  'SV-2 88',
  '120V',
  2,
  '$100-200 per day',
  '1 week',
  ARRAY['Backline rental', 'Keyboard stores'],
  true,
  true,
  33
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Roland RD-2000 Stage Piano',
  'roland-rd2000',
  'Professional 88-key hybrid stage piano',
  '88-key PHA-50 hybrid action, SuperNATURAL and V-Piano engines',
  'each',
  ARRAY['Roland RD', 'RD-2000', 'Stage Piano'],
  ARRAY['roland', 'rd2000', 'piano', 'keyboard', '88', 'hybrid'],
  ARRAY['backline', 'keyboard', 'piano', 'roland'],
  'Roland',
  'RD-2000',
  '120V',
  2,
  '$125-250 per day',
  '1 week',
  ARRAY['Backline rental', 'Keyboard stores'],
  true,
  true,
  34
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Hammond SK Pro 73 Organ',
  'hammond-sk-pro-73',
  'Professional 73-key organ with drawbars',
  '73-key waterfall action, dual tone wheels, 9 drawbars per manual',
  'each',
  ARRAY['Hammond Organ', 'SK Pro', 'B3 Organ'],
  ARRAY['hammond', 'organ', 'sk', 'pro', '73', 'drawbar', 'b3'],
  ARRAY['backline', 'keyboard', 'organ', 'hammond'],
  'Hammond',
  'SK Pro 73',
  '120V',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Keyboard stores'],
  true,
  true,
  35
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Moog Subsequent 37 Synthesizer',
  'moog-subsequent-37',
  'Analog synthesizer with 37 keys',
  '37-key semi-weighted, 2 oscillators, ladder filter, classic Moog sound',
  'each',
  ARRAY['Moog Synth', 'Subsequent 37', 'Analog Synth'],
  ARRAY['moog', 'synthesizer', 'analog', '37', 'keys', 'synth'],
  ARRAY['backline', 'keyboard', 'synthesizer', 'moog'],
  'Moog',
  'Subsequent 37',
  '120V',
  1,
  '$75-150 per day',
  '1 week',
  ARRAY['Backline rental', 'Synthesizer stores'],
  true,
  true,
  36
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Korg Kronos 2 88 Workstation',
  'korg-kronos-2-88',
  'Professional 88-key music workstation',
  '88-key RH3 weighted action, 9 sound engines, sequencer, sampling',
  'each',
  ARRAY['Korg Kronos', 'Kronos 2', 'Workstation'],
  ARRAY['korg', 'kronos', 'workstation', '88', 'keyboard', 'synth'],
  ARRAY['backline', 'keyboard', 'workstation', 'korg'],
  'Korg',
  'Kronos 2 88',
  '120V',
  1,
  '$150-300 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Keyboard stores'],
  true,
  true,
  37
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Yamaha Montage 8 Synthesizer',
  'yamaha-montage-8',
  'Professional 88-key synthesizer workstation',
  '88-key GH weighted action, AWM2 and FM-X engines, motion control',
  'each',
  ARRAY['Yamaha Montage', 'Montage 8', 'Synth Workstation'],
  ARRAY['yamaha', 'montage', 'synthesizer', '88', 'workstation'],
  ARRAY['backline', 'keyboard', 'synthesizer', 'yamaha'],
  'Yamaha',
  'Montage 8',
  '120V',
  1,
  '$150-300 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Keyboard stores'],
  true,
  true,
  38
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Roland Fantom-8 Workstation',
  'roland-fantom-8',
  'Professional 88-key synthesizer workstation',
  '88-key PHA-50 hybrid action, ZEN-Core engine, V-Piano, sequencer',
  'each',
  ARRAY['Roland Fantom', 'Fantom-8', 'Workstation'],
  ARRAY['roland', 'fantom', 'synthesizer', '88', 'workstation'],
  ARRAY['backline', 'keyboard', 'synthesizer', 'roland'],
  'Roland',
  'Fantom-8',
  '120V',
  1,
  '$150-300 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Keyboard stores'],
  true,
  true,
  39
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Kurzweil K2700 Workstation',
  'kurzweil-k2700',
  'Professional 88-key music workstation',
  '88-key fully-weighted action, V.A.S.T. engine, 16-track sequencer',
  'each',
  ARRAY['Kurzweil', 'K2700', 'Workstation'],
  ARRAY['kurzweil', 'k2700', 'workstation', '88', 'keyboard'],
  ARRAY['backline', 'keyboard', 'workstation', 'kurzweil'],
  'Kurzweil',
  'K2700',
  '120V',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['Backline rental', 'Keyboard stores'],
  true,
  true,
  40
);

COMMIT;
