-- ============================================================================
-- CATALOG BACKLINE - DJ EQUIPMENT (Industry Standard)
-- CDJs, mixers, turntables, controllers, and DJ monitors
-- ============================================================================

BEGIN;

-- ============================================================================
-- BACKLINE - DJ CDJ PLAYERS (Top 10)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pioneer DJ CDJ-3000',
  'pioneer-cdj-3000',
  'Professional multi-player with 9-inch touchscreen',
  'High-res 9" touchscreen, MPU-6050 sensor, USB/SD/Link, 96kHz/24-bit audio',
  'each',
  ARRAY['CDJ-3000', 'Pioneer CDJ', 'Multi-Player', 'DJ Deck'],
  ARRAY['pioneer', 'cdj', '3000', 'dj', 'player', 'deck', 'multi-player'],
  ARRAY['backline', 'dj', 'cdj', 'pioneer'],
  'Pioneer DJ',
  'CDJ-3000',
  '100-240V',
  2,
  '$150-300 per day',
  '2 weeks',
  ARRAY['DJ equipment rental', 'Professional audio', 'Event production'],
  true,
  true,
  41
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pioneer DJ CDJ-2000NXS2',
  'pioneer-cdj-2000nxs2',
  'Professional multi-player with full-color display',
  '7" full-color LCD, USB/SD/Link, 96kHz/24-bit audio, beat sync',
  'each',
  ARRAY['CDJ-2000NXS2', 'Pioneer CDJ', 'NXS2', 'DJ Deck'],
  ARRAY['pioneer', 'cdj', '2000', 'nxs2', 'dj', 'player', 'nexus'],
  ARRAY['backline', 'dj', 'cdj', 'pioneer'],
  'Pioneer DJ',
  'CDJ-2000NXS2',
  '100-240V',
  2,
  '$125-250 per day',
  '2 weeks',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  42
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Denon DJ SC6000 Prime',
  'denon-sc6000-prime',
  'Professional DJ media player with 10.1-inch touchscreen',
  '10.1" motorized touchscreen, dual-layer playback, 96kHz/24-bit audio',
  'each',
  ARRAY['SC6000', 'Denon Prime', 'Prime Player', 'DJ Deck'],
  ARRAY['denon', 'sc6000', 'prime', 'dj', 'player', 'deck'],
  ARRAY['backline', 'dj', 'media player', 'denon'],
  'Denon DJ',
  'SC6000 Prime',
  '100-240V',
  2,
  '$125-250 per day',
  '2 weeks',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  43
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Denon DJ SC5000 Prime',
  'denon-sc5000-prime',
  'Professional DJ media player with 7-inch touchscreen',
  '7" multi-touch display, dual-layer playback, 96kHz/24-bit audio',
  'each',
  ARRAY['SC5000', 'Denon Prime', 'Prime Player'],
  ARRAY['denon', 'sc5000', 'prime', 'dj', 'player', 'media'],
  ARRAY['backline', 'dj', 'media player', 'denon'],
  'Denon DJ',
  'SC5000 Prime',
  '100-240V',
  2,
  '$100-200 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  44
);

-- ============================================================================
-- BACKLINE - DJ MIXERS (Top 10)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pioneer DJ DJM-V10',
  'pioneer-djm-v10',
  'Professional 6-channel DJ mixer',
  '6-channel, 4-band EQ per channel, dual USB, 96kHz/24-bit, send/return FX',
  'each',
  ARRAY['DJM-V10', 'Pioneer Mixer', 'V10', 'Club Mixer'],
  ARRAY['pioneer', 'djm', 'v10', 'mixer', 'dj', '6-channel'],
  ARRAY['backline', 'dj', 'mixer', 'pioneer'],
  'Pioneer DJ',
  'DJM-V10',
  '100-240V',
  1,
  '$150-300 per day',
  '2 weeks',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  45
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pioneer DJ DJM-900NXS2',
  'pioneer-djm-900nxs2',
  'Professional 4-channel DJ mixer',
  '4-channel, 3-band EQ, dual USB, 96kHz/32-bit, Beat FX, Sound Color FX',
  'each',
  ARRAY['DJM-900NXS2', 'Pioneer Mixer', 'NXS2', 'Club Mixer'],
  ARRAY['pioneer', 'djm', '900', 'nxs2', 'mixer', 'dj', 'nexus'],
  ARRAY['backline', 'dj', 'mixer', 'pioneer'],
  'Pioneer DJ',
  'DJM-900NXS2',
  '100-240V',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  46
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Allen & Heath XONE:96',
  'allen-heath-xone-96',
  'Professional 6+2-channel analog DJ mixer',
  '6+2 channels, 4-band EQ, dual USB, analog filters, send/return FX',
  'each',
  ARRAY['XONE:96', 'Allen & Heath', 'Xone Mixer', 'Analog Mixer'],
  ARRAY['allen', 'heath', 'xone', '96', 'mixer', 'dj', 'analog'],
  ARRAY['backline', 'dj', 'mixer', 'allen-heath'],
  'Allen & Heath',
  'XONE:96',
  '100-240V',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  47
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Denon DJ X1850 Prime',
  'denon-x1850-prime',
  'Professional 4-channel DJ mixer',
  '4-channel, 3-band EQ, dual USB, 96kHz/24-bit, sweep FX, dual zone output',
  'each',
  ARRAY['X1850', 'Denon Mixer', 'Prime Mixer'],
  ARRAY['denon', 'x1850', 'prime', 'mixer', 'dj', '4-channel'],
  ARRAY['backline', 'dj', 'mixer', 'denon'],
  'Denon DJ',
  'X1850 Prime',
  '100-240V',
  1,
  '$100-200 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  48
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Rane MP2015 Rotary Mixer',
  'rane-mp2015',
  'Professional 4-channel rotary DJ mixer',
  '4-channel rotary, 3-band EQ, USB, balanced XLR outputs, premium sound',
  'each',
  ARRAY['Rane MP2015', 'Rotary Mixer', 'Rane Mixer'],
  ARRAY['rane', 'mp2015', 'rotary', 'mixer', 'dj', '4-channel'],
  ARRAY['backline', 'dj', 'mixer', 'rane', 'rotary'],
  'Rane',
  'MP2015',
  '100-240V',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['DJ equipment rental', 'Boutique audio'],
  true,
  true,
  49
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pioneer DJ DJM-A9',
  'pioneer-djm-a9',
  'Professional 4-channel DJ mixer with Atmosphere',
  '4-channel, 3-band EQ, dual USB, Atmosphere spatial audio, Beat FX',
  'each',
  ARRAY['DJM-A9', 'Pioneer Mixer', 'A9', 'Atmosphere Mixer'],
  ARRAY['pioneer', 'djm', 'a9', 'mixer', 'dj', 'atmosphere'],
  ARRAY['backline', 'dj', 'mixer', 'pioneer'],
  'Pioneer DJ',
  'DJM-A9',
  '100-240V',
  1,
  '$150-300 per day',
  '2 weeks',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  50
);

-- ============================================================================
-- BACKLINE - TURNTABLES (Top 5)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Technics SL-1200MK7',
  'technics-sl1200mk7',
  'Professional direct-drive DJ turntable',
  'Direct-drive, high-torque motor, pitch control ±8/±16%, USB output, reverse play',
  'each',
  ARRAY['Technics 1200', 'SL-1200', 'MK7', 'Turntable', 'Deck'],
  ARRAY['technics', 'sl1200', 'mk7', 'turntable', 'vinyl', 'dj', 'deck'],
  ARRAY['backline', 'dj', 'turntable', 'technics'],
  'Technics',
  'SL-1200MK7',
  '100-240V',
  2,
  '$75-150 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  51
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pioneer DJ PLX-1000',
  'pioneer-plx-1000',
  'Professional direct-drive DJ turntable',
  'Direct-drive, high-torque motor, pitch control ±8/±16%, tempo reset, detachable power/audio',
  'each',
  ARRAY['PLX-1000', 'Pioneer Turntable', 'PLX', 'Deck'],
  ARRAY['pioneer', 'plx', '1000', 'turntable', 'vinyl', 'dj'],
  ARRAY['backline', 'dj', 'turntable', 'pioneer'],
  'Pioneer DJ',
  'PLX-1000',
  '100-240V',
  2,
  '$60-120 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  52
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Audio-Technica AT-LP1240-USB XP',
  'audio-technica-lp1240',
  'Professional DJ turntable with USB',
  'Direct-drive, high-torque motor, pitch control ±8/±20%, USB output, S-shaped tonearm',
  'each',
  ARRAY['AT-LP1240', 'Audio-Technica', 'LP1240', 'Turntable'],
  ARRAY['audio-technica', 'lp1240', 'turntable', 'vinyl', 'dj', 'usb'],
  ARRAY['backline', 'dj', 'turntable', 'audio-technica'],
  'Audio-Technica',
  'AT-LP1240-USB XP',
  '100-240V',
  2,
  '$50-100 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Music stores'],
  true,
  true,
  53
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Reloop RP-8000 MK2',
  'reloop-rp8000-mk2',
  'Professional DJ turntable with MIDI',
  'Direct-drive, high-torque motor, pitch control ±8/±16/±50%, MIDI control, USB',
  'each',
  ARRAY['RP-8000', 'Reloop', 'RP8000', 'MIDI Turntable'],
  ARRAY['reloop', 'rp8000', 'turntable', 'vinyl', 'dj', 'midi'],
  ARRAY['backline', 'dj', 'turntable', 'reloop'],
  'Reloop',
  'RP-8000 MK2',
  '100-240V',
  2,
  '$60-120 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  54
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Numark TTX USB',
  'numark-ttx-usb',
  'Professional DJ turntable with USB',
  'Direct-drive, high-torque motor, pitch control ±10/±20/±50%, USB output, battle-style',
  'each',
  ARRAY['Numark TTX', 'TTX', 'Numark Turntable'],
  ARRAY['numark', 'ttx', 'turntable', 'vinyl', 'dj', 'usb', 'battle'],
  ARRAY['backline', 'dj', 'turntable', 'numark'],
  'Numark',
  'TTX USB',
  '100-240V',
  2,
  '$50-100 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Music stores'],
  true,
  true,
  55
);

-- ============================================================================
-- BACKLINE - DJ CONTROLLERS (Top 5)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pioneer DJ DDJ-REV7',
  'pioneer-ddj-rev7',
  'Professional 2-channel DJ controller for Serato',
  '2-channel, motorized jog wheels, 7" touchscreens, Serato DJ Pro compatible',
  'each',
  ARRAY['DDJ-REV7', 'Pioneer Controller', 'REV7', 'Serato Controller'],
  ARRAY['pioneer', 'ddj', 'rev7', 'controller', 'dj', 'serato'],
  ARRAY['backline', 'dj', 'controller', 'pioneer'],
  'Pioneer DJ',
  'DDJ-REV7',
  '100-240V',
  1,
  '$100-200 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  56
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pioneer DJ DDJ-FLX10',
  'pioneer-ddj-flx10',
  'Professional 4-channel DJ controller',
  '4-channel, motorized jog wheels, 7" touchscreens, Rekordbox & Serato compatible',
  'each',
  ARRAY['DDJ-FLX10', 'Pioneer Controller', 'FLX10'],
  ARRAY['pioneer', 'ddj', 'flx10', 'controller', 'dj', 'rekordbox'],
  ARRAY['backline', 'dj', 'controller', 'pioneer'],
  'Pioneer DJ',
  'DDJ-FLX10',
  '100-240V',
  1,
  '$100-200 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  57
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Denon DJ Prime 4+',
  'denon-prime-4-plus',
  'Standalone 4-channel DJ controller',
  '4-channel standalone, 10" touchscreen, WiFi streaming, no laptop required',
  'each',
  ARRAY['Prime 4+', 'Denon Controller', 'Standalone Controller'],
  ARRAY['denon', 'prime', '4', 'plus', 'controller', 'standalone', 'dj'],
  ARRAY['backline', 'dj', 'controller', 'denon'],
  'Denon DJ',
  'Prime 4+',
  '100-240V',
  1,
  '$125-250 per day',
  '2 weeks',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  58
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Native Instruments Traktor Kontrol S4 MK3',
  'traktor-s4-mk3',
  'Professional 4-channel DJ controller for Traktor',
  '4-channel, motorized jog wheels, RGB displays, Traktor Pro 3 included',
  'each',
  ARRAY['Traktor S4', 'Kontrol S4', 'NI Controller'],
  ARRAY['native', 'instruments', 'traktor', 's4', 'mk3', 'controller'],
  ARRAY['backline', 'dj', 'controller', 'traktor'],
  'Native Instruments',
  'Traktor Kontrol S4 MK3',
  '100-240V',
  1,
  '$75-150 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Music stores'],
  true,
  true,
  59
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Roland DJ-707M',
  'roland-dj-707m',
  'Professional 4-channel DJ controller',
  '4-channel, large jog wheels, Serato DJ Pro compatible, TR drum sequencer',
  'each',
  ARRAY['DJ-707M', 'Roland Controller', '707M'],
  ARRAY['roland', 'dj', '707m', 'controller', 'serato', 'tr'],
  ARRAY['backline', 'dj', 'controller', 'roland'],
  'Roland',
  'DJ-707M',
  '100-240V',
  1,
  '$75-150 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Music stores'],
  true,
  true,
  60
);

-- ============================================================================
-- BACKLINE - DJ MONITORS (Top 5)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, dimensions, weight, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pioneer DJ VM-50',
  'pioneer-vm-50',
  'Professional 5-inch active DJ monitor',
  '5" woofer, 50W Class-D amp, front bass reflex port, DJ-tuned sound',
  'each',
  ARRAY['VM-50', 'Pioneer Monitor', 'DJ Speaker', 'Booth Monitor'],
  ARRAY['pioneer', 'vm50', 'monitor', 'dj', 'speaker', 'booth', '5-inch'],
  ARRAY['backline', 'dj', 'monitor', 'pioneer'],
  'Pioneer DJ',
  'VM-50',
  '7" x 10" x 8"',
  '11 lbs',
  '100-240V',
  2,
  '$40-80 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  61
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Pioneer DJ VM-80',
  'pioneer-vm-80',
  'Professional 8-inch active DJ monitor',
  '8" woofer, 100W Class-D amp, front bass reflex port, DJ-tuned sound',
  'each',
  ARRAY['VM-80', 'Pioneer Monitor', 'DJ Speaker', 'Booth Monitor'],
  ARRAY['pioneer', 'vm80', 'monitor', 'dj', 'speaker', 'booth', '8-inch'],
  ARRAY['backline', 'dj', 'monitor', 'pioneer'],
  'Pioneer DJ',
  'VM-80',
  '10" x 14" x 11"',
  '24 lbs',
  '100-240V',
  2,
  '$60-120 per day',
  '1 week',
  ARRAY['DJ equipment rental', 'Professional audio'],
  true,
  true,
  62
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'KRK Rokit RP5 G4',
  'krk-rokit-rp5-g4',
  'Professional 5-inch studio monitor for DJs',
  '5" woofer, 55W Class-D amp, DSP-driven EQ, studio-quality sound',
  'each',
  ARRAY['KRK Rokit', 'RP5', 'Studio Monitor', 'DJ Monitor'],
  ARRAY['krk', 'rokit', 'rp5', 'monitor', 'studio', 'dj', '5-inch'],
  ARRAY['backline', 'dj', 'monitor', 'krk'],
  'KRK',
  'Rokit RP5 G4',
  '7" x 11" x 9"',
  '10 lbs',
  '100-240V',
  2,
  '$30-60 per day',
  '3 days',
  ARRAY['DJ equipment rental', 'Studio rental'],
  true,
  true,
  63
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'Yamaha HS8',
  'yamaha-hs8',
  'Professional 8-inch studio monitor for DJs',
  '8" woofer, 120W bi-amp, room control and high trim, accurate sound',
  'each',
  ARRAY['Yamaha HS8', 'HS8', 'Studio Monitor', 'DJ Monitor'],
  ARRAY['yamaha', 'hs8', 'monitor', 'studio', 'dj', '8-inch'],
  ARRAY['backline', 'dj', 'monitor', 'yamaha'],
  'Yamaha',
  'HS8',
  '10" x 15" x 12"',
  '23 lbs',
  '100-240V',
  2,
  '$40-80 per day',
  '3 days',
  ARRAY['DJ equipment rental', 'Studio rental'],
  true,
  true,
  64
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'backline'),
  'JBL 305P MkII',
  'jbl-305p-mkii',
  'Professional 5-inch powered studio monitor',
  '5" woofer, 82W bi-amp, boundary EQ, Image Control Waveguide',
  'each',
  ARRAY['JBL 305P', '305P MkII', 'Studio Monitor', 'DJ Monitor'],
  ARRAY['jbl', '305p', 'mkii', 'monitor', 'studio', 'dj', '5-inch'],
  ARRAY['backline', 'dj', 'monitor', 'jbl'],
  'JBL',
  '305P MkII',
  '7" x 10" x 8"',
  '10 lbs',
  '100-240V',
  2,
  '$30-60 per day',
  '3 days',
  ARRAY['DJ equipment rental', 'Studio rental'],
  true,
  true,
  65
);

COMMIT;
