-- ============================================================================
-- CATALOG - VIDEO & BROADCAST EQUIPMENT (Comprehensive)
-- Cameras, monitors, switchers, streaming, and broadcast gear
-- ============================================================================

BEGIN;

-- ============================================================================
-- TECHNICAL PRODUCTION - VIDEO CAMERAS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Cinema Camera (6K)',
  'cinema-camera-6k',
  'Professional 6K cinema camera',
  '6K Super 35 sensor, RAW recording, EF mount, 13 stops dynamic range',
  'each',
  ARRAY['Cinema Camera', 'Film Camera', '6K Camera', 'Production Camera'],
  ARRAY['cinema', 'camera', '6k', 'film', 'production', 'raw'],
  ARRAY['video', 'camera', 'cinema'],
  'Blackmagic Design',
  'URSA Mini Pro 6K',
  '12-20V DC',
  2,
  '$300-600 per day',
  '2 weeks',
  ARRAY['Camera rental', 'Video production rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Broadcast Camera (4K)',
  'broadcast-camera-4k',
  'Professional 4K broadcast camera with B4 mount',
  '4K UHD sensor, 2/3" B4 mount, 14-bit processing, broadcast workflows',
  'each',
  ARRAY['Broadcast Camera', 'Studio Camera', 'ENG Camera'],
  ARRAY['broadcast', 'camera', '4k', 'studio', 'eng', 'b4'],
  ARRAY['video', 'camera', 'broadcast'],
  'Sony',
  'PXW-Z450',
  '12V DC',
  4,
  '$250-500 per day',
  '2 weeks',
  ARRAY['Broadcast rental', 'Video production'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'PTZ Camera (4K)',
  'ptz-camera-4k',
  'Pan-tilt-zoom camera for remote operation',
  '4K UHD, 20x optical zoom, NDI|HX, PoE+, remote control',
  'each',
  ARRAY['PTZ Camera', 'Robotic Camera', 'Remote Camera'],
  ARRAY['ptz', 'camera', 'pan', 'tilt', 'zoom', '4k', 'ndi'],
  ARRAY['video', 'camera', 'ptz', 'broadcast'],
  'Panasonic',
  'AW-UE150',
  'PoE+ or 12V DC',
  6,
  '$150-300 per day',
  '1 week',
  ARRAY['Broadcast rental', 'AV rental'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'DSLR Camera (Full Frame)',
  'dslr-camera-full-frame',
  'Full-frame DSLR for video production',
  'Full-frame sensor, 4K video, dual card slots, EF mount',
  'each',
  ARRAY['DSLR', 'Digital Camera', 'Photo Camera'],
  ARRAY['dslr', 'camera', 'full', 'frame', 'video', '4k'],
  ARRAY['video', 'camera', 'dslr'],
  'Canon',
  'EOS 5D Mark IV',
  'Battery',
  4,
  '$100-200 per day',
  '1 week',
  ARRAY['Camera rental', 'Photography rental'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Mirrorless Camera (4K)',
  'mirrorless-camera-4k',
  'Professional mirrorless camera for video',
  'Full-frame sensor, 4K 60p, in-body stabilization, E-mount',
  'each',
  ARRAY['Mirrorless', 'Hybrid Camera', 'Video Camera'],
  ARRAY['mirrorless', 'camera', '4k', 'video', 'hybrid'],
  ARRAY['video', 'camera', 'mirrorless'],
  'Sony',
  'A7S III',
  'Battery',
  4,
  '$150-300 per day',
  '1 week',
  ARRAY['Camera rental', 'Video production'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Cinema Lens Set (Prime)',
  'cinema-lens-set-prime',
  'Professional cinema prime lens set',
  'Set of 5 prime lenses: 24mm, 35mm, 50mm, 85mm, 135mm, T1.5, EF mount',
  'set',
  ARRAY['Prime Lenses', 'Cinema Lenses', 'Lens Set'],
  ARRAY['cinema', 'lens', 'prime', 'set', 'ef', 'mount'],
  ARRAY['video', 'lens', 'cinema'],
  'Rokinon',
  'Xeen CF',
  NULL,
  2,
  '$200-400 per day',
  '2 weeks',
  ARRAY['Camera rental', 'Lens rental'],
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Zoom Lens (24-70mm)',
  'zoom-lens-24-70mm',
  'Professional zoom lens for cinema',
  '24-70mm T2.9, cinema-style zoom, EF mount, parfocal',
  'each',
  ARRAY['Zoom Lens', 'Cinema Zoom', 'Standard Zoom'],
  ARRAY['zoom', 'lens', '24-70', 'cinema', 'ef'],
  ARRAY['video', 'lens', 'zoom'],
  'Canon',
  'CN-E 24-70mm T2.9',
  NULL,
  2,
  '$150-300 per day',
  '1 week',
  ARRAY['Camera rental', 'Lens rental'],
  true,
  true,
  7
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Tripod (Heavy Duty)',
  'tripod-heavy-duty',
  'Professional heavy-duty video tripod',
  'Carbon fiber legs, fluid head, 100mm bowl, 55lb capacity',
  'each',
  ARRAY['Video Tripod', 'Camera Tripod', 'Fluid Head'],
  ARRAY['tripod', 'video', 'heavy', 'duty', 'fluid', 'head'],
  ARRAY['video', 'support', 'tripod'],
  'Sachtler',
  'System FSB 10',
  NULL,
  6,
  '$50-100 per day',
  '1 week',
  ARRAY['Camera rental', 'Video production'],
  true,
  true,
  8
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Camera Jib (12 ft)',
  'camera-jib-12ft',
  '12-foot camera jib arm',
  'Carbon fiber jib, 12ft reach, fluid head, counterweight system',
  'each',
  ARRAY['Jib', 'Crane', 'Jib Arm', 'Camera Crane'],
  ARRAY['jib', 'crane', 'arm', '12', 'feet', 'camera'],
  ARRAY['video', 'support', 'jib'],
  'Kessler',
  'Crane System',
  NULL,
  2,
  '$150-300 per day',
  '2 weeks',
  ARRAY['Camera rental', 'Video production'],
  true,
  true,
  9
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Camera Slider (4 ft)',
  'camera-slider-4ft',
  '4-foot motorized camera slider',
  'Motorized slider, 4ft travel, time-lapse capable, app control',
  'each',
  ARRAY['Slider', 'Camera Dolly', 'Track', 'Motorized Slider'],
  ARRAY['slider', 'camera', 'motorized', '4', 'feet', 'dolly'],
  ARRAY['video', 'support', 'slider'],
  'Rhino',
  'ROV Pro',
  'Battery',
  2,
  '$75-150 per day',
  '1 week',
  ARRAY['Camera rental', 'Video production'],
  true,
  true,
  10
);

-- ============================================================================
-- TECHNICAL PRODUCTION - VIDEO MONITORS & RECORDERS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, dimensions, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Production Monitor (17" HD)',
  'production-monitor-17-hd',
  '17-inch HD production monitor',
  '17" 1920x1080, SDI/HDMI input, waveform/vectorscope, rack mountable',
  'each',
  ARRAY['Video Monitor', 'Production Monitor', 'Broadcast Monitor'],
  ARRAY['monitor', 'video', '17', 'hd', 'production', 'sdi'],
  ARRAY['video', 'monitor', 'display'],
  'Blackmagic Design',
  'SmartView HD',
  '17" diagonal',
  '12V DC',
  4,
  '$50-100 per day',
  '1 week',
  ARRAY['Video production rental', 'Broadcast rental'],
  true,
  true,
  11
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Field Monitor (7" 4K)',
  'field-monitor-7-4k',
  '7-inch 4K field monitor with HDR',
  '7" 1920x1200, 4K HDMI, HDR support, waveform, false color, battery powered',
  'each',
  ARRAY['Field Monitor', 'Camera Monitor', 'On-Camera Monitor'],
  ARRAY['field', 'monitor', '7', '4k', 'camera', 'hdr'],
  ARRAY['video', 'monitor', 'field'],
  'Atomos',
  'Shinobi',
  '7" diagonal',
  'Battery or DC',
  6,
  '$40-80 per day',
  '1 week',
  ARRAY['Camera rental', 'Video production'],
  true,
  true,
  12
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Video Recorder (4K)',
  'video-recorder-4k',
  '4K video recorder with SSD recording',
  '4K 60p recording, ProRes/DNxHD, HDMI/SDI I/O, SSD media',
  'each',
  ARRAY['Video Recorder', 'Capture Device', 'Field Recorder'],
  ARRAY['recorder', 'video', '4k', 'prores', 'ssd', 'capture'],
  ARRAY['video', 'recorder', 'capture'],
  'Atomos',
  'Ninja V',
  '5" diagonal',
  'Battery or DC',
  4,
  '$75-150 per day',
  '1 week',
  ARRAY['Camera rental', 'Video production'],
  true,
  true,
  13
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Multiviewer (16-input)',
  'multiviewer-16-input',
  '16-input HD multiviewer',
  '16x HD-SDI inputs, HDMI output, audio meters, tally, UMD labels',
  'each',
  ARRAY['Multiviewer', 'Multi-view', 'Video Wall'],
  ARRAY['multiviewer', 'multi', 'view', '16', 'input', 'sdi'],
  ARRAY['video', 'monitor', 'multiviewer'],
  'Blackmagic Design',
  'MultiView 16',
  '19" rack, 1U',
  '12V DC',
  2,
  '$75-150 per day',
  '1 week',
  ARRAY['Video production rental', 'Broadcast rental'],
  true,
  true,
  14
);

-- ============================================================================
-- TECHNICAL PRODUCTION - VIDEO SWITCHERS & PROCESSING
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, dimensions, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Video Switcher (12-input 4K)',
  'video-switcher-12-input-4k',
  '12-input 4K video production switcher',
  '12x 12G-SDI inputs, 4K 60p, DVE, chroma key, streaming, recording',
  'each',
  ARRAY['Video Switcher', 'Vision Mixer', 'Production Switcher'],
  ARRAY['switcher', 'video', '12', 'input', '4k', 'production'],
  ARRAY['video', 'switcher', 'production'],
  'Blackmagic Design',
  'ATEM 2 M/E Constellation 4K',
  '19" rack, 4U',
  '100-240V',
  1,
  '$300-600 per day',
  '2 weeks',
  ARRAY['Video production rental', 'Broadcast rental'],
  true,
  true,
  15
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Video Switcher (4-input HD)',
  'video-switcher-4-input-hd',
  'Compact 4-input HD video switcher',
  '4x HDMI inputs, HD 1080p, transitions, chroma key, streaming',
  'each',
  ARRAY['Video Switcher', 'Compact Switcher', 'HDMI Switcher'],
  ARRAY['switcher', 'video', '4', 'input', 'hd', 'hdmi'],
  ARRAY['video', 'switcher', 'compact'],
  'Blackmagic Design',
  'ATEM Mini Pro',
  'Desktop unit',
  '12V DC',
  3,
  '$75-150 per day',
  '1 week',
  ARRAY['Video production rental', 'AV rental'],
  true,
  true,
  16
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Video Scaler/Converter',
  'video-scaler-converter',
  'Multi-format video scaler and converter',
  'SDI/HDMI I/O, 4K scaling, frame rate conversion, format conversion',
  'each',
  ARRAY['Video Scaler', 'Format Converter', 'Video Processor'],
  ARRAY['scaler', 'converter', 'video', 'format', '4k', 'processor'],
  ARRAY['video', 'processing', 'scaler'],
  'AJA',
  'FS4',
  '19" rack, 1U',
  '100-240V',
  4,
  '$75-150 per day',
  '1 week',
  ARRAY['Video production rental', 'Broadcast rental'],
  true,
  true,
  17
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'LED Video Wall (500mm Panel)',
  'led-video-wall-500mm-panel',
  '500mm x 500mm LED video panel',
  '3.9mm pixel pitch, 1000 nits, indoor/outdoor, modular, touring-grade',
  'panel',
  ARRAY['LED Wall', 'Video Wall', 'LED Panel', 'Video Screen'],
  ARRAY['led', 'video', 'wall', 'panel', '500mm', 'screen'],
  ARRAY['video', 'led', 'display'],
  'ROE Visual',
  'Black Onyx',
  '500mm x 500mm',
  '100-240V',
  50,
  '$100-200 per panel/day',
  '4 weeks',
  ARRAY['LED rental', 'Video production', 'Staging companies'],
  true,
  true,
  18
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'LED Video Processor',
  'led-video-processor',
  'LED video wall processor',
  '4K input, multi-layer processing, scaling, windowing, Genlock',
  'each',
  ARRAY['Video Processor', 'LED Processor', 'Wall Processor'],
  ARRAY['led', 'processor', 'video', 'wall', '4k', 'scaling'],
  ARRAY['video', 'led', 'processing'],
  'Barco',
  'E2',
  '19" rack, 4U',
  '100-240V',
  2,
  '$200-400 per day',
  '2 weeks',
  ARRAY['LED rental', 'Video production'],
  true,
  true,
  19
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'video'),
  'Projector (10K Lumens)',
  'projector-10k-lumens',
  '10,000-lumen laser projector',
  '10,000 lumens, WUXGA, laser light source, lens shift, HDBaseT',
  'each',
  ARRAY['Projector', 'Video Projector', 'Laser Projector'],
  ARRAY['projector', '10k', 'lumens', 'laser', 'wuxga', 'video'],
  ARRAY['video', 'projector', 'display'],
  'Panasonic',
  'PT-RZ10K',
  'Large format',
  '100-240V',
  4,
  '$300-600 per day',
  '2 weeks',
  ARRAY['AV rental', 'Video production'],
  true,
  true,
  20
);

-- ============================================================================
-- TECHNICAL PRODUCTION - BROADCAST EQUIPMENT
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'broadcast'),
  'Streaming Encoder (4K)',
  'streaming-encoder-4k',
  '4K streaming encoder with dual outputs',
  '4K HEVC encoding, dual streaming, RTMP/SRT, SDI/HDMI input',
  'each',
  ARRAY['Encoder', 'Streaming Encoder', 'Video Encoder'],
  ARRAY['encoder', 'streaming', '4k', 'rtmp', 'srt', 'hevc'],
  ARRAY['broadcast', 'streaming', 'encoder'],
  'Teradek',
  'Prism Flex',
  '12V DC',
  2,
  '$150-300 per day',
  '1 week',
  ARRAY['Broadcast rental', 'Streaming services'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'broadcast'),
  'Wireless Video System (HD)',
  'wireless-video-system-hd',
  'HD wireless video transmission system',
  'HD-SDI/HDMI, 300ft range, zero latency, encrypted',
  'system',
  ARRAY['Wireless Video', 'Video TX/RX', 'Wireless Transmission'],
  ARRAY['wireless', 'video', 'transmission', 'hd', 'teradek'],
  ARRAY['broadcast', 'wireless', 'video'],
  'Teradek',
  'Bolt 500 XT',
  'Battery or DC',
  3,
  '$100-200 per day',
  '1 week',
  ARRAY['Camera rental', 'Broadcast rental'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'broadcast'),
  'Teleprompter (17" On-Camera)',
  'teleprompter-17-on-camera',
  '17-inch on-camera teleprompter',
  '17" high-bright LCD, 70/30 beamsplitter glass, software included',
  'each',
  ARRAY['Teleprompter', 'Autocue', 'Prompter'],
  ARRAY['teleprompter', 'prompter', '17', 'camera', 'autocue'],
  ARRAY['broadcast', 'teleprompter', 'production'],
  'Autocue',
  'QStart',
  '12V DC',
  3,
  '$75-150 per day',
  '1 week',
  ARRAY['Camera rental', 'Broadcast rental'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'broadcast'),
  'Teleprompter (Presidential)',
  'teleprompter-presidential',
  'Presidential glass teleprompter pair',
  'Pair of glass prompters on stands, software, operator station',
  'set',
  ARRAY['Presidential Prompter', 'Glass Prompter', 'Speech Prompter'],
  ARRAY['teleprompter', 'presidential', 'glass', 'speech', 'prompter'],
  ARRAY['broadcast', 'teleprompter', 'speech'],
  'Autocue',
  'Presidential',
  '12V DC',
  1,
  '$200-400 per day',
  '2 weeks',
  ARRAY['AV rental', 'Broadcast rental'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'broadcast'),
  'Video Router (12x12)',
  'video-router-12x12',
  '12x12 SDI video router',
  '12 inputs, 12 outputs, 12G-SDI, 4K support, control panel',
  'each',
  ARRAY['Video Router', 'SDI Router', 'Matrix Switcher'],
  ARRAY['router', 'video', 'sdi', '12x12', 'matrix', '4k'],
  ARRAY['broadcast', 'router', 'distribution'],
  'Blackmagic Design',
  'Videohub 12x12',
  '100-240V',
  2,
  '$100-200 per day',
  '1 week',
  ARRAY['Broadcast rental', 'Video production'],
  true,
  true,
  5
);

COMMIT;
