-- ============================================================================
-- CATALOG - IT/CONNECTIVITY & SUPPLIES (Comprehensive)
-- Network equipment, WiFi, cables, and consumable supplies
-- ============================================================================

BEGIN;

-- ============================================================================
-- SITE SERVICES - IT & CONNECTIVITY
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  make, model, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'WiFi Access Point (Enterprise)',
  'wifi-access-point-enterprise',
  'Enterprise-grade WiFi 6 access point',
  'WiFi 6 (802.11ax), dual-band, PoE+, 2.5Gbps, cloud managed',
  'each',
  ARRAY['WiFi AP', 'Access Point', 'Wireless AP', 'WiFi 6'],
  ARRAY['wifi', 'access', 'point', 'wireless', 'ap', '802.11ax'],
  ARRAY['it', 'network', 'wifi'],
  'Ubiquiti',
  'UniFi 6 Enterprise',
  'PoE+ (802.3at)',
  20,
  '$30-60 per day',
  '1 week',
  ARRAY['IT rental', 'Network services', 'AV rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'Network Switch (24-port PoE+)',
  'network-switch-24-port-poe',
  '24-port gigabit PoE+ managed switch',
  '24x 1Gbps PoE+ ports, 2x 10Gbps SFP+, 400W PoE budget, managed',
  'each',
  ARRAY['Network Switch', 'PoE Switch', 'Ethernet Switch'],
  ARRAY['switch', 'network', 'poe', '24', 'port', 'gigabit'],
  ARRAY['it', 'network', 'switch'],
  'Ubiquiti',
  'UniFi Switch Pro 24 PoE',
  '100-240V',
  8,
  '$40-80 per day',
  '1 week',
  ARRAY['IT rental', 'Network services'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'Network Switch (48-port)',
  'network-switch-48-port',
  '48-port gigabit managed switch',
  '48x 1Gbps ports, 4x 10Gbps SFP+, Layer 3, managed',
  'each',
  ARRAY['Network Switch', 'Core Switch', 'Ethernet Switch'],
  ARRAY['switch', 'network', '48', 'port', 'gigabit', 'core'],
  ARRAY['it', 'network', 'switch'],
  'Cisco',
  'Catalyst 9300',
  '100-240V',
  4,
  '$75-150 per day',
  '2 weeks',
  ARRAY['IT rental', 'Network services'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'Router (Enterprise)',
  'router-enterprise',
  'Enterprise-grade router with firewall',
  'Multi-WAN, VPN, firewall, 1Gbps throughput, cloud managed',
  'each',
  ARRAY['Router', 'Gateway', 'Firewall', 'Network Router'],
  ARRAY['router', 'gateway', 'firewall', 'enterprise', 'vpn'],
  ARRAY['it', 'network', 'router'],
  'Ubiquiti',
  'UniFi Dream Machine Pro',
  '100-240V',
  4,
  '$50-100 per day',
  '1 week',
  ARRAY['IT rental', 'Network services'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'Ethernet Cable (Cat6, 100 ft)',
  'ethernet-cable-cat6-100ft',
  '100-foot Cat6 Ethernet cable',
  'Cat6, 23AWG, shielded, RJ45 connectors, 100ft',
  'each',
  ARRAY['Network Cable', 'Ethernet Cable', 'Cat6 Cable'],
  ARRAY['ethernet', 'cable', 'cat6', '100', 'feet', 'network'],
  ARRAY['it', 'cable', 'network'],
  'Monoprice',
  'Cat6 Shielded',
  NULL,
  50,
  '$5-12 per day',
  '3 days',
  ARRAY['IT rental', 'Cable suppliers'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'Ethernet Cable (Cat6, 50 ft)',
  'ethernet-cable-cat6-50ft',
  '50-foot Cat6 Ethernet cable',
  'Cat6, 23AWG, shielded, RJ45 connectors, 50ft',
  'each',
  ARRAY['Network Cable', 'Ethernet Cable', 'Cat6 Cable'],
  ARRAY['ethernet', 'cable', 'cat6', '50', 'feet', 'network'],
  ARRAY['it', 'cable', 'network'],
  'Monoprice',
  'Cat6 Shielded',
  NULL,
  100,
  '$3-8 per day',
  '3 days',
  ARRAY['IT rental', 'Cable suppliers'],
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'Fiber Optic Cable (Single-mode, 100m)',
  'fiber-optic-cable-sm-100m',
  '100-meter single-mode fiber cable',
  'Single-mode OS2, LC-LC duplex, 100m, outdoor rated',
  'each',
  ARRAY['Fiber Cable', 'Fiber Optic', 'LC Cable'],
  ARRAY['fiber', 'optic', 'cable', 'single', 'mode', 'lc', '100m'],
  ARRAY['it', 'cable', 'fiber'],
  'Corning',
  'ClearCurve',
  NULL,
  20,
  '$15-30 per day',
  '1 week',
  ARRAY['IT rental', 'Fiber specialists'],
  true,
  true,
  7
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'Cellular Booster/Repeater',
  'cellular-booster-repeater',
  'Cellular signal booster for events',
  'Multi-carrier, 4G/5G, covers 10,000 sq ft, FCC approved',
  'each',
  ARRAY['Cell Booster', 'Signal Booster', 'Cell Repeater'],
  ARRAY['cellular', 'booster', 'repeater', 'signal', '4g', '5g'],
  ARRAY['it', 'cellular', 'connectivity'],
  'WilsonPro',
  'Enterprise 4300',
  '100-240V',
  3,
  '$100-200 per day',
  '2 weeks',
  ARRAY['IT rental', 'Cellular services'],
  true,
  true,
  8
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'Internet Service (Dedicated Fiber)',
  'internet-service-fiber',
  'Dedicated fiber internet connection',
  'Dedicated fiber, symmetrical speeds, SLA, installation included',
  'event',
  ARRAY['Fiber Internet', 'Dedicated Internet', 'Fiber Connection'],
  ARRAY['internet', 'fiber', 'dedicated', 'connection', 'isp'],
  ARRAY['it', 'internet', 'connectivity'],
  'Various ISPs',
  NULL,
  NULL,
  1,
  '$1000-5000 per event',
  '4 weeks',
  ARRAY['ISPs', 'Telecom providers'],
  true,
  true,
  9
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'Bonded Cellular Router',
  'bonded-cellular-router',
  'Multi-SIM bonded cellular router',
  '8x SIM slots, load balancing, failover, VPN, cloud managed',
  'each',
  ARRAY['Cellular Router', 'Bonded Router', 'Multi-SIM Router'],
  ARRAY['bonded', 'cellular', 'router', 'multi', 'sim', 'failover'],
  ARRAY['it', 'cellular', 'router'],
  'Peplink',
  'MAX Transit Duo',
  '12V DC',
  2,
  '$100-200 per day',
  '1 week',
  ARRAY['IT rental', 'Cellular services'],
  true,
  true,
  10
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-services'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'it-connectivity'),
  'Network Rack (12U Mobile)',
  'network-rack-12u-mobile',
  '12U mobile network equipment rack',
  '12U rack mount, wheels, cable management, power strip',
  'each',
  ARRAY['Network Rack', 'Server Rack', 'Equipment Rack'],
  ARRAY['rack', 'network', '12u', 'mobile', 'server', 'equipment'],
  ARRAY['it', 'rack', 'infrastructure'],
  'Middle Atlantic',
  'Mobile Rack',
  NULL,
  4,
  '$30-60 per day',
  '1 week',
  ARRAY['IT rental', 'AV rental'],
  true,
  true,
  11
);

-- ============================================================================
-- SITE ASSETS - SUPPLIES (CONSUMABLES)
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  typical_quantity, estimated_cost, lead_time,
  is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Gaff Tape (2" x 55yd)',
  'gaff-tape-2in-55yd',
  '2-inch gaff tape roll',
  'Matte black gaff tape, 2" x 55 yards, cloth backing, residue-free',
  'roll',
  ARRAY['Gaff Tape', 'Gaffer Tape', 'Stage Tape'],
  ARRAY['gaff', 'tape', 'gaffer', '2', 'inch', 'black'],
  ARRAY['supplies', 'tape', 'consumable'],
  100,
  '$8-15 per roll',
  '3 days',
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Spike Tape (1/2" x 45yd)',
  'spike-tape-half-in-45yd',
  '1/2-inch spike tape roll',
  'Fluorescent spike tape, 1/2" x 45 yards, various colors',
  'roll',
  ARRAY['Spike Tape', 'Marking Tape', 'Floor Tape'],
  ARRAY['spike', 'tape', 'marking', 'floor', 'fluorescent'],
  ARRAY['supplies', 'tape', 'consumable'],
  50,
  '$5-10 per roll',
  '3 days',
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Duct Tape (2" x 60yd)',
  'duct-tape-2in-60yd',
  '2-inch duct tape roll',
  'Heavy-duty duct tape, 2" x 60 yards, silver',
  'roll',
  ARRAY['Duct Tape', 'Duck Tape', 'Utility Tape'],
  ARRAY['duct', 'tape', 'silver', '2', 'inch', 'heavy', 'duty'],
  ARRAY['supplies', 'tape', 'consumable'],
  50,
  '$5-10 per roll',
  '3 days',
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Zip Ties (Assorted)',
  'zip-ties-assorted',
  'Assorted zip ties pack',
  'Cable ties, various sizes (4", 8", 12", 18"), UV resistant, 100-pack',
  'pack',
  ARRAY['Zip Ties', 'Cable Ties', 'Tie Wraps'],
  ARRAY['zip', 'ties', 'cable', 'tie', 'wraps', 'assorted'],
  ARRAY['supplies', 'cable management', 'consumable'],
  50,
  '$8-15 per pack',
  '3 days',
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Velcro Cable Ties (50-pack)',
  'velcro-cable-ties-50-pack',
  'Reusable velcro cable ties',
  'Hook and loop cable ties, 8" length, reusable, 50-pack',
  'pack',
  ARRAY['Velcro Ties', 'Cable Wraps', 'Hook and Loop'],
  ARRAY['velcro', 'cable', 'ties', 'hook', 'loop', 'reusable'],
  ARRAY['supplies', 'cable management', 'reusable'],
  30,
  '$10-20 per pack',
  '3 days',
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Sharpies (Assorted Colors, 12-pack)',
  'sharpies-assorted-12-pack',
  'Permanent markers assorted colors',
  'Sharpie permanent markers, fine point, assorted colors, 12-pack',
  'pack',
  ARRAY['Sharpies', 'Markers', 'Permanent Markers'],
  ARRAY['sharpie', 'marker', 'permanent', 'assorted', 'colors'],
  ARRAY['supplies', 'writing', 'consumable'],
  20,
  '$8-15 per pack',
  '3 days',
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Batteries (AA, 24-pack)',
  'batteries-aa-24-pack',
  'AA alkaline batteries',
  'AA alkaline batteries, 24-pack, long-lasting',
  'pack',
  ARRAY['AA Batteries', 'Batteries', 'Alkaline Batteries'],
  ARRAY['batteries', 'aa', 'alkaline', '24', 'pack'],
  ARRAY['supplies', 'batteries', 'consumable'],
  30,
  '$10-20 per pack',
  '3 days',
  true,
  true,
  7
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Batteries (AAA, 24-pack)',
  'batteries-aaa-24-pack',
  'AAA alkaline batteries',
  'AAA alkaline batteries, 24-pack, long-lasting',
  'pack',
  ARRAY['AAA Batteries', 'Batteries', 'Alkaline Batteries'],
  ARRAY['batteries', 'aaa', 'alkaline', '24', 'pack'],
  ARRAY['supplies', 'batteries', 'consumable'],
  30,
  '$10-20 per pack',
  '3 days',
  true,
  true,
  8
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Batteries (9V, 12-pack)',
  'batteries-9v-12-pack',
  '9V alkaline batteries',
  '9V alkaline batteries, 12-pack, for wireless mics and equipment',
  'pack',
  ARRAY['9V Batteries', 'Batteries', 'Alkaline Batteries'],
  ARRAY['batteries', '9v', 'alkaline', '12', 'pack', 'wireless'],
  ARRAY['supplies', 'batteries', 'consumable'],
  20,
  '$15-30 per pack',
  '3 days',
  true,
  true,
  9
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Trash Bags (55-gallon, 100-pack)',
  'trash-bags-55-gallon-100-pack',
  'Heavy-duty trash bags',
  '55-gallon trash bags, heavy-duty, black, 100-pack',
  'pack',
  ARRAY['Trash Bags', 'Garbage Bags', 'Waste Bags'],
  ARRAY['trash', 'bags', 'garbage', '55', 'gallon', 'heavy', 'duty'],
  ARRAY['supplies', 'waste', 'consumable'],
  20,
  '$20-40 per pack',
  '3 days',
  true,
  true,
  10
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Ice (20 lb bag)',
  'ice-20-lb-bag',
  '20-pound bag of ice',
  'Bagged ice, 20 lbs, for coolers and beverage service',
  'bag',
  ARRAY['Ice', 'Bagged Ice', 'Cooler Ice'],
  ARRAY['ice', 'bag', '20', 'pound', 'cooler', 'beverage'],
  ARRAY['supplies', 'hospitality', 'consumable'],
  100,
  '$5-10 per bag',
  '1 day',
  true,
  true,
  11
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Bottled Water (24-pack)',
  'bottled-water-24-pack',
  'Bottled water case',
  'Bottled water, 16.9 oz bottles, 24-pack case',
  'case',
  ARRAY['Water', 'Bottled Water', 'Drinking Water'],
  ARRAY['water', 'bottled', 'drinking', '24', 'pack', 'case'],
  ARRAY['supplies', 'hospitality', 'consumable'],
  50,
  '$8-15 per case',
  '1 day',
  true,
  true,
  12
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Paper Towels (12-roll pack)',
  'paper-towels-12-roll-pack',
  'Paper towel rolls',
  'Paper towels, 2-ply, 12-roll pack',
  'pack',
  ARRAY['Paper Towels', 'Towels', 'Cleaning Supplies'],
  ARRAY['paper', 'towels', 'cleaning', '12', 'roll', 'pack'],
  ARRAY['supplies', 'cleaning', 'consumable'],
  15,
  '$15-30 per pack',
  '3 days',
  true,
  true,
  13
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Extension Cord (50 ft, 12/3)',
  'extension-cord-50ft-household',
  '50-foot household extension cord',
  'Heavy-duty extension cord, 12/3 SJTW, 15A, lighted ends, 50ft',
  'each',
  ARRAY['Extension Cord', 'Power Cord', 'Extension Cable'],
  ARRAY['extension', 'cord', 'power', '50', 'feet', '12', '3'],
  ARRAY['supplies', 'power', 'cable'],
  40,
  '$5-12 per day',
  '3 days',
  true,
  true,
  14
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'supplies'),
  'Multi-Outlet Power Strip (6-outlet)',
  'power-strip-6-outlet',
  '6-outlet surge protector power strip',
  '6 outlets, surge protection, 6ft cord, circuit breaker',
  'each',
  ARRAY['Power Strip', 'Surge Protector', 'Outlet Strip'],
  ARRAY['power', 'strip', 'surge', 'protector', '6', 'outlet'],
  ARRAY['supplies', 'power', 'electrical'],
  50,
  '$5-10 per day',
  '3 days',
  true,
  true,
  15
);

COMMIT;
