-- ============================================================================
-- CATALOG - CROWD CONTROL, SIGNAGE & ACCESSIBILITY (Comprehensive)
-- Barriers, stanchions, signs, wayfinding, and accessibility equipment
-- ============================================================================

BEGIN;

-- ============================================================================
-- SITE ASSETS - CROWD CONTROL
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  dimensions, weight,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'crowd-control'),
  'Bike Rack Barricade (8 ft)',
  'bike-rack-barricade-8ft',
  '8-foot steel bike rack barricade',
  'Heavy-duty steel construction, interlocking, powder-coated finish, 8ft length',
  'each',
  ARRAY['Bike Rack', 'Barricade', 'Crowd Barrier', 'Steel Barrier'],
  ARRAY['bike', 'rack', 'barricade', 'barrier', '8', 'feet', 'steel'],
  ARRAY['crowd control', 'barrier', 'safety'],
  '8 ft x 4 ft',
  '50 lbs',
  200,
  '$8-15 per day',
  '1 week',
  ARRAY['Event rental', 'Staging companies', 'Crowd control'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'crowd-control'),
  'Stanchion with Retractable Belt',
  'stanchion-retractable-belt',
  'Stanchion with retractable belt',
  'Chrome or black finish, 11ft retractable belt, weighted base, stackable',
  'each',
  ARRAY['Stanchion', 'Queue Post', 'Rope Post', 'Belt Barrier'],
  ARRAY['stanchion', 'retractable', 'belt', 'queue', 'post', 'rope'],
  ARRAY['crowd control', 'queue', 'barrier'],
  '38" height',
  '25 lbs',
  100,
  '$5-12 per day',
  '3 days',
  ARRAY['Event rental', 'Party rental'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'crowd-control'),
  'Stanchion with Velvet Rope',
  'stanchion-velvet-rope',
  'VIP stanchion with velvet rope',
  'Polished brass or chrome, red velvet rope, weighted base, 6ft rope',
  'each',
  ARRAY['Stanchion', 'VIP Post', 'Rope Post', 'Velvet Rope'],
  ARRAY['stanchion', 'velvet', 'rope', 'vip', 'post', 'brass'],
  ARRAY['crowd control', 'vip', 'queue'],
  '38" height',
  '30 lbs',
  50,
  '$8-15 per day',
  '3 days',
  ARRAY['Event rental', 'Party rental'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'crowd-control'),
  'Plastic Crowd Control Barrier',
  'plastic-crowd-control-barrier',
  'Interlocking plastic crowd barrier',
  'HDPE plastic, water-fillable, interlocking, UV resistant, 6ft length',
  'each',
  ARRAY['Plastic Barrier', 'Water Barrier', 'Jersey Barrier'],
  ARRAY['plastic', 'barrier', 'crowd', 'control', 'water', 'fillable'],
  ARRAY['crowd control', 'barrier', 'plastic'],
  '6 ft x 3 ft',
  '35 lbs empty',
  100,
  '$10-20 per day',
  '1 week',
  ARRAY['Event rental', 'Construction rental'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'crowd-control'),
  'Traffic Cone (28" with reflective collar)',
  'traffic-cone-28-reflective',
  '28-inch traffic cone with reflective collar',
  'Orange PVC, 28" height, reflective collar, weighted base',
  'each',
  ARRAY['Traffic Cone', 'Safety Cone', 'Road Cone'],
  ARRAY['traffic', 'cone', 'safety', '28', 'inch', 'reflective'],
  ARRAY['crowd control', 'safety', 'traffic'],
  '28" height',
  '10 lbs',
  200,
  '$2-5 per day',
  '3 days',
  ARRAY['Event rental', 'Safety equipment'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'crowd-control'),
  'Retractable Belt Barrier (Wall Mount)',
  'retractable-belt-barrier-wall',
  'Wall-mounted retractable belt barrier',
  'Wall-mounted cassette, 13ft retractable belt, various colors',
  'each',
  ARRAY['Belt Barrier', 'Wall Mount Barrier', 'Retractable Belt'],
  ARRAY['retractable', 'belt', 'barrier', 'wall', 'mount', 'cassette'],
  ARRAY['crowd control', 'queue', 'wall mount'],
  '13 ft belt',
  '5 lbs',
  40,
  '$8-15 per day',
  '1 week',
  ARRAY['Event rental', 'Queue management'],
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-assets'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'crowd-control'),
  'Queue Management System (Digital)',
  'queue-management-system-digital',
  'Digital queue management system',
  'Digital display, ticket dispenser, call system, software included',
  'system',
  ARRAY['Queue System', 'Ticket System', 'Queue Management'],
  ARRAY['queue', 'management', 'system', 'digital', 'ticket', 'display'],
  ARRAY['crowd control', 'queue', 'digital'],
  'Complete system',
  NULL,
  2,
  '$150-300 per day',
  '2 weeks',
  ARRAY['Queue management', 'AV rental'],
  true,
  true,
  7
);

-- ============================================================================
-- SITE INFRASTRUCTURE - SIGNAGE & WAYFINDING
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  dimensions, material,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'signage-wayfinding'),
  'A-Frame Sign (24" x 36")',
  'a-frame-sign-24x36',
  'Double-sided A-frame sidewalk sign',
  'Metal frame, double-sided, 24" x 36" insert area, weather resistant',
  'each',
  ARRAY['A-Frame', 'Sidewalk Sign', 'Sandwich Board', 'A-Board'],
  ARRAY['a-frame', 'sign', 'sidewalk', 'sandwich', 'board', '24x36'],
  ARRAY['signage', 'wayfinding', 'display'],
  '24" x 36"',
  'Metal frame',
  30,
  '$10-20 per day',
  '3 days',
  ARRAY['Event rental', 'Sign companies'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'signage-wayfinding'),
  'Directional Sign Post with Arms',
  'directional-sign-post-arms',
  'Directional sign post with multiple arms',
  'Metal post with 4-6 directional arms, custom graphics, ground stake',
  'each',
  ARRAY['Directional Sign', 'Way Finding Post', 'Arrow Sign'],
  ARRAY['directional', 'sign', 'post', 'wayfinding', 'arrow', 'arms'],
  ARRAY['signage', 'wayfinding', 'directional'],
  '6 ft height',
  'Metal',
  20,
  '$25-50 per day',
  '1 week',
  ARRAY['Event rental', 'Sign companies'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'signage-wayfinding'),
  'Banner Stand (Retractable, 33" x 80")',
  'banner-stand-retractable-33x80',
  'Retractable banner stand',
  'Retractable banner stand, 33" x 80", aluminum base, carrying case',
  'each',
  ARRAY['Banner Stand', 'Roll-Up Banner', 'Retractable Stand'],
  ARRAY['banner', 'stand', 'retractable', 'roll-up', '33x80'],
  ARRAY['signage', 'banner', 'display'],
  '33" x 80"',
  'Aluminum',
  40,
  '$15-30 per day',
  '3 days',
  ARRAY['Event rental', 'Display rental'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'signage-wayfinding'),
  'Vinyl Banner (Custom, 4 ft x 8 ft)',
  'vinyl-banner-4x8-custom',
  'Custom vinyl banner',
  'Full-color vinyl banner, 4 ft x 8 ft, grommets, weather resistant',
  'each',
  ARRAY['Vinyl Banner', 'Custom Banner', 'Outdoor Banner'],
  ARRAY['vinyl', 'banner', 'custom', '4x8', 'outdoor', 'grommets'],
  ARRAY['signage', 'banner', 'vinyl'],
  '4 ft x 8 ft',
  'Vinyl',
  30,
  '$30-60 per day',
  '1 week',
  ARRAY['Print shops', 'Sign companies'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'signage-wayfinding'),
  'Feather Flag (12 ft with base)',
  'feather-flag-12ft-base',
  'Feather flag with ground spike or base',
  'Teardrop/feather flag, 12 ft height, custom graphics, ground spike or water base',
  'each',
  ARRAY['Feather Flag', 'Teardrop Flag', 'Swooper Flag'],
  ARRAY['feather', 'flag', 'teardrop', 'swooper', '12', 'feet'],
  ARRAY['signage', 'flag', 'outdoor'],
  '12 ft height',
  'Fabric',
  25,
  '$20-40 per day',
  '1 week',
  ARRAY['Event rental', 'Flag companies'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'signage-wayfinding'),
  'Digital Signage Display (43" LCD)',
  'digital-signage-43-lcd',
  '43-inch digital signage display',
  '43" commercial LCD, 1920x1080, media player included, portrait/landscape',
  'each',
  ARRAY['Digital Sign', 'LCD Display', 'Digital Screen'],
  ARRAY['digital', 'signage', 'display', '43', 'lcd', 'screen'],
  ARRAY['signage', 'digital', 'display'],
  '43" diagonal',
  'LCD',
  15,
  '$75-150 per day',
  '1 week',
  ARRAY['AV rental', 'Digital signage'],
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'signage-wayfinding'),
  'Floor Decal (Custom)',
  'floor-decal-custom',
  'Custom floor decal/sticker',
  'Vinyl floor decal, custom size/design, slip-resistant laminate',
  'each',
  ARRAY['Floor Decal', 'Floor Sticker', 'Floor Graphic'],
  ARRAY['floor', 'decal', 'sticker', 'graphic', 'vinyl', 'custom'],
  ARRAY['signage', 'floor', 'decal'],
  'Custom size',
  'Vinyl',
  50,
  '$20-50 per decal',
  '1 week',
  ARRAY['Print shops', 'Sign companies'],
  true,
  true,
  7
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'signage-wayfinding'),
  'Emergency Exit Sign (LED)',
  'emergency-exit-sign-led',
  'LED emergency exit sign',
  'LED exit sign, battery backup, UL listed, red or green',
  'each',
  ARRAY['Exit Sign', 'Emergency Sign', 'Safety Sign'],
  ARRAY['exit', 'sign', 'emergency', 'led', 'safety', 'battery'],
  ARRAY['signage', 'emergency', 'safety'],
  'Standard size',
  'Plastic/LED',
  40,
  '$10-20 per day',
  '3 days',
  ARRAY['Safety equipment', 'Electrical rental'],
  true,
  true,
  8
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'signage-wayfinding'),
  'Yard Sign (18" x 24" with stake)',
  'yard-sign-18x24-stake',
  'Corrugated plastic yard sign with stake',
  'Coroplast yard sign, 18" x 24", H-stake included, custom graphics',
  'each',
  ARRAY['Yard Sign', 'Lawn Sign', 'Coroplast Sign'],
  ARRAY['yard', 'sign', 'lawn', 'coroplast', '18x24', 'stake'],
  ARRAY['signage', 'outdoor', 'yard'],
  '18" x 24"',
  'Coroplast',
  100,
  '$5-10 per day',
  '3 days',
  ARRAY['Print shops', 'Sign companies'],
  true,
  true,
  9
);

-- ============================================================================
-- SITE INFRASTRUCTURE - ACCESSIBILITY
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  dimensions, capacity,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'accessibility'),
  'ADA Ramp (Modular, 8 ft)',
  'ada-ramp-modular-8ft',
  'Modular ADA-compliant wheelchair ramp',
  'Aluminum modular ramp, 8 ft length, 36" wide, ADA compliant, non-slip',
  'section',
  ARRAY['Wheelchair Ramp', 'ADA Ramp', 'Accessibility Ramp'],
  ARRAY['ada', 'ramp', 'wheelchair', 'accessibility', 'modular', '8ft'],
  ARRAY['accessibility', 'ada', 'ramp'],
  '8 ft x 36"',
  '800 lbs',
  10,
  '$50-100 per day',
  '1 week',
  ARRAY['Accessibility rental', 'Event rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'accessibility'),
  'Accessible Viewing Platform',
  'accessible-viewing-platform',
  'ADA-compliant elevated viewing platform',
  'Modular platform, ADA compliant, ramp access, railing, 8 ft x 8 ft',
  'each',
  ARRAY['Viewing Platform', 'ADA Platform', 'Wheelchair Platform'],
  ARRAY['accessible', 'viewing', 'platform', 'ada', 'wheelchair', 'elevated'],
  ARRAY['accessibility', 'ada', 'platform'],
  '8 ft x 8 ft',
  '10 wheelchairs',
  4,
  '$200-400 per day',
  '2 weeks',
  ARRAY['Staging companies', 'Accessibility rental'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'accessibility'),
  'Wheelchair (Manual)',
  'wheelchair-manual',
  'Manual wheelchair for guest use',
  'Standard manual wheelchair, foldable, 250 lb capacity',
  'each',
  ARRAY['Wheelchair', 'Manual Wheelchair', 'Guest Wheelchair'],
  ARRAY['wheelchair', 'manual', 'guest', 'accessibility', 'foldable'],
  ARRAY['accessibility', 'wheelchair', 'mobility'],
  'Standard size',
  '250 lbs',
  10,
  '$15-30 per day',
  '3 days',
  ARRAY['Medical equipment', 'Accessibility rental'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'accessibility'),
  'Assistive Listening System (FM)',
  'assistive-listening-system-fm',
  'FM assistive listening system',
  'FM transmitter and 20 receivers, ADA compliant, rechargeable',
  'system',
  ARRAY['Assistive Listening', 'FM System', 'Hearing Assistance'],
  ARRAY['assistive', 'listening', 'fm', 'hearing', 'ada', 'system'],
  ARRAY['accessibility', 'audio', 'hearing'],
  'Transmitter + 20 receivers',
  NULL,
  2,
  '$100-200 per day',
  '1 week',
  ARRAY['AV rental', 'Accessibility services'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'accessibility'),
  'Braille Signage (Custom)',
  'braille-signage-custom',
  'ADA-compliant Braille signage',
  'Tactile Braille signage, ADA compliant, custom text, mounting hardware',
  'each',
  ARRAY['Braille Sign', 'Tactile Sign', 'ADA Sign'],
  ARRAY['braille', 'signage', 'tactile', 'ada', 'custom', 'accessibility'],
  ARRAY['accessibility', 'signage', 'braille'],
  'Custom size',
  NULL,
  30,
  '$20-40 per sign',
  '2 weeks',
  ARRAY['Sign companies', 'Accessibility services'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'site-infrastructure'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'accessibility'),
  'Accessible Parking Sign with Post',
  'accessible-parking-sign-post',
  'ADA accessible parking sign with post',
  'Reflective ADA parking sign, 7 ft post, ground sleeve, compliant',
  'each',
  ARRAY['Handicap Sign', 'ADA Parking Sign', 'Accessible Parking'],
  ARRAY['accessible', 'parking', 'sign', 'ada', 'handicap', 'post'],
  ARRAY['accessibility', 'parking', 'signage'],
  '7 ft post',
  NULL,
  20,
  '$15-30 per day',
  '1 week',
  ARRAY['Sign companies', 'Event rental'],
  true,
  true,
  6
);

COMMIT;
