-- ============================================================================
-- CATALOG - HOSPITALITY AMENITIES & GREEN ROOMS (Comprehensive)
-- Green room furniture, appliances, dressing room equipment, and amenities
-- ============================================================================

BEGIN;

-- ============================================================================
-- HOSPITALITY - GREEN ROOMS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  dimensions, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'green-rooms'),
  'Refrigerator (Mini Fridge)',
  'refrigerator-mini-fridge',
  'Compact refrigerator for green rooms',
  '3.2 cu ft capacity, adjustable thermostat, reversible door',
  'each',
  ARRAY['Mini Fridge', 'Compact Fridge', 'Small Refrigerator'],
  ARRAY['refrigerator', 'mini', 'fridge', 'compact', 'green', 'room'],
  ARRAY['hospitality', 'appliance', 'green room'],
  '19" x 18" x 20"',
  '120V',
  15,
  '$25-50 per day',
  '3 days',
  ARRAY['Appliance rental', 'Event rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'green-rooms'),
  'Microwave (1000W)',
  'microwave-1000w',
  'Countertop microwave oven',
  '1000W, 1.1 cu ft capacity, digital controls, turntable',
  'each',
  ARRAY['Microwave', 'Microwave Oven'],
  ARRAY['microwave', 'oven', '1000w', 'countertop', 'green', 'room'],
  ARRAY['hospitality', 'appliance', 'green room'],
  '20" x 16" x 12"',
  '120V',
  12,
  '$15-30 per day',
  '3 days',
  ARRAY['Appliance rental', 'Event rental'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'green-rooms'),
  'Coffee Maker (12-cup)',
  'coffee-maker-12-cup',
  'Programmable 12-cup coffee maker',
  '12-cup capacity, programmable, auto shut-off, warming plate',
  'each',
  ARRAY['Coffee Maker', 'Coffee Machine', 'Drip Coffee'],
  ARRAY['coffee', 'maker', 'machine', '12', 'cup', 'drip'],
  ARRAY['hospitality', 'appliance', 'beverage'],
  '12" x 8" x 14"',
  '120V',
  10,
  '$10-20 per day',
  '3 days',
  ARRAY['Appliance rental', 'Event rental'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'green-rooms'),
  'Keurig Coffee Maker',
  'keurig-coffee-maker',
  'Single-serve Keurig coffee maker',
  'K-cup compatible, multiple brew sizes, auto shut-off',
  'each',
  ARRAY['Keurig', 'K-Cup Machine', 'Single Serve Coffee'],
  ARRAY['keurig', 'k-cup', 'coffee', 'single', 'serve', 'maker'],
  ARRAY['hospitality', 'appliance', 'beverage'],
  '10" x 10" x 12"',
  '120V',
  15,
  '$15-30 per day',
  '3 days',
  ARRAY['Appliance rental', 'Event rental'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'green-rooms'),
  'Sofa (3-Seater)',
  'sofa-3-seater',
  'Comfortable 3-seater sofa',
  'Upholstered 3-seater sofa, various colors, comfortable seating',
  'each',
  ARRAY['Sofa', 'Couch', '3-Seater', 'Lounge Furniture'],
  ARRAY['sofa', 'couch', '3', 'seater', 'lounge', 'furniture'],
  ARRAY['hospitality', 'furniture', 'seating'],
  '84" x 36" x 36"',
  NULL,
  8,
  '$50-100 per day',
  '1 week',
  ARRAY['Furniture rental', 'Event rental'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'green-rooms'),
  'Armchair (Lounge)',
  'armchair-lounge',
  'Comfortable lounge armchair',
  'Upholstered armchair, various colors, comfortable seating',
  'each',
  ARRAY['Armchair', 'Lounge Chair', 'Accent Chair'],
  ARRAY['armchair', 'lounge', 'chair', 'accent', 'furniture'],
  ARRAY['hospitality', 'furniture', 'seating'],
  '32" x 34" x 36"',
  NULL,
  12,
  '$25-50 per day',
  '1 week',
  ARRAY['Furniture rental', 'Event rental'],
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'green-rooms'),
  'Coffee Table',
  'coffee-table',
  'Modern coffee table',
  'Wood or glass top, various styles, sturdy construction',
  'each',
  ARRAY['Coffee Table', 'Center Table', 'Lounge Table'],
  ARRAY['coffee', 'table', 'center', 'lounge', 'furniture'],
  ARRAY['hospitality', 'furniture', 'table'],
  '48" x 24" x 18"',
  NULL,
  10,
  '$20-40 per day',
  '1 week',
  ARRAY['Furniture rental', 'Event rental'],
  true,
  true,
  7
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'green-rooms'),
  'TV (55" LED)',
  'tv-55-led',
  '55-inch LED television',
  '55" LED TV, 1080p or 4K, HDMI inputs, stand or wall mount',
  'each',
  ARRAY['Television', 'TV', 'LED TV', 'Flat Screen'],
  ARRAY['tv', 'television', '55', 'led', 'flat', 'screen'],
  ARRAY['hospitality', 'entertainment', 'display'],
  '55" diagonal',
  '120V',
  8,
  '$50-100 per day',
  '1 week',
  ARRAY['AV rental', 'Electronics rental'],
  true,
  true,
  8
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'green-rooms'),
  'Sound System (Bluetooth Speaker)',
  'sound-system-bluetooth-speaker',
  'Portable Bluetooth speaker system',
  'Bluetooth connectivity, rechargeable, high-quality sound',
  'each',
  ARRAY['Bluetooth Speaker', 'Portable Speaker', 'Wireless Speaker'],
  ARRAY['bluetooth', 'speaker', 'portable', 'wireless', 'sound'],
  ARRAY['hospitality', 'audio', 'entertainment'],
  'Portable',
  'Battery or AC',
  12,
  '$15-30 per day',
  '3 days',
  ARRAY['AV rental', 'Electronics rental'],
  true,
  true,
  9
);

-- ============================================================================
-- HOSPITALITY - DRESSING ROOMS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  dimensions,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'dressing-rooms'),
  'Vanity Mirror with Lights',
  'vanity-mirror-with-lights',
  'Hollywood-style vanity mirror with lights',
  'Lighted vanity mirror, adjustable brightness, 32" x 26", wall or tabletop',
  'each',
  ARRAY['Vanity Mirror', 'Makeup Mirror', 'Hollywood Mirror'],
  ARRAY['vanity', 'mirror', 'lights', 'makeup', 'hollywood', 'lighted'],
  ARRAY['hospitality', 'dressing room', 'mirror'],
  '32" x 26"',
  10,
  '$30-60 per day',
  '1 week',
  ARRAY['Event rental', 'Theater rental'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'dressing-rooms'),
  'Clothing Rack (Heavy Duty)',
  'clothing-rack-heavy-duty',
  'Heavy-duty rolling clothing rack',
  'Commercial-grade garment rack, adjustable height, 400 lb capacity, wheels',
  'each',
  ARRAY['Clothing Rack', 'Garment Rack', 'Wardrobe Rack'],
  ARRAY['clothing', 'rack', 'garment', 'wardrobe', 'rolling', 'heavy'],
  ARRAY['hospitality', 'dressing room', 'storage'],
  '60" x 24" x 72"',
  15,
  '$15-30 per day',
  '3 days',
  ARRAY['Event rental', 'Theater rental'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'dressing-rooms'),
  'Hangers (50-pack)',
  'hangers-50-pack',
  'Plastic or velvet hangers',
  'Non-slip hangers, plastic or velvet, 50-pack',
  'pack',
  ARRAY['Hangers', 'Clothes Hangers', 'Garment Hangers'],
  ARRAY['hangers', 'clothes', 'garment', 'plastic', 'velvet', '50'],
  ARRAY['hospitality', 'dressing room', 'supplies'],
  'Standard size',
  20,
  '$10-20 per pack',
  '3 days',
  ARRAY['Event rental', 'Retail suppliers'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'dressing-rooms'),
  'Full-Length Mirror (Freestanding)',
  'full-length-mirror-freestanding',
  'Freestanding full-length mirror',
  'Full-length mirror, 60" height, freestanding with base',
  'each',
  ARRAY['Full Mirror', 'Standing Mirror', 'Floor Mirror'],
  ARRAY['full', 'length', 'mirror', 'freestanding', 'floor', 'standing'],
  ARRAY['hospitality', 'dressing room', 'mirror'],
  '60" x 20"',
  12,
  '$20-40 per day',
  '1 week',
  ARRAY['Event rental', 'Furniture rental'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'dressing-rooms'),
  'Steamer (Garment)',
  'steamer-garment',
  'Professional garment steamer',
  'Standing garment steamer, 1500W, continuous steam, 1.8L tank',
  'each',
  ARRAY['Garment Steamer', 'Clothes Steamer', 'Steam Iron'],
  ARRAY['steamer', 'garment', 'clothes', 'steam', 'iron', 'wrinkle'],
  ARRAY['hospitality', 'dressing room', 'appliance'],
  'Standing unit',
  8,
  '$20-40 per day',
  '3 days',
  ARRAY['Appliance rental', 'Event rental'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'dressing-rooms'),
  'Ironing Board with Iron',
  'ironing-board-with-iron',
  'Ironing board with steam iron',
  'Standard ironing board with steam iron, adjustable height',
  'set',
  ARRAY['Ironing Board', 'Iron', 'Ironing Set'],
  ARRAY['ironing', 'board', 'iron', 'steam', 'press', 'clothes'],
  ARRAY['hospitality', 'dressing room', 'appliance'],
  'Standard size',
  6,
  '$15-30 per day',
  '3 days',
  ARRAY['Appliance rental', 'Event rental'],
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'dressing-rooms'),
  'Makeup Station (Portable)',
  'makeup-station-portable',
  'Portable makeup station with storage',
  'Rolling makeup case with drawers, mirror, and lights',
  'each',
  ARRAY['Makeup Station', 'Makeup Case', 'Beauty Station'],
  ARRAY['makeup', 'station', 'portable', 'case', 'beauty', 'rolling'],
  ARRAY['hospitality', 'dressing room', 'makeup'],
  'Rolling case',
  4,
  '$40-80 per day',
  '1 week',
  ARRAY['Event rental', 'Theater rental'],
  true,
  true,
  7
);

-- ============================================================================
-- HOSPITALITY - AMENITIES
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  typical_quantity, estimated_cost, lead_time,
  is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'amenities'),
  'Towel Service (Per Person)',
  'towel-service-per-person',
  'Fresh towel service with laundry',
  'Fresh towels provided, laundry service included, per person per day',
  'person',
  ARRAY['Towels', 'Towel Service', 'Laundry Service'],
  ARRAY['towel', 'service', 'laundry', 'fresh', 'clean'],
  ARRAY['hospitality', 'amenity', 'laundry'],
  100,
  '$5-10 per person/day',
  '1 week',
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'amenities'),
  'Toiletries Kit',
  'toiletries-kit',
  'Individual toiletries kit',
  'Shampoo, conditioner, soap, lotion, toothbrush, toothpaste',
  'kit',
  ARRAY['Toiletries', 'Amenity Kit', 'Personal Care'],
  ARRAY['toiletries', 'kit', 'amenity', 'shampoo', 'soap', 'personal'],
  ARRAY['hospitality', 'amenity', 'personal care'],
  100,
  '$5-10 per kit',
  '1 week',
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'amenities'),
  'Snack Basket (Per Room)',
  'snack-basket-per-room',
  'Curated snack basket',
  'Assorted snacks, candy, chips, nuts, per room',
  'basket',
  ARRAY['Snack Basket', 'Snacks', 'Amenity Basket'],
  ARRAY['snack', 'basket', 'amenity', 'candy', 'chips', 'nuts'],
  ARRAY['hospitality', 'amenity', 'food'],
  20,
  '$20-40 per basket',
  '3 days',
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'amenities'),
  'Fresh Flowers (Arrangement)',
  'fresh-flowers-arrangement',
  'Fresh flower arrangement',
  'Fresh cut flowers in vase, various styles',
  'arrangement',
  ARRAY['Flowers', 'Floral Arrangement', 'Fresh Flowers'],
  ARRAY['flowers', 'fresh', 'arrangement', 'floral', 'vase'],
  ARRAY['hospitality', 'amenity', 'decor'],
  15,
  '$30-75 per arrangement',
  '3 days',
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'hospitality'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'amenities'),
  'Welcome Gift Bag',
  'welcome-gift-bag',
  'Custom welcome gift bag',
  'Branded gift bag with local items, swag, and welcome materials',
  'bag',
  ARRAY['Gift Bag', 'Welcome Bag', 'Swag Bag'],
  ARRAY['welcome', 'gift', 'bag', 'swag', 'branded', 'local'],
  ARRAY['hospitality', 'amenity', 'gift'],
  100,
  '$15-50 per bag',
  '2 weeks',
  true,
  true,
  5
);

COMMIT;
