-- ============================================================================
-- CATALOG - SCENIC ELEMENTS & SHOW POWER (Comprehensive)
-- Backdrops, scrims, draping, and power distribution equipment
-- ============================================================================

BEGIN;

-- ============================================================================
-- TECHNICAL PRODUCTION - SCENIC ELEMENTS
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  dimensions, material,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scenic-elements'),
  'Cyc Wall (Seamless, 20 ft x 12 ft)',
  'cyc-wall-20x12',
  'Seamless cyclorama backdrop',
  'Seamless muslin cyc, 20 ft wide x 12 ft tall, white or black, fire-rated',
  'each',
  ARRAY['Cyc', 'Cyclorama', 'Backdrop', 'Seamless Backdrop'],
  ARRAY['cyc', 'cyclorama', 'backdrop', 'seamless', '20x12', 'muslin'],
  ARRAY['scenic', 'backdrop', 'cyc'],
  '20 ft x 12 ft',
  'Muslin',
  4,
  '$100-200 per day',
  '2 weeks',
  ARRAY['Scenic rental', 'Theater rental', 'Event production'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scenic-elements'),
  'Backdrop (Painted, 16 ft x 10 ft)',
  'backdrop-painted-16x10',
  'Custom painted backdrop',
  'Hand-painted or printed backdrop, 16 ft x 10 ft, grommets for hanging',
  'each',
  ARRAY['Backdrop', 'Painted Backdrop', 'Scenic Backdrop'],
  ARRAY['backdrop', 'painted', 'scenic', '16x10', 'custom'],
  ARRAY['scenic', 'backdrop', 'painted'],
  '16 ft x 10 ft',
  'Canvas',
  6,
  '$150-300 per day',
  '4 weeks',
  ARRAY['Scenic rental', 'Theater rental'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scenic-elements'),
  'Scrim (Sharkstooth, 20 ft x 12 ft)',
  'scrim-sharkstooth-20x12',
  'Sharkstooth scrim for projection',
  'Sharkstooth scrim, 20 ft x 12 ft, white or black, projection surface',
  'each',
  ARRAY['Scrim', 'Sharkstooth', 'Projection Scrim'],
  ARRAY['scrim', 'sharkstooth', 'projection', '20x12', 'screen'],
  ARRAY['scenic', 'scrim', 'projection'],
  '20 ft x 12 ft',
  'Sharkstooth fabric',
  4,
  '$75-150 per day',
  '2 weeks',
  ARRAY['Scenic rental', 'Theater rental'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scenic-elements'),
  'Projection Screen (16:9, 20 ft)',
  'projection-screen-16-9-20ft',
  'Front projection screen',
  '16:9 aspect ratio, 20 ft diagonal, matte white, frame or truss mount',
  'each',
  ARRAY['Projection Screen', 'Screen', 'Video Screen'],
  ARRAY['projection', 'screen', '16:9', '20', 'feet', 'video'],
  ARRAY['scenic', 'projection', 'screen'],
  '20 ft diagonal',
  'PVC',
  4,
  '$100-200 per day',
  '1 week',
  ARRAY['AV rental', 'Projection rental'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scenic-elements'),
  'Rear Projection Screen (16:9, 15 ft)',
  'rear-projection-screen-16-9-15ft',
  'Rear projection screen',
  '16:9 aspect ratio, 15 ft diagonal, translucent, frame mount',
  'each',
  ARRAY['Rear Screen', 'RP Screen', 'Translucent Screen'],
  ARRAY['rear', 'projection', 'screen', '16:9', '15', 'translucent'],
  ARRAY['scenic', 'projection', 'screen'],
  '15 ft diagonal',
  'Translucent PVC',
  3,
  '$150-300 per day',
  '2 weeks',
  ARRAY['AV rental', 'Projection rental'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scenic-elements'),
  'Pipe and Drape (8 ft H x 10 ft W)',
  'pipe-and-drape-8x10',
  'Adjustable pipe and drape system',
  'Adjustable uprights, crossbar, drape panels, 8 ft H x 10 ft W section',
  'section',
  ARRAY['Pipe and Drape', 'Draping', 'Room Divider'],
  ARRAY['pipe', 'drape', 'draping', '8', '10', 'divider', 'backdrop'],
  ARRAY['scenic', 'draping', 'pipe and drape'],
  '8 ft H x 10 ft W',
  'Fabric',
  30,
  '$15-30 per section/day',
  '1 week',
  ARRAY['Event rental', 'Draping rental'],
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scenic-elements'),
  'Velour Drape (10 ft H x 5 ft W)',
  'velour-drape-10x5',
  'Premium velour drape panel',
  'Heavyweight velour, 10 ft H x 5 ft W, grommets, various colors',
  'panel',
  ARRAY['Velour', 'Drape', 'Curtain', 'Fabric Panel'],
  ARRAY['velour', 'drape', 'curtain', '10x5', 'fabric', 'panel'],
  ARRAY['scenic', 'draping', 'fabric'],
  '10 ft H x 5 ft W',
  'Velour',
  50,
  '$20-40 per panel/day',
  '1 week',
  ARRAY['Event rental', 'Draping rental'],
  true,
  true,
  7
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scenic-elements'),
  'Sheer Drape (12 ft H x 5 ft W)',
  'sheer-drape-12x5',
  'Sheer voile drape panel',
  'Lightweight sheer voile, 12 ft H x 5 ft W, grommets, white or ivory',
  'panel',
  ARRAY['Sheer', 'Voile', 'Drape', 'Curtain'],
  ARRAY['sheer', 'voile', 'drape', 'curtain', '12x5', 'lightweight'],
  ARRAY['scenic', 'draping', 'sheer'],
  '12 ft H x 5 ft W',
  'Voile',
  40,
  '$15-30 per panel/day',
  '1 week',
  ARRAY['Event rental', 'Draping rental'],
  true,
  true,
  8
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scenic-elements'),
  'Scenic Flat (4 ft x 8 ft)',
  'scenic-flat-4x8',
  'Theatrical scenic flat',
  'Hollywood flat, 4 ft x 8 ft, muslin covered, paintable',
  'each',
  ARRAY['Flat', 'Scenic Flat', 'Hollywood Flat', 'Wall Flat'],
  ARRAY['scenic', 'flat', 'hollywood', '4x8', 'wall', 'theater'],
  ARRAY['scenic', 'flat', 'set piece'],
  '4 ft x 8 ft',
  'Wood frame/muslin',
  20,
  '$25-50 per day',
  '2 weeks',
  ARRAY['Scenic rental', 'Theater rental'],
  true,
  true,
  9
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'scenic-elements'),
  'Masking Legs (10 ft H x 3 ft W)',
  'masking-legs-10x3',
  'Stage masking legs',
  'Black velour masking legs, 10 ft H x 3 ft W, grommets',
  'pair',
  ARRAY['Masking', 'Legs', 'Stage Masking', 'Side Masking'],
  ARRAY['masking', 'legs', 'stage', 'side', '10x3', 'velour'],
  ARRAY['scenic', 'masking', 'stage'],
  '10 ft H x 3 ft W',
  'Velour',
  12,
  '$30-60 per pair/day',
  '1 week',
  ARRAY['Theater rental', 'Staging companies'],
  true,
  true,
  10
);

-- ============================================================================
-- TECHNICAL PRODUCTION - SHOW POWER
-- ============================================================================

INSERT INTO catalog_items (
  category_id, subcategory_id, name, slug, description, specifications,
  standard_unit, alternate_names, search_terms, tags,
  dimensions, power_requirements,
  typical_quantity, estimated_cost, lead_time,
  common_vendors, is_global, active, "order"
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'show-power'),
  'Distro Box (400A Cam-Lok)',
  'distro-box-400a-camlok',
  '400A power distribution box',
  '400A Cam-Lok input, 6x 100A outputs, circuit breakers, weatherproof',
  'each',
  ARRAY['Distro', 'Power Distro', 'Distribution Box', 'Cam-Lok Distro'],
  ARRAY['distro', 'distribution', 'box', '400a', 'camlok', 'power'],
  ARRAY['power', 'distribution', 'electrical'],
  '24" x 18" x 12"',
  '400A input',
  4,
  '$150-300 per day',
  '2 weeks',
  ARRAY['Power rental', 'Production electrical'],
  true,
  true,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'show-power'),
  'Distro Box (200A Cam-Lok)',
  'distro-box-200a-camlok',
  '200A power distribution box',
  '200A Cam-Lok input, 6x 60A outputs, circuit breakers, weatherproof',
  'each',
  ARRAY['Distro', 'Power Distro', 'Distribution Box'],
  ARRAY['distro', 'distribution', 'box', '200a', 'camlok', 'power'],
  ARRAY['power', 'distribution', 'electrical'],
  '20" x 16" x 10"',
  '200A input',
  6,
  '$100-200 per day',
  '1 week',
  ARRAY['Power rental', 'Production electrical'],
  true,
  true,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'show-power'),
  'Cam-Lok Cable (4/0, 50 ft)',
  'camlok-cable-4-0-50ft',
  '50-foot 4/0 Cam-Lok feeder cable',
  '4/0 AWG, 50 ft, Cam-Lok connectors, 400A rated, SOOW',
  'each',
  ARRAY['Cam-Lok Cable', 'Feeder Cable', 'Power Cable'],
  ARRAY['camlok', 'cable', 'feeder', '4/0', '50', 'feet', 'power'],
  ARRAY['power', 'cable', 'camlok'],
  '50 ft',
  '400A',
  20,
  '$25-50 per day',
  '1 week',
  ARRAY['Power rental', 'Cable rental'],
  true,
  true,
  3
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'show-power'),
  'Cam-Lok Cable (2/0, 50 ft)',
  'camlok-cable-2-0-50ft',
  '50-foot 2/0 Cam-Lok feeder cable',
  '2/0 AWG, 50 ft, Cam-Lok connectors, 200A rated, SOOW',
  'each',
  ARRAY['Cam-Lok Cable', 'Feeder Cable', 'Power Cable'],
  ARRAY['camlok', 'cable', 'feeder', '2/0', '50', 'feet', 'power'],
  ARRAY['power', 'cable', 'camlok'],
  '50 ft',
  '200A',
  30,
  '$20-40 per day',
  '1 week',
  ARRAY['Power rental', 'Cable rental'],
  true,
  true,
  4
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'show-power'),
  'Bates Cable (100 ft)',
  'bates-cable-100ft',
  '100-foot Bates stage pin cable',
  '100 ft, 12/3 SOOW, Bates stage pin connectors, 20A',
  'each',
  ARRAY['Bates Cable', 'Stage Pin Cable', 'Power Cable'],
  ARRAY['bates', 'cable', 'stage', 'pin', '100', 'feet', 'power'],
  ARRAY['power', 'cable', 'bates'],
  '100 ft',
  '20A',
  40,
  '$10-20 per day',
  '1 week',
  ARRAY['Power rental', 'Theater rental'],
  true,
  true,
  5
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'show-power'),
  'Edison Multi-Cable (6-channel, 100 ft)',
  'edison-multi-cable-6ch-100ft',
  '6-channel Edison multi-cable',
  '100 ft, 6x 20A Edison circuits, 12/3 SOOW, breakouts',
  'each',
  ARRAY['Multi-Cable', 'Edison Multi', 'Mult Cable', 'Socapex'],
  ARRAY['edison', 'multi', 'cable', '6', 'channel', '100', 'feet'],
  ARRAY['power', 'cable', 'multi-cable'],
  '100 ft',
  '6x 20A',
  20,
  '$20-40 per day',
  '1 week',
  ARRAY['Power rental', 'Production electrical'],
  true,
  true,
  6
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'show-power'),
  'Socapex Breakout (6-way)',
  'socapex-breakout-6-way',
  '6-way Socapex breakout',
  'Socapex 19-pin to 6x Edison outlets, 20A per circuit',
  'each',
  ARRAY['Socapex', 'Breakout', 'Multi Breakout', '6-way'],
  ARRAY['socapex', 'breakout', '6', 'way', 'edison', 'multi'],
  ARRAY['power', 'breakout', 'socapex'],
  'Breakout box',
  '20A per circuit',
  15,
  '$10-20 per day',
  '1 week',
  ARRAY['Power rental', 'Production electrical'],
  true,
  true,
  7
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'show-power'),
  'Power Tap (3-way Edison)',
  'power-tap-3-way-edison',
  '3-way Edison power tap',
  'In-line 3-way Edison tap, 20A, SOOW cable',
  'each',
  ARRAY['Power Tap', 'Edison Tap', '3-Way Tap', 'Inline Tap'],
  ARRAY['power', 'tap', '3', 'way', 'edison', 'inline'],
  ARRAY['power', 'tap', 'adapter'],
  'Inline',
  '20A',
  30,
  '$5-10 per day',
  '3 days',
  ARRAY['Power rental', 'Production electrical'],
  true,
  true,
  8
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'show-power'),
  'Ground Fault Interrupter (Portable)',
  'gfi-portable',
  'Portable ground fault interrupter',
  'In-line GFI, 20A, NEMA 5-20, automatic reset',
  'each',
  ARRAY['GFI', 'GFCI', 'Ground Fault', 'Safety Device'],
  ARRAY['gfi', 'gfci', 'ground', 'fault', 'interrupter', 'safety'],
  ARRAY['power', 'safety', 'gfi'],
  'Inline',
  '20A',
  20,
  '$10-20 per day',
  '3 days',
  ARRAY['Power rental', 'Safety equipment'],
  true,
  true,
  9
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'technical-production'),
  (SELECT id FROM catalog_subcategories WHERE slug = 'show-power'),
  'Cable Ramp (5-channel)',
  'cable-ramp-5-channel',
  '5-channel cable protector ramp',
  'Heavy-duty rubber cable ramp, 5 channels, vehicle rated, modular',
  'section',
  ARRAY['Cable Ramp', 'Cable Protector', 'Cable Guard', 'Yellow Jacket'],
  ARRAY['cable', 'ramp', 'protector', 'guard', '5', 'channel', 'yellow'],
  ARRAY['power', 'cable management', 'safety'],
  '36" length',
  NULL,
  30,
  '$10-20 per section/day',
  '1 week',
  ARRAY['Power rental', 'Safety equipment'],
  true,
  true,
  10
);

COMMIT;
